packages/tokens/properties/color/base.json
Color migration still needs a true white (#FFFFFF) available, so we're setting that to white, and moving the current white to grey-50.
`npm start` and check http://localhost:6006/?path=/story/tokens--page to ensure the token is present
`lerna run build`
=> improvement(color): move white to grey-50 and change white to #FFFFFF

.gitignore, CHANGELOG.md, README.md, lerna.json, package.json, packages/components/CHANGELOG.md, packages/components/package-lock.json, packages/components/package.json, packages/styles/CHANGELOG.md, packages/styles/package-lock.json, packages/styles/package.json, packages/tokens/CHANGELOG.md, packages/tokens/package-lock.json, packages/tokens/package.json
Update versions for published [v0.0.1-alpha.1](https://www.npmjs.com/package/@chanzuckerberg/czedi-kit-tokens/v/0.0.1-alpha.1)
=> Dcwither/v0.0.1 alpha.1

package.json, packages/components/src/tokens.stories.mdx, packages/tokens/package-lock.json, packages/tokens/package.json, packages/tokens/properties/color/base.json
Ad design system colors from https://www.figma.com/file/sKEhNrLEdexPeVVn58dkWx/SDL-(Summit-Design-Language)-Explorations?node-id=690%3A0. Uses the eds prefix for now, we can revisit later before a 1.0.0 launch.
Ran in storybook with `npm start` to confirm new colors are added.
TODO: use new colors with tailwind etc.
=> feat(colors): add eds colors to tokens

.gitignore
as titled, I might have saved my vscode workspace in a bad spot and this seemed easier than moving it
n/a
=> chore: add vscode workspace to gitignore

packages/components/.babelrc, packages/components/.storybook/preview.tsx, packages/components/jest.config.js, packages/components/package-lock.json, packages/components/package.json
Following https://github.com/chanzuckerberg/lp-design-system/issues/212, switches to using babel. This is a prereq for using Linaria
```
npm run build
```
should successfully compile 1 file (`dist/button/button.js` ), ignoring `spec` and `stories` files, and 1 declarations file (`dist/button.d.ts`)
=> build: use babel for compilation

.eslintrc, packages/components/jest.config.js, packages/components/package-lock.json, packages/components/package.json, packages/components/src/playground/button.spec.tsx, packages/components/src/typography/typography.spec.tsx, packages/components/test/jest.setup.ts, packages/components/test/removeClassSnapshotSerializer.ts
Pulled `https://github.com/chanzuckerberg/along/blob/main/client/src/test/removeStylesJestSerializer.ts` from along - we should consider moving this into https://github.com/chanzuckerberg/frontend-libs
`npm test`
=> test(snapshots): remove classes from snapshots

packages/components/src/styles/global.js, packages/components/src/typography/typography.stories.tsx
https://app.clubhouse.io/connections/story/33653/ds-typography-confirm-with-design-through-percy
Sean pointed out that the Storybook fonts didn't actually look like Arimo -- turns out I wasn't loading the font files properly :')
Confirm storybook type:
Matches Figma:
Especially look at the number 1, because that was clearly off before. Percy changes are expected
=> fix(typography): render Arimo in storybook properly

CHANGELOG.md, lerna.json, packages/components/CHANGELOG.md, packages/components/package-lock.json, packages/components/package.json, packages/tokens/CHANGELOG.md, packages/tokens/package-lock.json, packages/tokens/package.json
[CH task](https://app.clubhouse.io/czi-edu/story/65420/ds-publish-typography-component)
Publishing typography component to start traject migration. Also snuck in the [tailwind config export](https://app.clubhouse.io/czi-edu/story/62334/ds-prep-tailwind-config-for-export)
Run `npx lerna run prepack`, confirm:
- packages/tokens/dist includes `json/css-variables-nested.json`
- packages/components/dist includes
=> chore(release): publish v0.0.1-alpha.6

README.md, packages/components/package-lock.json
I did some silly stuff while trying to publish version alpha.6, including manually changing package-lock.json 😅 
n/a
=> chore: update package-lock and publishing instructions

packages/components/.storybook/preview-body.html, packages/components/README.md, packages/components/src/Heading/Heading.tsx, packages/components/src/Text/Text.tsx, packages/components/src/playground/button.tsx
We shouldn't be setting `font-arimo` everywhere -- this adds it to root Storybook styles & add some instruction for external projects
Percy should show no visual changes
=> refactor: remove font-arimo from components

package.json, packages/components/generateFlowTypes.sh, packages/components/package-lock.json, packages/components/package.json
Add `./generateFlowTypes.sh` as part of `build:types` (ts + flow)
```
➜ components (ch124021) ✗ ./generateFlowTypes.sh
Generating flowtype for dist/Heading/Heading
Parsing Heading
Generating flowtype for dist/Heading/index
Parsing index
Generating flowtype for dist/Text/index
Parsing index
Generating flowtype for dist/Text/Text
Parsing Text
Generating flowtype for dist/index
Parsing index
Generating flowtype for dist/playground/button
Parsing button
Generating flowtype for dist/styles/global
Parsing global
Generating flowtype for dist/util/typography
Parsing typography
```
=> feat(build): add script to generate flow types

.eslintrc, .stylelintrc, packages/components/.babelrc, packages/components/package.json
This fixes conflicts between stylelint's formatter and prettier - allowing prettier to win when they conflict.
```js
css`
property: value;
`
```
autocorrects to 
```js
css`
property: value;
`
```
without stylelint complaining.
=> fix(lint): fix styleint/eslint/prettier integration

.prettierrc, .stylelintrc, packages/components/.storybook/Button/button.stories.tsx, packages/components/package-lock.json, packages/components/package.json, packages/components/src/Button/__snapshots__/button.spec.tsx.snap, packages/components/src/Heading/__snapshots__/Heading.spec.tsx.snap, packages/components/src/Text/__snapshots__/Text.spec.tsx.snap, packages/components/src/util/clickable.module.css, packages/components/src/util/clickable.tsx, packages/components/src/util/typography.module.css, packages/components/src/util/typography.tsx, packages/tokens/style-dictionary.config.js
Let's see what the repo would look like with a different way of referencing css modules! Also since this style doesn't use bind, we can use [`clsx`](https://github.com/lukeed/clsx) which is smaller and more performant than `classnames`.
- `npm test`
- CI
- Percy (should have no differences from buttons)
One benefit that looks like a downside is we have a more accurate picture of our coverage.
=> refactor(classnames): move to camelcase classnames

packages/components/src/Heading/Heading.tsx, packages/components/src/Text/Text.spec.tsx, packages/components/src/Text/Text.tsx, packages/components/src/common/typography.tsx
Allow classname pass through for text. Although this will probably lead to some style overriding in our projects, there's too many valid use cases that we want to support to encode into the text and heading components.
e.g. line clamping, responsive margins, etc.
Added test for Text component with pass through. It felt unnecessary to add another story since this doesn't create an immediately visual change.
=> feat(typography): allow classname pass through on text components

packages/components/.storybook/typography.module.css, packages/components/.storybook/typography.stories.mdx
As teams start refactoring text, the current way we split up each type size into a story is kind of hard to reference. This adds a "Typography Ramp" table to Storybook:
build passes, no codecov or percy changes
=>  chore: add story with entire type ramp

packages/components/src/Text/Text.stories.tsx, packages/components/src/Text/__snapshots__/Text.spec.tsx.snap, packages/components/src/common/typography.module.css, packages/components/src/common/typography.tsx
TLDR: This is not a finished PR, just looking for feedback on the problem/possible solutions re: inheriting color for typography components
When working on the Banner EDS candidate (https://github.com/FB-PLP/traject/pull/6758), one of the suggestions was to pull out a `Banner.Title` component that ensures the `Heading` component styling stays consistent:
```
Banner.Title = function BannerTitle(props: {|
children?: React$Node,
as: string,
|}) {
return (
<Heading as={props.as} size="h3">
{props.children}
</Heading>
);
};
```
and usage would look something like
```
<Banner>
<Banner.Title> Title Content </Banner.Title>
<Banner.Body> Body Content </Banner.Body> 
</Banner>
```
But Heading and Text have a default color value `base`, so the result is that the banner color was being overriden: …
=> feat(typography): allow color passthrough on text components

packages/components/src/Text/Text.spec.tsx, packages/components/src/Text/Text.tsx, packages/components/src/common/typography.tsx
Allow consumers of the `Text` componnent to pass down a `ref` to access the underlying DOM
element directly.
GitHub issue:
https://github.com/chanzuckerberg/edu-design-system/issues/295
Clubhouse story:
https://app.clubhouse.io/czi-edu/story/141247/add-forward-ref-to-heading-text-components
I added a unit test that uses a ref to focus on the text element produced by a <Text/>
element to verify the ref is correctly being passed down.
=> feat(typography): allow ref pass through on Text components

packages/components/src/Heading/Heading.spec.tsx, packages/components/src/Heading/Heading.tsx
Follow-up to https://github.com/chanzuckerberg/edu-design-system/pull/452 in which we allowed refs to pass through `Text` components. Because that one updated the underlying `Typography` component, this PR only has to update `Heading`.
Run the tests and verify they all pass.
=> feat(typography): allow ref to pass through Heading

packages/components/.storybook/Button/button.stories.tsx, packages/components/src/Button/__snapshots__/button.spec.tsx.snap, packages/components/src/Button/button.stories.tsx, packages/components/src/common/clickable.module.css, packages/components/src/common/clickable.tsx
Clubhouse story: https://app.clubhouse.io/czi-edu/story/143864/buttons
This PR adds a couple of small updates to the `Button` component to prepare it for launch:
- re-adds the "warning" color (because we'll need it in the banners)
- adds `display: "inline-flex"` to the button (so icons can be used inside)
- adds 2 stories with a test icon to verify the `flex` change is working as expected
- adds 1 story with a `data-test-id` attribute to verify other important attributes not
explicitly exposed will work with the component
`npm start` to run storybook,
and navigate to the `Button` stories.
Then:
- inspect the `With Data Test Id` button and verify the button element has a `data-test-id` with a value of "fake-test-id"
- verify the `Link With Icon` and `Outline With Icon` stories have the …
=> feat(button): add warning color and display flex

packages/components/.storybook/Button/button.stories.tsx
Clubhouse story: https://app.clubhouse.io/czi-edu/story/143864/buttons
This PR pulls out part of the render template from the `All Variants` `Button`
story and renders it again with a dark dark background and white text.
We could also just render the whole `All Variants` again in this section, but
that felt like overkill to me when we just want to see one size for each color +
variant on a non-white background.
`npm start` to run storybook,
navigate to the `Button` component stories,
verify all the existing stories are unchanged (except the `All Variants` now has darker text outside the buttons),
and verify there is now a new story called `Medium Variants On Dark Background` that has the medium size buttons (flat, outline, and link) on a dark background with white text around the buttons.
=> chore(button): add dark background stories

packages/components/src/Button/__snapshots__/button.spec.tsx.snap, packages/components/src/Button/button.stories.tsx, packages/components/src/Button/button.tsx, packages/components/src/Clickable/Clickable.tsx
This PR accomplishes 2 tasks:
- explicitly allow HTML button attributes on the `Button` props
- use the `className` prop if it's passed into the `Clickable` component
The `Clickable` component already has `className` in the types, and we have a test to verify that it's being applied to the element, but it's currently **removing** the default styles we're adding to the element. This change adds the `className`, if passed in, to the styles list so it exists so they are both applied.
Question: should the `className` be applied at the top or bottom of the stack? I put it at the top so our default styles win out, which I think makes sense for highly opinionated design system components.
It looks like type checking is currently not running on story files, so, to test this, I added a little test …
=> chore(button): specify HTML attr styles, use className on Clickable

packages/components/src/Button/button.stories.tsx, packages/components/src/index.ts
Since we're preparing to release the `Button` package, it seems like it's
the right time to remove the "WIP" title.
Navigate to the button stories in storybook,
and verify the component is just called "Button", not "Button - WIP".
=> chore(button): remove 'WIP' from Button story name

packages/components/src/Clickable/Clickable.module.css
I was pairing with Sean over the `Banner` component and he pointed out that
the outline buttons have a white background when he intended for them to be
transparent.
Currently, these buttons aren't being used anywhere, so I think this is a safe
change to make. Thoughts?
Run storybook,
navigate to the "Medium Variants on Dark Background" story,
verify the outline buttons have a transparent background (except for the hover state, which should be unchanged).
=> chore(buttons): make outline button background transparent

packages/components/src/Clickable/Clickable.module.css, packages/components/tailwind.config.js
The `Clickable` component has a transition for button color change, but
that animation currently does not respect the reduce motion accessibility
setting.
This commit removes the animation for the reduce motion setting.
For some reason I'm still having trouble getting `motion-safe` to work on
transitions. But `motion-reduce:transition-none` did work for me, so I
used that instead and added a comment.
Here's a video of the behavior I was seeing. To make the transition more
obvious, I changed the hover color to `fuchsia` and increased the transition
duration to 1000.
https://user-images.githubusercontent.com/7761701/125968460-97f01fda-eac8-4e9b-a30a-af92fca9f55c.mp4
Run storybook (`npm start`),
navigate to `/?path=/story/button--all-variants`,
hover over the "inactive" buttons,
verify the …
=> feat(clickable): remove animation for reduce motion setting

.vscode/settings.json
Typescript errors weren't showing up inline for me in VSCode 😢  I usually have validation set to false in my User workspace because of traject (sad), so this should turn it on for the EDS project always
Forced an error in a file and confirmed inline error shows up:
=> chore: show ts errors inline in VSCode

packages/components/src/Banner/Banner.module.css, packages/components/src/Banner/Banner.stories.tsx, packages/components/src/Banner/Banner.tsx, packages/components/src/Banner/__snapshots__/Banner.spec.tsx.snap
We have 3 different levels of padding on the `Banner` component. The reasoning was that larger banners with lots of text need more padding or they look really cramped. But we actually don't want people to put lots of text into banners and are going to advice against it. So why would we support this version of the component?
This PR removes the padding props and also the stories that show the banner with lots of text. I verified with Sean that it's safe to remove these.
Verify Percy shows there are no changed stories (besides the ones removed).
=> chore(banner): remove padding props and long stories

packages/components/src/Banner/index.ts, packages/components/src/Toast/Toast.module.css, packages/components/src/Toast/Toast.spec.tsx, packages/components/src/Toast/Toast.stories.tsx, packages/components/src/Toast/Toast.tsx, packages/components/src/Toast/__snapshots__/Toast.spec.tsx.snap, packages/components/src/Toast/index.ts, packages/components/src/index.ts, packages/components/tailwind.config.js
Clubhouse ticket: https://app.clubhouse.io/czi-edu/story/149308/toast-done
Minimal changes made from the `traject` version just for moving from flow to typescript and satisfying the linter.
Run storybook (`npm start`),
navigate to `/?path=/docs/toast--success`,
verify the 3 stories are rendering just like in `traject` including the dark round hover state of the dismiss button.
=> feat(toast): copy Toast from traject

packages/components/src/Tag/Tag.module.css, packages/components/src/Tag/Tag.spec.tsx, packages/components/src/Tag/Tag.stories.module.css, packages/components/src/Tag/Tag.stories.tsx, packages/components/src/Tag/Tag.tsx, packages/components/src/Tag/__snapshots__/Tag.spec.tsx.snap, packages/components/src/Tag/index.ts, packages/components/src/common/typography.tsx, packages/components/src/index.ts
Clubhouse ticket: https://app.clubhouse.io/czi-edu/story/149292/tags-done
Minimal changes made just to move from flow to typescript and to satisfy the linter.
Run storybook (`npm start`),
navigate to `/?path=/docs/tag--default`,
and verify the stories output is identical to the ones in `traject`.
=> feat(tag): copy Tag over from traject

packages/components/.storybook/Button/button.stories.tsx, packages/components/.storybook/preview.tsx, packages/components/docs/token-table.tsx, packages/components/src/Banner/Banner.spec.tsx, packages/components/src/Banner/Banner.stories.tsx, packages/components/src/Banner/Banner.tsx, packages/components/src/Banner/index.ts, packages/components/src/Button/button.stories.tsx, packages/components/src/Clickable/Clickable.stories.tsx, packages/components/src/Heading/Heading.stories.tsx, packages/components/src/SVGIcon/SVGIcon.stories.tsx, packages/components/src/SVGIcon/SVGIcon.tsx, packages/components/src/SVGIcon/index.tsx, packages/components/src/Tag/Tag.spec.tsx, packages/components/src/Tag/Tag.stories.tsx, packages/components/src/Tag/Tag.tsx, packages/components/src/Text/Text.stories.tsx, packages/components/src/Toast/Toast.spec.tsx, packages/components/src/Toast/Toast.stories.tsx, packages/components/src/Toast/Toast.tsx, packages/components/src/Toast/index.ts, plop-templates/Component/Component.stories.tsx.hbs
Follow-up to https://github.com/chanzuckerberg/edu-design-system/pull/519
This PR changes 3 recurring issues that are left over after bringing in code that once used flow but is now typescript:
- remove `// @flow` from the top of files
- change `React.ElementProps` to `React.ComponentProps`
- change `import * as React from "react";` to `import React from "react";`
The last pattern existed in a bunch of files, not just ones ported over recently, so I just updated everything to be consistent.
- automated tests pass
- check out storybook (`npm start`) and verify there are no changes to the UI
=> chore: remove flow remnants

.github/workflows/test.yml, package.json, packages/components/package.json, packages/components/src/Banner/Banner.stories.tsx, packages/components/src/Button/button.stories.tsx, packages/components/src/Button/button.tsx, packages/components/src/Heading/Heading.spec.tsx, packages/components/src/Heading/Heading.tsx, packages/components/src/SVGIcon/SVGIcon.stories.tsx, packages/components/src/Tag/Tag.stories.tsx, packages/components/src/Text/Text.spec.tsx, packages/components/src/Text/Text.stories.tsx, packages/components/src/Text/Text.tsx, packages/components/tsconfig.json, packages/tokens/package.json
[ch147126]
This PR
- Adds a script for running typescript locally. Can run `npm run types` at either the top level or packages/components.
- Adds a separate CI step for type checking. Technically this is duplicate work with the build step. But it could make what's going on more obvious.
- Enable type checking for stories and tests
- Allow Text and Heading components to receive `tabIndex`
- Ignore type errors in SvgIcon, for now. We'll need to figure out what the types should be there.
- ~~Use `React.ComponentProps` instead of `React.ElementProps`~~ Handled by #524
- ~~Remove the Flow pattern of `import * as React from "react"`, which isn't necessary here~~ Handled by #524
- Various type fixes
- Update package author to "CZI"
- CI
=> Various cleanups

packages/components/src/Banner/Banner.tsx, packages/components/src/SVGIcon/SVGIcon.tsx, packages/components/src/Tag/Tag.tsx, packages/components/src/Toast/Toast.tsx
I ported over several components that are using `cx` (`classnames`), but the rest of the components are using `clsx`. This PR just updates all usage of `cx` to `clsx`.
I added this to the list of things we might want to automatically update when porting over a component: https://app.clubhouse.io/czi-edu/story/150855/write-migration-script-for-components-from-traject-eds
Spot check that there are no changes in styling in storybook.
=> chore: use clsx instead of cx

packages/components/src/Banner/Banner.module.css
Small cleanup here.
The dismiss button on the `Banner` component is inheriting it's `transition` styles, including `motion-reduce`, from the underlying `Button` component. This PR removes the transition logic from the `Banner`, updates the comment to state why there is no transition logic, and moves the 2nd hover style so the 2 are grouped together.
Run storybook (`npm start`),
navigate to `/?path=/story/banner--brand-dismissable`, 
hover over the dismiss icon,
verify there's a very subtle transition in the hover effect (you can add `duration-1000` to line 34 to make the transition more obvious),
open your accessibility software settings,
turn on "reduce motion",
hover over the dismiss button again,
verify the subtle transition is gone.
=> chore(banner): clean up dismiss hover styles

packages/components/src/Text/Text.stories.tsx, packages/components/src/Text/Text.tsx
I figure most `Text` instances will be `"body"` sized, so why not make that the default and reduce a little repetition?
Verify there are no Percy changes on this story and typecheck passes.
=> chore(text): make "body" default size

packages/components/src/SvgIcon/SvgIcon.stories.tsx, packages/components/src/SvgIcon/SvgIcon.tsx
Removes the `ts-ignore`s from SVGIcon.stories.tsx. Next PR will add `createSvgIcon` and a license statement
- tsc passes
- confirmed that passing something like `role: "test"` still
fails type checking
=> chore: fix SvgIcon story types

README.md, package.json
This PR adds scripts for publishing, to make it easier. Now to publish you'd
- Run `npm run create-releases`
- Check that everything looks right
- Run `npm run publish-releases`
- Run `git push origin head --follow-tags`
- Test publish
=> Scripts for easy package publishing

packages/components/src/SvgIcon/SvgIcon.tsx, packages/components/src/SvgIcon/index.tsx, packages/components/src/index.ts
Allow `<SvgIcon>` to be used from the components package. That way we can look at using it in Learning Platform and Along.
- CI
=> Export SvgIcon from the components package

codecov.yml
[ch150553]
We already have pretty high code coverage, and it's not useful for codecov to block builds at this point. I'm choosing to keep it and just turn it to "informational" mode (non-blocking), in case it does start producing useful insights lol
- created a commit that removed all button tests, just for testing
- ensured that [codecov check passes](https://codecov.io/gh/chanzuckerberg/edu-design-system/commit/7f0b985fd561db14f5be886d5b3f86439ee9602b) even though coverage decreased
(I'll remove this commit after approval)
=> ci: set codecov to informational mode

package.json, scripts/updateYarnLockForLerna.sh
Hat tip @anniehu4 for the idea here
Currently Lerna doesn't update yarn.lock files when dependencies between monorepo packages increment. See https://github.com/lerna/lerna/issues/1171.
To work around that, we manually install deps during publishing so that the lock file gets updated.
Another workaround would be to [use Yarn workspace ranges to specify dependencies between package](https://yarnpkg.com/features/workspaces/#workspace-ranges-workspace), so that there's no need to reference specific version numbers.
Unfortunately, Lerna also doesn't support that, either - https://github.com/lerna/lerna/issues/2564.
=> Ensure the yarn.lock file gets updated when publishing

packages/components/src/Button/button.spec.tsx, packages/components/src/Button/button.tsx, packages/components/src/Clickable/Clickable.tsx
@pomfy113 and I were working on focus management for https://app.clubhouse.io/czi-edu/story/153582/screen-reader-ssp-adoption-setup-improvements-nvda-announces-extra-text-blank-when-press-enter-key-on-x-button-besides-the, and realized we can't use React refs (to manage focus) with the react-bootstrap buttons. 
React-bootstrap's buttons have refs, but get you an instance of the React class, not the element.
Decided it was a good opportunity to switch over to the EDS buttons, but realized that they don't take refs. This PR adds ref support to buttons.
- CI
=> Allow buttons to take a ref

packages/components/src/Clickable/Clickable.module.css
[ch156491]
Noticed in the [UI Kit](https://www.figma.com/file/YPTOEVRuas5ytXQEcwm4FK/UI-Kit-Sticker-Sheet-(Core)?node-id=226%3A1100) that the Tertiary button is actually using `neutral-500` instead of `-600`. The darkness difference is noticeable enough that a product team was hesitant to use the new EDS button.
Note: the UI kit uses `-500` for the hover & active states as well, which is inconsistent with the other button color implementations. I'm choosing to keep consistency for now (b/c this update already brings it a lot closer to those designs), and can clarify more w/ Sean
- see Storybook changes
- confirmed color contrast rules in Storybook still all passed (on the "All Variants" story)
=> feat: update neutral button colors

packages/components/generateFlowTypes.sh
some context: https://czi-edu.slack.com/archives/C0241M8DGLV/p1629414226047300
I don't feel good that we currently can't make any updates because of flow T_T would prefer enabling that now, then cutting a release with flow turned on only once I'm sure it works
double-check no `@flow` annotation in the built files
=> fix: turn off flow types for now

packages/components/src/Clickable/Clickable.module.css
Because it's kind of obvious that these variables are for buttons. Or links or whatever the `Clickable` component is making.
Verify there are no changes in percy, snapshots, or in the `Button` stories in storybook.
=> chore(button): remove 'button' prefix from css variables

packages/components/src/Button/button.tsx, packages/components/src/Link/Link.tsx
Clubhouse ticket: https://app.clubhouse.io/czi-edu/story/150604/polish-eds-link-component
Our `Button` and `Link` components currently have an `as` prop that lets users pass in a component to be styled like a button or link. These wrap the `Clickable` component, which does the same thing and is available in `traject`, so we don't actually need `Button` and `Link` components to have an `as` prop at all. I think that it may also be clearer when to which components if the `Button` always returns a `button`, `Link` always returns an `a`, and `Clickable` is the only one that can return anything.
This PR updates the `Button` and `Link` components to no longer accept an `as` prop. Thoughts?
Automated tests should be sufficient for this change.
=> feat(link + button): remove 'as' prop

packages/components/src/Banner/Banner.stories.tsx, packages/components/src/Banner/Banner.tsx, packages/components/src/Banner/__snapshots__/Banner.spec.tsx.snap
Clubhouse ticket: https://app.clubhouse.io/czi-edu/story/157238/update-banner-api
The `Banner` component is pretty complex, and we're playing around with the API to hopefully be easier to reason about. We're concerned that it may be confusing to pass in the `action` as a prop while the heading and body are the `children`.
We want the `action` to be a prop to control its position (left side when the banner is laid out horizontally; centered when in mobile or card format) and the gab between it and the text. Right now, we're just assuming any `children` passed in is intended to be the text (heading and body) that appears above the `action`.
This PR removes the `children` prop and replaces it with one or more props for the text to be passed in. …
=> chore(banner): update api to use title and message instead of children

packages/components/package.json, yarn.lock
Upgrade axe-storybook-testing from 3.0.2 to 4.0.0
- CI
=> Upgrade axe-storybook-testing from 3.0.2 to 4.0.0

packages/components/package.json, yarn.lock
Upgrade axe-storybook-testing from 4.0.0 to 4.0.1
- CI
=> Upgrade axe-storybook-testing from 4.0.0 to 4.0.1

packages/components/src/Banner/Banner.tsx, packages/components/src/Banner/index.ts, packages/components/src/index.ts
When updating the `eds/components` package in `traject`, I ran into 2 issues (one big; one small):
- we can't import the `Link` component because it's not being exported from `index.ts`
- we can't reuse the `Banner` props in `NuxMegaphone` because it's not being exported at all
Relevant PR: https://github.com/FB-PLP/traject/pull/8370
Verify `npx lerna run build:types` completes with no errors or warnings.
=> chore(link, banner): export Banner props and Link from index

packages/components/src/ClickableStyle/ClickableStyle.module.css
I noticed that the horizontal padding for buttons in figma is 14px (not counting the border), but they have 20px in the code. I asked Sean about it, and he said he actually prefers 16px. So he's going to make the padding 2px higher in figma and I'm making it 4px lower in the code.
`yarn start`,
navigate to `http://localhost:6008/?path=/docs/button--all-variants`,
and verify the small and medium buttons have 1 rem horizontal padding.
=> chore(clickable-style): reduce horizontal padding from 20px to 16px

packages/components/src/Button/__snapshots__/button.spec.tsx.snap, packages/components/src/Button/button.stories.tsx, packages/components/src/ClickableStyle/ClickableStyle.module.css, packages/components/src/ClickableStyle/ClickableStyle.tsx, packages/components/src/Link/Link.stories.tsx, packages/components/src/Link/__snapshots__/Link.spec.tsx.snap
Shortcut ticket: https://app.shortcut.com/czi-edu/story/160030/icon-button
Design: https://www.figma.com/file/P9VPyI821gLq832tuU2WeY/UI-Kit-Master-Core?node-id=3072%3A11792
There is a style of button in the UI kit referred to as `TextButton`. This is floating text that has the same padding as the flat and outline buttons but doesn't have a background color in its default state. There was a bit of discussion around what this button is and how are we distinguishing that it's interactive in a way besides color since it doesn't have an underline.
I talked it out with Sean and I think I understand this variant now – it is only intended to be used with an icon. (I still have reservations about this from an accessibility point of view because there are also times when non-interactive text is …
=> feat(clickable-style): add text variant

packages/components/src/Button/button.stories.tsx, packages/components/src/ClickableStyle/ClickableStyle.module.css, packages/components/src/ClickableStyle/ClickableStyle.tsx, packages/components/src/Link/Link.stories.tsx
Shortcut ticket: 
Figma: https://www.figma.com/file/P9VPyI821gLq832tuU2WeY/UI-Kit-Master-Core?node-id=3072%3A11792
Adding an extra small button size for really narrow spaces like table cells.
`yarn start`,
navigate to `http://localhost:6006/?path=/story/button--all-variants` and `http://localhost:6006/?path=/story/link--all-variants`,
verify there's now an extra small version of all the buttons/links (even though it doesn't affect the "link" style),
and verify the other buttons and links are unchanged.
=> feat(clickable-style, button, link): add extraSmall size

packages/components/src/Banner/__snapshots__/Banner.spec.tsx.snap, packages/components/src/Button/__snapshots__/button.spec.tsx.snap, packages/components/src/Button/button.stories.tsx, packages/components/src/Button/button.tsx, packages/components/src/ClickableStyle/ClickableStyle.module.css, packages/components/src/ClickableStyle/ClickableStyle.stories.tsx, packages/components/src/ClickableStyle/ClickableStyle.tsx, packages/components/src/ClickableStyle/__snapshots__/ClickableStyle.spec.tsx.snap, packages/components/src/Link/Link.stories.tsx, packages/components/src/Link/Link.tsx, packages/components/src/Link/__snapshots__/Link.spec.tsx.snap
The "large" button size is not currently being used (in the product or in the UI sticker sheet), and Sean says we don't need it and can kick it to the curb. This PR removes that but also bumps the remaining sizes up by one to remove the "extraSmall" name, which we don't like just on a naming basis (the styles are fine and will now be known as "small").
Because "medium" was previously the default button size, the default is now "large". Because of that, I also updated the stories to use "large" as the default.
Most of this PR is actually snapshot changes because the class names changed from "medium" to "large".
Check out the following stories:
- http://localhost:6006/?path=/docs/clickablestyle--clickable-style-as-an-a-tag
- http://localhost:6006/?path=/docs/button--primary
- …
=> feat(clickable-style): remove large, bump remaining sizes up one level

packages/components/src/SvgIcon/SvgIcon.module.css
Related to https://github.com/FB-PLP/traject/pull/8898 -- the old EDSCandidates icon set `flex-none`, while the new EDS icon only set `display: inline`. In trying to unravel why, I noticed that:
- when @dierat [originally copied over the icon](https://github.com/chanzuckerberg/edu-design-system/pull/509/files#diff-1919752300777d670a3ccc3f8c58b08e3ff2034c1125a0aade1026a75ea1d851R2), it had styling `@apply flex-none inline-block`
- when we [split off the icon changes into a separate PR](https://github.com/chanzuckerberg/edu-design-system/pull/516/commits/a9fd0b71076a34af1dcc9d5e3513ade35013809c#diff-aa5b180f76dda970207508580e582f9ca15b84f00f3a72b2ee5d2927e65dffb6R2), the styling became `@apply inline` (and then was landed)
I think we always wanted `@apply flex-none inline-block` and …
=> fix(svgicon): set inline-block

.github/workflows/test.yml, packages/components/package.json, yarn.lock
Removes percy since chromatic does visual regression testing now
- Chromatic testing works
- CI
=> Remove Percy from EDS

packages/components/src/Icons/ExpandLessRounded.tsx, packages/components/src/Icons/index.ts
Just what it says! Notebooks needs this one.
Verify the icon appears in the `All Icons` story.
=> chore(svg-icon): add ExpandLessRounded icon

.eslintrc
[ch172777]
forced an error:
confirmed importing from something like `docs-editor/` doesn't trigger the error
=> build: restrict importing from .storybook, docs into src

packages/components/src/Banner/__snapshots__/Banner.spec.tsx.snap, packages/components/src/Button/__snapshots__/button.spec.tsx.snap, packages/components/src/ClickableStyle/ClickableStyle.tsx, packages/components/src/Link/__snapshots__/Link.spec.tsx.snap
We have an empty space in the `ClickableStyle`, `Button`, and `Link` children. The comment says it's there to ensure the height of the button. We added `height` to the button styles a while back, to make sure icons don't expand the buttons and make them too tall, so we don't really need this anymore.
Strangely, the buttons are slightly *taller* after this change. According to the styles, the height is the same, but it's rendering very slightly taller. It's pretty subtle on an individual button.
Verify there are no significant changes in the chromatic snapshots.
=> chore(clickable-style): remove empty space in children

packages/components/src/Banner/Banner.tsx, packages/components/src/Banner/__snapshots__/Banner.spec.tsx.snap, packages/components/src/Toast/Toast.tsx, packages/components/src/common/CloseButton/CloseButton.module.css, packages/components/src/common/CloseButton/CloseButton.stories.module.css, packages/components/src/common/CloseButton/CloseButton.stories.tsx, packages/components/src/common/CloseButton/CloseButton.tsx, packages/components/src/common/Notifications/Notification.module.css
The `CloseButton` component was only really intended to be used in the `Banner` and `Toast` components, but I'm using the `CloseButton` in the `Modal` component in `traject`, and I noticed a few things I wanted to change:
- having to add your own hover color is annoying and not intuitive
- you can't add a custom aria label
- you can't pass other attributes like `data-testid` down to the button
- there are no default `size` and `color` values (I like the be able to plug the component in, verify it works with the default values, and then customize it to meet my needs)
This PR attempts to address these issues.
I'm also wondering if we should pull the `CloseButton` out of `common` or not.
Verify the close button hover state is unchanged in the `Banner` and `Toast` components in storybook,
and …
=> chore(close-button): add hover color, aria-label prop, and default prop vals

packages/components/src/common/CloseButton/CloseButton.tsx
I changed up the `CloseButton` but I didn't update the docstring, which is now incorrect. This PR just updates the docstring based on the changes made in https://github.com/chanzuckerberg/edu-design-system/pull/721
n/a
=> docs(close-button): clean up component docstring

packages/components/src/Icons/InfoRounded.tsx, packages/components/src/Icons/index.ts
Needed for some tooltip designs.
it's a bit different from the stickersheet design but I see that the "master" component was deleted so need to check with Sean if that's still the intended look 🤔  easy to change if so
=> feat(icons): add InfoRounded

packages/components/src/Banner/Banner.tsx
If you look at the `Banner` code snippets in storybook, it shows the subcomponents being called `BannerTitle` and `BannerMessage`. This is confusing because when you use them in your code, they're `Banner.Title` and `Banner.Message`. The component names in that snippet are coming from the `displayName` of the subcomponent, which are defined in `Banner` when they're first defined. We're taking these components and setting them to `Banner.Title` and `Banner.Message`, but that's not their names under the hood.
This PR adds display names for the `Banner` and its subcomponents so their names appear correctly in the code snippets on the docs page.
Alternatively, we could just update the docstring on the `Banner` with some example code that does use the right component names. …
=> docs(banner): fix display names for subcomponents

packages/components/src/Banner/Banner.tsx
This PR updates the `Banner` docstring to have a code example. It was originally for clarifying something confusing about the code snippets under the stories, but that was fixed in Alternative to https://github.com/chanzuckerberg/edu-design-system/pull/734
Alternative to https://github.com/chanzuckerberg/edu-design-system/pull/734
The code snippets for the `Banner` stories in storybook are a little misleading because they show the subcomponents as being called `BannerTitle` and `BannerMessage`, but when you use them in the code, you refer to them as `Banner.Title` and `Banner.Message`.
This PR updates the `Banner` docstring to have a code example that uses the right names and also points out that the code snippets are wrong.
Check out the `Banner` in storybook and verify the new docstring …
=> docs(banner): add example to docstring

packages/components/src/Icons/InsertDriveFileRounded.tsx, packages/components/src/Icons/index.ts
was working on https://app.asana.com/0/1193259244765873/1193259244765983 & noticed this icon is used in a couple of places in LP
=> feat(icon): add InsertDriveFile

packages/components/src/Link/Link.spec.tsx, packages/components/src/Link/Link.stories.tsx, packages/components/src/Link/__snapshots__/Link.spec.tsx.snap, packages/components/src/storyUtils/clickableStyleUtils.tsx
We have some `Link` stories that have an `href` that's just an empty string. When you click on those links, you're navigated to a different page that just has that story, which makes it kind of annoying to test the click interaction on these things.
This PR upgrades the `href` value to an actual example URL and also adds an `onClick` handler to stop the page navigation.
Please note that this only affects the top 3 stories (default, in body text, in a heading) and the big grids at the bottom (all variants) because I'm only updating the stories that already had an `href`. The other stories would be a little more work and repetition, and I don't think we need this for every single story. A couple is enough.
Navigate to `http://localhost:6008/?path=/docs/link--default`,
test clicking all the …
=> chore(link): add fake href, stop navigating away in stories

packages/components/src/ClickableStyle/ClickableStyle.module.css
Ticket: https://app.shortcut.com/czi-edu/story/176514/revisit-hover-background-color-on-plain-variant
There's been some back and forth about the "plain" `Button` variant's hover style. The button has a very light background color, which looks great on white, but it kind of disappears into the light gray background that is commonly used in LP.
I talked to Sean and we decided to add a 2px border on the hover style (so it kind of turns into an "outline" variant button but it still has the light background color). I think the hope is that one day we may no longer have these gray backgrounds, but I don't think that day is going to come anytime soon. If it does, we can consider dropping the outline.
Navigate to `http://localhost:6008/?path=/story/button--all-variants`,
verify the hover and …
=> chore(clickable-style): give plain button hover style a border

packages/components/.storybook/preview.tsx, packages/components/src/Button/button.stories.tsx, packages/components/src/Link/Link.stories.tsx, packages/components/src/storyUtils/clickableStyleUtils.tsx
The `Button` and `Link` components both have a story that shows all of the variants of the component in one size (large) on a dark background. The reason we added these stories was to make the opacity of the buttons clear – specifically it's obvious when looking at these buttons that the outline variant has a transparent background (which there was some confusion around before). I used the standard "dark" background that comes with storybook because that accomplished the goal.
What I would like to do with this PR is change those stories to use the same gray that LP uses. This way, the stories will still communicate the opacity of the buttons but it will also help us see how well the buttons are working on this gray, which is very common in LP. I think the hope is that one day those gray …
=> chore(button, link): make dark background stories gray instead

packages/components/src/common/CloseButton/CloseButton.spec.tsx, packages/components/src/common/CloseButton/CloseButton.tsx, packages/components/src/common/CloseButton/__snapshots__/CloseButton.spec.tsx.snap
Part of https://app.shortcut.com/czi-edu/story/176519/modal-follow-ups
While working on the `Modal` component in LP, I've been thinking about how multi-step modals will need to manually set focus on the first interactive element in the modal when the user moves to a different step. We set focus using refs, but the `CloseButton` doesn't actually support forwarding refs atm, so this PR adds that functionality.
I wanted to add a test to verify that the ref was properly being forwarded, and I realized I never added a spec file for this component (???), so I added that while I was in here.
Next up: I'm going to move the `CloseButton` out of `/common` since we now expect it will be used in LP outside of EDS components.
Verify automated tests pass.
=> chore(close-button): add forwardRef, test file

.github/workflows/test.yml
Remove build matrix for Node versions.
Testing this repo on different versions of Node isn't meaningful. The Node version isn't the thing that will make these tests fail or pass. More relevant would be something like operating system.
This PR simplifies things a bit, and has the side benefit of meaning things like #767 don't have to update the branch protection rules to get required checks working right.
If/when approved, I'll update the branch protection rules and the 14.x checks will no longer show up as required.
- CI
=> Remove build matrix for Node versions

packages/components/src/Heading/Heading.tsx, packages/components/src/Text/Text.tsx
[sc-66248]
- extends Heading props to have html heading attributes
- extends Text props to have global html attributes
- no typescript complaints when html attributes exist
Previously:
Now no errors:
=> chore: extend props for Text and Heading

packages/components/README.md
Fixing a typo?
- Ran `yarn generateFlowTypes DropdownButton`; verified that worked.
- Tried `yarn generateFlowtypes DropdownButton`; verified that did not work.
- Previewed the read me file; verified it said `yarn generateFlowTypes <Component>`.
=> docs(read-me): change yarn generateFlowtypes to yarn generateFlowTypes

package.json
We're now over the 70kb size limit from the size-limit-action. This PR doubles it to 140kb, since it's expected that the package will keep getting bigger.
I'm not sure we should even use this action. But maybe it's nice to get the report on how much size increases per PR.
- CI
=> Double size limit to 140kb

packages/components/src/FormGroup/FormGroup.tsx
The `FormGroup` component has 2 subcomponents: `Form.Title` and `Form.Items`. But in the `code` feature of the docs tab in storybook, these components are shown as just `Title` and `Items`, which makes it little confusing for devs trying to import and use the component. The solution is to add display names for all three (`FormGroup`, `FormGroup.Title`, and `FormGroup.Items`).
Similar PR for the `Banner` component: https://github.com/chanzuckerberg/edu-design-system/pull/734
Manually tested in storybook.
=> chore(form-group): add display names to components

packages/components/package.json, packages/components/src/ButtonGroup/ButtonGroup.tsx
After making a very small change in a component in https://github.com/chanzuckerberg/edu-design-system/pull/832, I hit a chromatic build issue involving our chromatic version and Turbosnap. To unblock development, we can downgrade chromatic or remove the `--only-changed` flag from the chromatic script. We are opting to do the latter.
Make a change in some component (like adding a fragment or wrapping span or something),
then run `yarn workspace @chanzuckerberg/eds-components chromatic --project-token=${{ secrets.CHROMATIC_PROJECT_TOKEN }} --output-dir storybook-static --exit-zero-on-changes --skip 'dependabot/**'` (replacing `${{ secrets.CHROMATIC_PROJECT_TOKEN }}` with the actual token, which can be found in chromatic),
and verify you don't get an error.
=> chore: remove --only-changed from chromatic github action

packages/components/src/ButtonGroup/ButtonGroup.tsx, packages/components/src/DropdownButton/DropdownButton.tsx, packages/components/src/DropdownButton/__snapshots__/DropdownButton.spec.ts.snap
Part of https://app.shortcut.com/czi-edu/story/169970/dropdown-api-improvements
Wrapping the `DropdownButton` children in a `<span>` in case label contains more than just text
Verify the `<span>` is showing up in the snapshot file for the `DropdownButton` component.
=> chore(dropdown-button): wrap children in span

.github/workflows/test.yml
Exit Chromatic's build step once the Storybook build is uploaded.
Previously this would wait until the build was uploaded AND Chromatic finished processing the build. But there's no reason for the job to wait for all the processing, since the UI Tests step won't be green until that processing is complete (and any diffs are approved).
Making this change should make the build a little more resilient. Long-running Chromatic processing times can still be an issue, but at least they won't cause the upload job to time out.
=> Exit Chromatic once the build is uploaded

packages/components/.storybook/main.js
https://github.com/chanzuckerberg/edu-design-system/pull/813/files#r793032073 reminded me of this -- we should show the `docs/` pages first so they aren't buried under the components
confirmed Tokens & Typography story pages are now shown first:
=> docs: list docs/ stories first

.stylelintrc, package.json, packages/components/src/Tooltip/Tooltip.module.css, packages/components/src/styles/global.css, yarn.lock
v13 is no longer supported by the VSCode extension. a rare case where `traject` has more updated dependencies than EDS 😁 
I also noticed that `yarn lint:styles` was throwing errors (is `lint-staged` not working 🤔 ), so fixed those
- `yarn lint:styles` shows no errors
- tested that nesting errors are still flaggged
=> upgrade stylelint to v14

.github/dependabot.yml
https://app.shortcut.com/czi-edu/story/183913/figure-out-what-to-do-with-dependabot
All dependabot version update PRs fail the build ([example](https://github.com/chanzuckerberg/edu-design-system/runs/5314913517?check_suite_focus=true)) because [dependabot does not support yarn v2](https://github.com/dependabot/dependabot-core/issues/2030)
this turns off the PRs (which we did, and then un-did awhile ago)
not sure how to test, I followed https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/enabling-and-disabling-dependabot-version-updates#disabling-dependabot-version-updates
=> chore: disable dependabot version updates

packages/components/src/Dropdown/Dropdown.tsx
I missed this change to the `Dropdown` component when I copied the code into this codebase.
Verify the import example appears in storybook for the `Dropdown` component in the same way that it appears for other ones.
=> docs(dropdown): add import example to docstring

packages/components/src/Dropdown/Dropdown.spec.tsx, packages/components/src/Dropdown/Dropdown.stories.tsx, packages/components/src/Dropdown/Dropdown.tsx
While working on migrating the existing `Dropdown` usage in `traject` to use the new eds component, I realized that the types for the `options` prop is inconsistent with the actual usage. In the stories, we were using `id`, but they're using `key` in the app. Changing the component to be consistent with actual usage will make it easier to use this prop.
I published an alpha build (0.8.1-alpha.1), updated `traject` locally to use that build, updated an example dropdown (`PDSearchBar`), and verified the conversion from using `<Dropdown.Options>` to `options` was smooth.
=> chore(dropdown): use key instead of id in options

.eslintrc, plop-templates/Component/Component.spec.tsx.hbs, plop-templates/Component/Component.test.tsx.hbs, plopfile.js
Merging into `next` branch. Drops support for `.spec.ts` extension in favor of `.test.ts` going forward
- test file still linted correctly
- `plop` creates test file correctly
=> test: use .test as extension instead of .spec

.storybook/data/tokens.json, .stylelintrc, docs/CODE_GUIDELINES.md, package.json, src/components/Button/Button.tsx, src/components/Counter/Counter.stories.tsx, src/components/Tooltip/Tooltip.module.css, src/components/Tooltip/Tooltip.stories.module.css, src/components/Tooltip/Tooltip.stories.tsx, src/components/Tooltip/Tooltip.test.tsx, src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap, src/components/Tooltip/index.ts, src/design-tokens/tier-1-definitions/shadows.json, yarn.lock
[sc-187512]
- moves Tooltip from v0.8.1 to next
- remove TW use
- use CSS custom properties
- convert styles to BEM
- add storybook testing libraries
- tests pass
- manual testing
https://user-images.githubusercontent.com/86632227/157141485-c1fa6e7d-c395-4ddc-95cb-ada53831ea5f.mov
=> Move tooltip to next 

.storybook/pages/ProjectOverview/ProjectOverview.stories.tsx, .storybook/pages/ProjectOverview/ProjectOverview.tsx, src/components/ListDetail/ListDetail.module.css, src/components/ListDetail/ListDetail.stories.tsx, src/components/ListDetail/ListDetail.tsx, src/components/ListDetailPanel/ListDetailPanel.tsx
Shortcut: https://app.shortcut.com/czi-edu/story/189947/list-detail-component-sequence-variant
This PR adds a 'sequence' variant to the List Detail Component; sequence variant adds icons for 'success', 'warning' and 'error' and a vertical line to the list detail component's unordered list;
NOTES:
- The colors need to be replaced
- The line between list elements has vert space above and below it, but there is irregularity when the text in adjacent list elements are varying heights (see screenshot below)
- I fought the linter and the linter won. I'm open to suggestions on how to refactor those CSS selectors (src/components/ListDetail/ListDetail.module.css:107, 161)
=> chore(list detail): adding variants

packages/components/src/Dropdown/Dropdown.module.css, packages/components/src/Dropdown/Dropdown.stories.tsx, packages/components/src/Dropdown/Dropdown.tsx, packages/components/src/Dropdown/__snapshots__/Dropdown.spec.tsx.snap
Addresses: https://app.shortcut.com/czi-edu/story/189746/notebook-c3-compact-mode-variant-for-eds-drop-down
This PR adds compact variant to EDS drop-down:
- Dropdown button is only as large as content requires
- Dropdown can have differing button width and options menu width
- Dropdown menu has wider width to accomodate
- Dropdown menu can be right aligned to the button
Alternative approaches considered:
1. Using CSS var to defined and pass width
```
.compact > .options {
width: var(--eds-dropdown-options-width);
}
```
2. Passing ref back to caller to style options menu width
See storybook for Dropdown component:
1. Compact
2. Compact With Options Right Aligned
3. Separate Button And Menu Width
4. Compact Using Children Prop And No Visible Label
=> feat(dropdown): add compact button as option

docs/CODE_GUIDELINES.md
This PR proposes removing the section in CODE_GUIDELINES that was recently added re: the typing of state. Rather than refactor components that aren't broken, I amended the `useState()` section to suggest the pattern of initializing state with a prop when explicit typing is necessary (and allowing TypeScript's type inference to handle the rest of the cases.)
Confirm that the suggested patterns conform with best practices.
=> docs(code guidelines): revert change re: state

packages/components/src/Toast/Toast.tsx
The `CloseButton` is kind of a snowflake because it has a hover effect for the icon button that we don't use anywhere else. I talked to Sean and we're good to remove it to make the close buttons consistent with our other icon buttons. But before we can delete the component, we need to update the locations using it.
This PR updates the `Toast` component to use a plain `Button` instead of the customized `CloseButton`. The placement of the icon is a little different than before, but we paired on it and decided this is fine for now.
Tested in storybook.
https://user-images.githubusercontent.com/7761701/161343986-affc8360-0251-4fb7-8b24-f15baea6e6b1.mp4
=> chore(toast): use plain button instead of CloseButton

.storybook/pages/CoursesYear/CoursesYear.tsx, .storybook/pages/ProjectOverview/ProjectOverview.tsx, .storybook/recipes/PageShell/PageShell.tsx, docs/CODE_GUIDELINES.md, docs/COMPONENTS.md, docs/ICONS.md, src/components/Banner/Banner.stories.tsx, src/components/Button/Button.module.css, src/components/Button/Button.stories.tsx, src/components/Button/Button.test.tsx, src/components/Button/Button.tsx, src/components/ButtonGroup/ButtonGroup.stories.tsx, src/components/Counter/Counter.stories.tsx, src/components/Drawer/DrawerExample.tsx, src/components/InlineForm/InlineForm.tsx, src/components/Modal/ModalExample.tsx, src/components/Popover/PopoverExample.tsx, src/components/StackedBlock/StackedBlock.stories.tsx, src/components/TableHeaderCell/TableHeaderCell.tsx, src/components/TextField/TextField.stories.tsx, src/components/TextareaField/TextareaField.tsx, src/components/Tooltip/Tooltip.stories.tsx, src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
Following up on our EDS eng sync conversation on 3/29, this PR renames the `text` prop in the `Button` component to `children` to be consistent with what the users of this design system expect.
Spot check storybook, especially the docs changes since automated tests won't catch typos in there.
=> chore(button): rename 'text' prop to 'children'

src/components/Popover/PopoverExample.tsx
I'm seeing some type errors because of some unused imports in the `PopoverExample` component, and I also noticed an unused variable from a prop deconstruction, so I'm removing them in this PR so get the tests passing in a different PR.
`yarn types` returns no errors.
=> chore(popover-example): remove unused variables

packages/components/src/Banner/Banner.tsx, packages/components/src/Banner/__snapshots__/Banner.spec.tsx.snap
The `CloseButton` is kind of a snowflake because it has a hover effect for the icon button that we don't use anywhere else. I talked to Sean and we're good to remove it to make the close buttons consistent with our other icon buttons. But before we can delete the component, we need to update the locations using it.
This PR updates the `Banner` component to use a plain `Button` instead of the customized `CloseButton`. The placement of the icon is a little different than before, but we paired on it and decided this is fine for now.
Tested in storybook.
https://user-images.githubusercontent.com/7761701/161342193-d8d57a08-abde-41ff-9aca-2ff9186cba39.mp4
=> chore(banner): use plain button instead of CloseButton

src/components/Tooltip/Tooltip.stories.tsx, src/components/Tooltip/Tooltip.tsx
[sc-189391]
- deprecates dark tooltip via:
- tsdoc `@deprecated` flag (doesn't do anything with VSCode now, but hopefully will be better supported in future TS releases https://github.com/microsoft/tsdoc/issues/131)
- `console.warn` in non prod
- badge in storybook
- manual testing
- storybook has badge
- console warns
=> chore: deprecate dark tooltip

src/components/MediaBlock/MediaBlock.stories.tsx, src/components/StackedBlock/StackedBlock.stories.tsx
The `MediaBlock` and `StackedBlock` stories have been flaky in chromatic because they're linking to an image that doesn't exist (`https://placehold.it/600x400` takes forever and eventually just loads an error page), so sometimes we get no image and sometimes we get a broken image icon. We shouldn't link to external images anyway because it can cause flakiness, but in this case it's really obvious why this particular image is flaky, so I'm just replacing it with an actual image url for now.
Check out the `MediaBlock` and `StackedBlock` stories in storybook and verify they are now 1000% cuter.
=> chore: replace flaky image url with a cuter image url

.storybook/components/IconGrid/IconGrid.js, src/components/AccordionPanel/AccordionPanel.tsx, src/components/Banner/Banner.tsx, src/components/BreadcrumbsItem/BreadcrumbsItem.tsx, src/components/Button/Button.tsx, src/components/FieldNote/FieldNote.tsx, src/components/FileUploadField/FileUploadField.tsx, src/components/Icon/Icon.module.css, src/components/Icon/Icon.stories.tsx, src/components/Icon/Icon.tsx, src/components/LinkListItem/LinkListItem.tsx, src/components/ListDetail/ListDetail.tsx, src/components/LoadingIndicator/LoadingIndicator.tsx, src/components/PrimaryNavItem/PrimaryNavItem.tsx, src/components/SelectField/SelectField.tsx, src/components/TagsItem/TagsItem.tsx, src/components/TextField/TextField.tsx, src/components/TextareaField/TextareaField.tsx, src/components/Toast/Toast.tsx, src/components/UtilityNavItem/UtilityNavItem.tsx, src/design-tokens/css/base/media.css, src/util/allIcons.ts
[ch187509]
- Adds props from `SvgIcon` to `Icon` component
- Updates existing callsites
- Adds extra stories from EDS
**To handle later** (aka I tried but it took too much time & wanted to timebox it):
- Making `ALL_ICONS` a union type for the Icon `name` prop to read from
- Adding snapshot tests (there's an error rn because the stories read from `ALL_ICONS`, and jest doesn't like `require.context`)
https://app.shortcut.com/czi-edu/story/191277/make-icon-name-prop-a-union-of-available-icon-types
- No type errors
- See visual changes in Chromatic
- Make sure Icon Docs page controls work
=> Add `SvgIcon` props to `Icon`

.storybook/pages/ProjectOverview/ProjectOverview.tsx, .storybook/recipes/GlobalHeader/GlobalHeader.tsx, docs/COMPONENTS.md, docs/ICONS.md, src/components/Banner/Banner.tsx, src/components/Button/Button.module.css, src/components/Button/Button.stories.tsx, src/components/Button/Button.tsx, src/components/Counter/Counter.stories.tsx, src/components/Counter/Counter.tsx, src/components/DrawerHeader/DrawerHeader.tsx, src/components/FileUploadField/FileUploadField.tsx, src/components/ModalHeader/ModalHeader.tsx, src/components/ShowHide/ShowHide.stories.tsx, src/components/TableHeaderCell/TableHeaderCell.tsx, src/components/Toast/Toast.tsx, src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
On the CZI side, we've been discussing retaining the existing `Button` API where devs pass in an icon via `children` instead of the `iconName` and `iconPosition` props. This PR explores what that would look like.
Our reasoning is:
- we can get the spacing between icons and text with `gap`; we don't need to manually add margin to icons before and after the text
- this API feels much more intuitive and natural to us, and we feel confident the devs using the components would agree
- the other API felt especially weird to us when the button only contained an icon; you still had to pass in an `iconPosition` and it would add the margin on to one side, making it lop-sided; `gap` only adds the spacing when there's more than one child
The only downsides imo are:
- if the `children` text is broken …
=> feat(button): remove icon props

plop-templates/Page/Page.stories.tsx.hbs, plop-templates/Page/Page.tsx.hbs, plop-templates/Page/index.ts.hbs, plop-templates/Recipe/Recipe.tsx.hbs, plop-templates/Recipe/index.ts.hbs, plopfile.js
This PR contains changes to the plop templates that were missed in the initial pass. Specifically:
1. Add `index.ts` to the Page and Recipe templates to match established directory structure
2. Remove React.FC typing in Page and Recipe templates to match Component template
Run `yarn run plop`, `yarn run plop:page` and `yarn run plop:recipe` and confirm that all files are generated correctly with no errors.
=> chore(templates): update plop templates

.storybook/pages/ProjectOverview/ProjectOverview.tsx, .storybook/recipes/GlobalHeader/GlobalHeader.tsx, src/components/Banner/Banner.tsx, src/components/Button/Button.module.css, src/components/Button/Button.stories.tsx, src/components/Button/Button.tsx, src/components/Counter/Counter.module.css, src/components/Counter/Counter.stories.tsx, src/components/Counter/Counter.tsx, src/components/DrawerHeader/DrawerHeader.tsx, src/components/FileUploadField/FileUploadField.tsx, src/components/ModalHeader/ModalHeader.tsx, src/components/Popover/PopoverExample.tsx, src/components/TableHeaderCell/TableHeaderCell.tsx, src/components/TextField/TextField.stories.tsx, src/components/TextareaField/TextareaField.tsx, src/components/Toast/Toast.tsx
What this PR does:
- update the `Button` variants to match the new button token structure
What this PR does *not* do:
- update the styles of the variants, including newly added ones, to use the new tokens
- add stories for the new variants
I wanted to put this change out first to make sure we're aligned on this API change before digging into the actual styles.
- `yarn types` returns no errors
- no changes to existing button usage in storybook
=> feat(button): update variants to match new tokens

.storybook/recipes/GlobalHeader/GlobalHeader.tsx, docs/CODE_GUIDELINES.md, src/components/Button/Button.module.css, src/components/Button/Button.stories.tsx, src/components/Button/Button.tsx
I talked to Sean about the `inverted` `Button` prop, and we decided to remove it. The reasoning is that:
- LP has no dark backgrounds (except the sidebar/header, which is unique and will need unique styling anyway)
- we have no plans to implement dark mode (maybe one day but it's not in the foreseeable future)
The inverted button tokens were also removed, so there's nothing for us to use in the styles anyway.
Verify there are no type errors and there is no change to the icons in the`GlobalHeader` recipe.
=> feat(button): removed inverted prop

.storybook/data/tokens.json, src/components/Button/Button.module.css, src/components/Button/Button.stories.tsx, src/components/Button/Button.tsx, src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap, src/components/UtilityNav/UtilityNav.module.css, src/design-tokens/mixins.css, src/design-tokens/tier-3-component/buttons.json, src/tokens-dist/_scss_variables.scss, src/tokens-dist/variables-nested.json, src/tokens-dist/variables.css
I previously updated the variants in the `Button` component to match the new color tokens. This PR updates the `Button` styles to use those tokens. I also updated the stories to match the UI Kit, so it's now very close to the figma representation of the component. There's a little more work to do, mostly around sizing (icon size in the button, link text size, space between link text and icon), so I left a couple of todo comments.
Verify the button stories and styles now mostly match the UI Kit in figma, and make sure the hover/focus states look right (especially be sure to verify the disabled buttons don't change color or anything on hover/click).
=> feat(button): use new button tokens, update storybook

jest.config.js, jest/jest.setup.ts, jest/mocks/fileMock.js, src/components/Icon/Icon.test.tsx, src/components/Icon/__snapshots__/Icon.test.tsx.snap, src/components/Tag/Tag.stories.tsx, src/components/Tag/__snapshots__/Tag.test.ts.snap, src/components/Toast/Toast.stories.tsx, src/components/Toast/Toast.test.tsx, src/components/Toast/__snapshots__/Toast.test.tsx.snap
[ch191630]
Turns out the error was mocking `svg` files & some specific modules correctly. This adds back `Icon`, `Toast`, and `Tag` snapshot tests 🎉 
- `yarn test` passes
=> Enable icon snapshot tests

src/components/Checkbox/Checkbox.stories.module.css, src/components/Checkbox/Checkbox.stories.tsx, src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
- This was accidentally removed from original merged move checkbox pr
- Reintroduces grid to show that label wraps while `CheckboxInput` centers with first line of label
- `CheckboxInput` centers with first line of label in Storybook/Chromatic
=> chore: add grid styling to checkbox long labels story

src/components/Tooltip/Tooltip.stories.tsx
There's a flaky tooltip snapshot that keeps showing up in the chromatic changes. @jinlee93 added a delay to this test, which we had hoped would fix this, but I'm still seeing it sometimes. We could increase the delay, but now I'm also wondering what we even gain from this snapshot because it doesn't even show the tooltip. So this PR disables the chromatic snapshot for this story, but I'm also open to increasing the delay if people think that would be better.
https://www.chromatic.com/test?appId=61313967cde49b003ae2a860&id=6258e75b6814fe003a4828d2
Verify this snapshot is missing in chromatic.
=> test(tooltip): disable snapshot for long button text

src/design-tokens/mixins.css
This change was originally part of https://github.com/chanzuckerberg/edu-design-system/pull/968, which was closed because we're not going in that direction anymore.
This PR updates the `textLink` mixin to use the default link color tokens (instead of the "strong" ones). This does not affect the `ClickableStyle`, `Button`, or `Link` components; it only affects components that have text links but use the mixin instead of the component. (We may want to go back and use the component instead of the mixin in these places, but for now I think it's fine if they use the mixin.)
In storybook,
verify the "link" variant stories in the `Link` component are unchanged,
and verify the links in http://localhost:9009/?path=/docs/organisms-text-textpassage--default are now gray (and become a slightly darker …
=> feat(link): use default link color tokens in textLink mixin

src/components/Button/Button.stories.tsx, src/components/ClickableStyle/ClickableStyle.stories.tsx, src/components/Link/Link.stories.tsx
I'm having a bit of trouble with the `ClickableStyle`/`Button`/`Link` stories because the props aren't showing up by default. I don't want to get stuck in the weeds on this component anymore than I already have, so this PR just adds `argTypes` to the stories to get the docs working in storybook. (Unfortunately, we don't get the prop comments, which I really like, but, oh well.) I can make a backlog ticket to look into this further if we think it's worth coming back for.
Verify the `ClickableStyle`, `Button`, and `Link` components now have their main configurable props listed on the docs tab in storybook and you can click around in them to change the component styling.
=> docs(clickable-style, button, link): add argTypes to stories

src/components/Banner/Banner.module.css, src/components/Toast/Toast.module.css, src/design-tokens/mixins.css
The `Banner` and `Toast` have overlapping styles, and there are a couple more components in the UI Kit like them. This PR adds mixins to reuse the color-related styles (text, background, and border colors) for the 5 possible variants for messaging components. This will help us keep them in sync so it's easier to maintain and keep them consistent. (This PR does have a slight change to the component styles because it causes the `Toast` to now use the exact same tokens as the `Banner`.)
One thing to note is that the `Toast` only supports 2 of these variants, so it's possible this is overkill and the complexity isn't worth the deduplication in this case. I'm more inclined to add this because it could be reused in other future messaging components.
UI Kit: …
=> chore(banner, toast): use mixins to share variant colors between messaging components

src/components/Banner/Banner.module.css, src/components/Banner/Banner.stories.tsx, src/components/Banner/Banner.tsx, src/components/Heading/Heading.module.css, src/components/Heading/Heading.tsx, src/components/Heading/__snapshots__/Heading.test.tsx.snap, src/components/Text/Text.module.css, src/components/Text/Text.stories.tsx, src/components/Text/Text.tsx, src/components/Text/__snapshots__/Text.test.tsx.snap, src/components/Toast/Toast.module.css, src/components/Toast/Toast.stories.tsx, src/components/Toast/Toast.tsx, src/components/Toast/__snapshots__/Toast.test.tsx.snap, src/design-tokens/mixins.css
I noticed we're sometimes using the word "error" for red variants and sometimes using "alert" (but mostly using "error"). Design confirmed that we should be using "error" everywhere. This PR updates the `Banner`, `Toast`, `Text`, and `Heading` components to use "error".
Verify there are no changes to these components in storybook aside from the story name changes.
=> feat: use 'error' instead of 'alert' for red variants

src/components/Banner/Banner.test.tsx, src/components/Banner/__snapshots__/Banner.test.tsx.snap
I suddenly realized the `Banner` component didn't have a test file, so this PR adds one. Side note – it may be worth it to generate test files for all the components that don't have one already, because it's really easy to forget this when you're starting from a component that already exists.
`yarn test` passes without a hitch and now there are snapshot files for the `Banner`.
=> test(banner): add snapshot and dismiss tests

src/components/FieldsetItems/index.ts, src/components/FieldsetLegend/index.ts
I'm seeing some warnings in storybook about 
> ./src/components/FieldsetItems/index.ts 1:0-79"export 'FieldsetItemsProps' was not found in './FieldsetItems'./src/components/FieldsetLegend/index.ts 1:0-82"export 'FieldsetLegendProps' was not found in './FieldsetLegend'
I think we need to export props on a separate line that specifies the item is a `type` in order to clear these.
Navigate to any page in storybook and verify there are no warnings in the browser console about field set props not being found.
=> chore(fieldset-legend, fieldset-items): export props on separate lines

src/components/Banner/Banner.stories.tsx, src/components/Banner/Banner.tsx, src/components/Banner/__snapshots__/Banner.test.tsx.snap, src/components/Banner/index.ts, src/components/Toast/Toast.tsx
Now that the `Button` component can produce all 5 colors for `secondary`, `icon`, and `link` variants, we can use those in the `Banner` and `Toast` components. The only one used inside the components is the icon button in the close button; the others are just in the `Banner` stories file to give a more accurate demonstration what the `Banner` usage should look like.
Verify in storybook and chromatic that the `Banner` stories are unchanged except now they have close buttons, links, and action buttons that match the rest of the color of the banner.
=> feat(banner, toast): use status prop with close and action buttons

src/components/Button/Button.stories.tsx, src/components/Button/Button.tsx, src/components/Button/__snapshots__/Button.test.tsx.snap, src/components/ButtonGroup/ButtonGroup.stories.tsx, src/components/ButtonGroup/__snapshots__/ButtonGroup.test.ts.snap, src/components/ClickableStyle/ClickableStyle.tsx, src/components/Drawer/DrawerExample.tsx, src/components/Link/Link.stories.tsx, src/components/Link/__snapshots__/Link.test.tsx.snap, src/components/Modal/ModalExample.tsx, src/components/Popover/PopoverExample.tsx, src/components/ShowHide/ShowHide.stories.tsx, src/components/TableHeaderCell/TableHeaderCell.tsx, src/components/Tooltip/Tooltip.stories.tsx
@ifrost1 suggested we make the default variant "secondary" for `Button` etc. The reasoning here is that, ideally, there should really only be one primary button (the Most Important Action based on what the user is doing), which means we should be using more secondary buttons than primary, so making that the default prop value should reduce the number of times devs need to specify the variant and also possibly nudge them to use that variant.
No big chromatic changes (aside from some story name updates and some story buttons that I want to use the default variant regardless of what that is, like full width and loading button stories)
=> feat(clickable-style): make secondary variant default

src/components/Banner/Banner.tsx, src/components/Button/Button.tsx, src/components/ButtonGroup/ButtonGroup.tsx, src/components/Checkbox/Checkbox.tsx, src/components/ClickableStyle/ClickableStyle.tsx, src/components/Fieldset/Fieldset.tsx, src/components/FieldsetItems/FieldsetItems.tsx, src/components/FieldsetLegend/FieldsetLegend.tsx, src/components/Heading/Heading.tsx, src/components/Icon/Icon.tsx, src/components/Link/Link.tsx, src/components/Tag/Tag.tsx, src/components/Toast/Toast.tsx, src/components/Tooltip/Tooltip.tsx
This PR:
- adds import examples to component docstrings that don't have one
- updates existing import examples to use the updated package name (`@chanzuckerberg/eds` instead of `@chanzuckerberg/eds-components`)
- touches up a couple of component docstrings that I found a little hard to parse or still used the original super vague component docstring ("Primary UI component for user interaction")
I only touched the components we've already published because I'm focusing more on the upcoming merge of `next` into `main`, but I would like to update the other components and the plop file at some point. https://app.shortcut.com/czi-edu/story/194027/add-import-example-to-component-docstrings-and-better-starter-docstring-in-plopfile
Check out the components in storybook and verify their …
=> docs: update import examples in component docstrings

jest/jest.setup.ts, package.json, src/components/AccordionPanel/AccordionPanel.tsx, src/components/Banner/__snapshots__/Banner.test.tsx.snap, src/components/Breadcrumbs/Breadcrumbs.tsx, src/components/Button/__snapshots__/Button.test.tsx.snap, src/components/CheckboxField/CheckboxField.tsx, src/components/CheckboxFieldItem/CheckboxFieldItem.tsx, src/components/Counter/Counter.tsx, src/components/Fieldset/__snapshots__/Fieldset.test.ts.snap, src/components/FileUploadField/FileUploadField.tsx, src/components/Icon/Icon.tsx, src/components/Icon/__snapshots__/Icon.test.tsx.snap, src/components/InlineForm/InlineForm.tsx, src/components/Link/__snapshots__/Link.test.tsx.snap, src/components/ListDetail/ListDetail.tsx, src/components/PrimaryNav/PrimaryNav.tsx, src/components/RadioField/RadioField.tsx, src/components/RadioFieldItem/RadioFieldItem.tsx, src/components/Tabs/Tabs.tsx, src/components/TextField/TextField.tsx, src/components/TextareaField/TextareaField.tsx, src/components/Toast/__snapshots__/Toast.test.tsx.snap, src/components/UtilityNav/UtilityNav.tsx, yarn.lock
[ch192055]
Benefits of `react-uid`:
- stable ID generator (seems like nanoid is not), which allows for potential SSR in the future
- size difference is minimal (1kB gzipped vs. 500 bytes for nanoid)
- traject already uses it
- hook syntax is close to [React's native `useId` hook](https://reactjs.org/blog/2022/03/29/react-v18.html#useid) coming in React 18 (will upgrade when traject upgrades)
- sanity check that snapshot IDs still make sense
=> feat: replace nanoid with react-uid

src/components/Tag/Tag.module.css, src/components/Tag/Tag.stories.tsx, src/components/Tag/Tag.tsx, src/components/Tag/__snapshots__/Tag.test.ts.snap
Story: https://app.shortcut.com/czi-edu/story/191591/make-banner-and-tag-variant-names-consistent
The `Tag` component's variant names are out of sync with the other components so it's easier to use.
No changes in chromatic or storybook except for story name changes to match the new variants.
=> feat(tag): make variant names consistent with other components

jest.config.js, package.json, src/components/Tooltip/Tooltip.stories.tsx, src/components/Tooltip/Tooltip.test.tsx, src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap, yarn.lock
[ch194410]
Looking into the newly flaky Tooltip snapshots ... some things I noticed:
- For some reason, the animation duration _looks_ longer on `next` (even though it's the same value as `main`). can't tell if this is me being crazy 😩 
- `@tippyjs/react` versions: `main` is on `^4.2.6` while `next` is on `4.2.5`
- setting `animation: false` doesn't work in stories because it also sets `data-state="hidden"`. we target the latter to set `opacity: 0` to enable the fade animation
So the two things I did in this PR are:
- upgrade `@tippyjs` to match `main`
- set `duration: 0` in the always-visible tooltip stories to ensure flakiness isn't because of the animation
If this still doesn't work, I can look into storybook `preview` styling differences between the two branches && possibly adding a …
=> docs: make Tooltip snapshots not flaky

docs/CODE_GUIDELINES.md, src/components/FileUploadField/FileUploadField.tsx, src/components/ListDetail/ListDetail.stories.tsx, src/components/ListDetail/ListDetail.tsx, src/components/Tabs/Tabs.tsx
[ch194920]
Noticed in a Chromatic diff that the way I was using `useUIDSeed` isn't valid (in particular, doing something like `${object}-string` creates an output ID `[object Object]-string`). This corrects our usage & adds guidelines
- For `ListDetail`, confirmed valid IDs were generated, IDs were different for each item, and `id` and `aria-labelledby` were distinct for each item
- Confirmed aria is hooked up correctly using the Accessibility Tree
=> fix: useUIDSeed usage and guidelines

CHANGELOG.md, package.json, src/components/Text/Text.module.css, src/components/Text/Text.stories.tsx, src/components/Text/Text.tsx, src/components/Text/__snapshots__/Text.spec.tsx.snap
- global styles in LP set margin bottom for `p` overriding the `:where(.text)` margin reset
- published alpha, tests passing in text/heading use with alpha in https://github.com/FB-PLP/traject/pull/10779
- once merged, will be publishing patch build `0.12.1` off `jlee/v0.12.1` and updating aforementioned pr to it 
- ci tests pass
- merge v0.12.1 into v0.13.0 and release v0.13.1
=> chore(text): reintroduce spacing variant in Text

src/components/Banner/Banner.stories.tsx, src/components/Banner/Banner.tsx, src/components/Button/__snapshots__/button.spec.tsx.snap, src/components/Button/button.stories.tsx, src/components/Button/button.tsx, src/components/ButtonGroup/ButtonGroup.stories.tsx, src/components/ClickableStyle/ClickableStyle.tsx, src/components/Link/Link.stories.tsx, src/components/Link/Link.tsx, src/components/Toast/Toast.tsx, src/components/Tooltip/__snapshots__/Tooltip.spec.tsx.snap, src/components/storyUtils/clickableStyleUtils.tsx
NOTE: We're planning to merge these API update PRs in a sequence. The sequence will go:
- for each PR, merge in the EDS API update PR
- publish a new package version
- update the package in traject in a PR that has already been reviewed and is waiting to update the component API based on the EDS PR and merge that in
- move on to the next component
To prepare for migrating the `main` branch to use the v1 component versions on `next`, I'm updating the `ClickableStyle`, `Button`, and `Link` APIs (but not the internal logic – that will come later). After landing this, I'll publish a new npm package version, update the EDS package in `traject` and update the component usage to match these changes. That way when we merge the full `next` branch in and deploy, we won't have to update the buttons …
=>  feat(clickable-style, button, link): use API from next to prep for merge

src/components/Banner/Banner.tsx
The `Banner` component comment has an API example that's stale. The example is representative of the first version of the API I used on `next`. The API was changed during the PR process, but I forgot to update the example.
Verify the updated example appears in storybook.
=> docs(banner): update component comment to use updated API

docs/typography.stories.mdx, src/components/Text/Text.module.css
2 small cleanups:
- Makes "lg" size font-normal for consistency with other sizes (consumers can still pass `weight="bold"` if needed)
- Adds "lg" size to type ramp
=> Text size "lg" updates

src/components/Banner/Banner.stories.tsx, src/components/Banner/Banner.test.tsx, src/components/Banner/Banner.tsx
There's one thing about our `Banner` in the `next` branch that's very different than the one on `main` and that's the dismiss logic/API.
In the `main` `Banner`, you pass in an `onDismiss` prop to give the `Banner` a close button in the top right. You handle the dismiss logic yourself.
In the `next` `Banner`, the component has some internal dismiss logic that it tracks with component state. To make the `Banner` dismissable, you pass in `dismissable={true}`. The `onDismiss` prop is only needed if there's some logic you need to run at the time that the `Banner` is dismissed.
Now that I'm updating the API in `traject`, I'm wondering if we want to keep that logic or not.
=> feat(banner): remove internal dismiss logic

src/components/Toast/Toast.module.css, src/components/Toast/Toast.stories.tsx, src/components/Toast/Toast.tsx, src/components/Toast/__snapshots__/Toast.spec.tsx.snap, src/components/Toast/index.ts
[sc-193788]
- updates toast to match incoming `next` api
- `color` prop renamed to `variant`
- `alert` color/variant renamed to `error`
- Icon may be slightly different due to spritemap icon architecture
- pending #1012 
- chromatic: little visual differences
- icon changes
- story naming change (error/alert)
=> chore(toast): update toast to use incoming next api

.github/workflows/test.yml, .storybook/components/DesignTokens/Tier1/Tier1Tokens.stories.js, .storybook/components/DesignTokens/Tier2/Tier2Tokens.stories.js, .storybook/components/Docs/Documents.stories.tsx, .storybook/components/IconGrid/IconGrid.stories.js, .storybook/components/Utilities/Utilities.stories.js, .storybook/pages/Announcements/Announcements.stories.tsx, .storybook/pages/CoursesYear/CoursesYear.stories.tsx, .storybook/pages/CurriculumCourses/CurriculumCourses.stories.tsx, .storybook/pages/FeedbackOverview/FeedbackOverview.stories.tsx, .storybook/pages/ProjectOverview/ProjectOverview.stories.tsx, src/components/Banner/Banner.stories.tsx, src/components/Card/Card.stories.tsx, src/components/CheckboxField/CheckboxField.stories.tsx, src/components/Grid/Grid.stories.tsx, src/components/Layout/Layout.stories.tsx, src/components/LayoutContainer/LayoutContainer.stories.tsx, src/components/ListDetail/ListDetail.stories.tsx, src/components/ListDetailPanel/ListDetailPanel.tsx, src/components/Main/Main.stories.tsx, src/components/Radio/Radio.stories.tsx, src/components/ShowHide/ShowHide.stories.tsx, src/components/TableObject/TableObject.stories.tsx, src/components/TextInput/TextInput.stories.tsx, src/components/Textarea/Textarea.stories.tsx, src/components/Toolbar/Toolbar.stories.tsx
[ch187481]
Turn axe-storybook back on! most existing errors are from "fpo" blocks, the one exception is `ListDetail` text color 😬  which we've already flagged to design
build passes
=> build: re-enable axe-storybook

src/components/Banner/Banner.tsx
In updating the `Banner` usage in `traject`, I ran into an annoying issue with the `NuxMegaphone`, which is wrapping the `Banner`. It uses a nux data store, which injects some props into the component behind our backs. When we updated the `Banner` API recently, we started passing any additional props that were passed in down to the underlying `article` element. One of the props being injected, `reloadRoute`, is not a valid HTML attribute, so the tests are throwing an error. I was able to update get the tests to run in order to update the snapshots by making this change directly in the node module locally, but those test will presumably fail for the next dev trying to update those snapshots.
tl;dr I'm removing the `other` props being passed down to the `article` because the `NuxMegaphone` …
=> chore(banner): stop passing down extra props to underlying element

src/components/Banner/Banner.tsx
Due to the `NuxMegaphone` component in `traject` being annoying, I removed the `other` props being passed down to the underlying `article` element in the `Banner` component in https://github.com/chanzuckerberg/edu-design-system/pull/1032. This PR brings that change to `next` as well.
There should be no changes in the `Banner` component.
=> chore(banner): stop passing 'other' props down to the underlying article element

src/components/Text/Text.module.css, src/components/Text/Text.stories.module.css, src/components/Text/Text.stories.tsx, src/components/Text/Text.tsx, src/components/Text/__snapshots__/Text.test.tsx.snap
When migrating the `Text` component in `traject`, it became obvious that removing the `spacing` prop was going to be too much of a hassle. As such, it was re-added on `main`. This PR makes the same change on `next` to keep them in sync.
Verify there is now a `Spacing` story and the levels look the same as the one on `main`.
=> chore(text): re-add spacing prop

.stylelintrc, src/components/FileUploadField/FileUploadField.module.css, src/components/Grid/Grid.module.css, src/components/GridItem/GridItem.module.css, src/components/LinkList/LinkList.module.css, src/components/ListDetail/ListDetail.module.css, src/components/Radio/Radio.module.css, src/components/RadioField/RadioField.module.css, src/components/StackedBlock/StackedBlock.module.css, src/components/Table/Table.module.css, src/components/TableObject/TableObject.module.css, src/components/Tabs/Tabs.module.css, src/components/TextList/TextList.module.css
- remove [no-descending-specificity](https://stylelint.io/user-guide/rules/list/no-descending-specificity/) rule, as it's been more confusing than valuable
- increase `max-nesting-depth` allowed to 2 -- [we agreed awhile ago](https://czi-edu.slack.com/archives/C0310HJ9WEN/p1648490911423979?thread_ts=1648488617.379909&cid=C0310HJ9WEN) that this was fine given other code guidelines, but never got around to it
build passes
=> build: remove descending-specificty rule and allow nesting depth of 2

src/components/HorizontalStep/HorizontalStep.module.css, src/components/HorizontalStep/HorizontalStep.tsx, src/components/HorizontalStepper/__snapshots__/HorizontalStepper.test.tsx.snap, src/components/NumberIcon/NumberIcon.module.css, src/components/NumberIcon/NumberIcon.stories.tsx, src/components/NumberIcon/NumberIcon.test.tsx, src/components/NumberIcon/NumberIcon.tsx, src/components/NumberIcon/__snapshots__/NumberIcon.test.tsx.snap, src/components/NumberIcon/index.ts, src/index.ts
- add number icon
- text number enclosed in a circle
- size variants: default 'lg' and 'sm'
- Louie advised no 'md' variant, should default to 'lg'
- color variants: default 'base' and 'success'
- uses `span` but set `role='img'` and requires `aria-label` or `aria-labelledby`
- No use case where a number icon would be purely decorative?
- snap tests and unit test written
- use in HorizontalStepper creates no visual diff
base-lg:
base-sm:
success-lg:
success-sm:
double-digits:
=> feat(numbericon): add number icon

src/components/Banner/Banner.stories.tsx
The `Dark` `Tooltip` variant already has the deprecated badge in storybook, so this PR only adds the deprecated badge to the `Flat` `Banner` variant.
Very the `Flat` `Banner` variant has the "deprecated" badge (but the other variants don't).
=> docs(banner): add deprecated badge to flat story

src/components/Tooltip/Tooltip.stories.tsx
Just what it says. @anniehu4 already turned off the animation for the tooltip stories, but these still keep coming up in chromatic. The chromatic snapshots show the tooltip as having moved ever to slightly, maybe 1 or 2 pixels, left or right. The only thing I know to try is delaying the snapshot in case there's some weirdness around the tooltip is still rendering when the snapshot is being taken. The button triggering the tooltip is not appearing changed; only the tooltip itself.
Wait and see if chromatic continues to flag changes in these stories on other PRs after this PR has merged.
=> chore(tooltip): delay chromatic snapshots to see if it helps with flakiness

plopfile.js, src/index.ts
The plop generator creates files for a new component, and it also adds the new component to the `index.src` file and sorts the file so the new export is placed correctly in the file. Recently some components were commented out in the `index.src` file, which has thrown off the sorting logic – it wants to sort the commented-out components with the rest of them, which breaks the comment blocks and generally messes up the file. You can see the output of the `plop` logic in this PR: https://github.com/chanzuckerberg/edu-design-system/pull/1063
This PR updates the sort logic to use @csnizik 's code change suggestion, which only sorts the lines that start with "export". The code suggestion is posted in this comment: https://github.com/chanzuckerberg/edu-design-system/pull/1063#issuecomment-112629 …
=> chore(plop): fix sorting logic

src/components/DragDrop/DragDrop.module.css, src/components/DragDrop/DragDrop.stories.tsx, src/components/DragDrop/DragDrop.tsx, src/components/DragDrop/DragDropTypes.ts, src/components/DragDrop/__snapshots__/DragDrop.test.tsx.snap, src/components/DragDropContainer/DragDropContainer.tsx, src/components/DragDropItem/DragDropItem.tsx
Adds useHandles variant to DragDrop component. When set to true, items inherit no styles. A handle must be passed in as a prop, and the item can only be grabbed by clicking on the handle. 
https://user-images.githubusercontent.com/24812780/168608744-bdb2bc4d-a1d8-47fc-9bd0-dc9bb8ce5583.mov
New panel is added to Storybook: Organisms/Interactive/Drag and Drop/Drag By Handle. All other drag/drop functionality should be the same as the "unstyled" configuration.
=> chore(drag and drop): detached handles variant

src/components/NumberIcon/NumberIcon.stories.tsx, src/components/NumberIcon/NumberIcon.test.tsx, src/components/NumberIcon/NumberIcon.tsx
- removes `aria-labelledby` prop
- requires `aria-label` prop
- type checking makes previous console warns redundant hence removing
=> chore(numbericon): remove aria labelledby prop for aria label req

src/components/Banner/Banner.module.css, src/components/InlineNotification/InlineNotification.module.css, src/components/Toast/Toast.module.css, src/design-tokens/mixins.css
The icons and darker borders in the "warning", "success", and "brand" variants of the messaging components (`Banner`, `Toast`, InlineNotification`) are a little too light. This PR darkens them to be consistent with the mocks.
The messaging components are in a slightly awkward place right now because the border around the `InlineNotification` is darker than the border around the `Banner` and `Toast` but lighter than the dark border on the side of `Banner` and `Toast`. So we have 3 border colors (2 of which are being used in `Banner` and `Toast` and 1 that's being used in `InlineNotification`). From the mocks, it looks like the `InlineNotification` border will be used in the `Banner`, but when used in combination with the drop shadow that's on the `Banner` and `Toast`, that border looks …
=> chore(messaging): darken icons and dark borders in mixins

src/components/HorizontalStepper/__snapshots__/HorizontalStepper.test.tsx.snap
- stepper snaps broke due to classnames order changing in `Text`
- updates snaps
- no relevant visual regression
=> test(horizontalstepper): update snaps

src/components/Banner/Banner.module.css, src/components/Banner/Banner.stories.module.css, src/components/Banner/Banner.stories.tsx, src/components/Banner/Banner.test.tsx, src/components/Banner/Banner.tsx, src/components/Banner/__snapshots__/Banner.test.tsx.snap
We have brand new shiny `Banner` component styles, which are similar to the old banner but there are important changes. The component in those designs is intended to be used as a top level page banner whereas the existing `Banner` is used in the page, sometimes even in sidebars.
As such, I'm going to make a new component, called `PageLevelBanner` to serve that need. For the existing `Banner`, I'm going to make a couple of style changes so it matches the new `PageLevelBanner` a little bit, but I'm not going to change too much. I mostly just want to update the text to be gray because the links will now be gray, but I'm also updating the spacing a little bit as well. In the future, we actually want people to use the `InlineNotification` for these in-page banners (also known as "section …
=> chore(banner): update text styles to match figma

.storybook/components/DesignTokens/Legacy/LegacyTypography.stories.mdx
I noticed a console warning in storybook about 
>browser.js:39 Importing from '@storybook/addon-docs/blocks' is deprecated, import directly from '@storybook/addon-docs' instead:
>
>https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-scoped-blocks-imports
This PR follows the warning's advice and updates the one place where we were importing from "@storybook/addon-docs/blocks" to instead import from "@storybook/addon-docs".
Load up storybook and verify that warning is gone.
=> chore: don't import from @storybook/addon-docs/blocks

src/components/Button/Button.stories.tsx, src/components/Icon/Icon.stories.tsx, src/components/InlineNotification/InlineNotification.stories.tsx, src/components/Link/Link.stories.tsx, src/components/Tag/Tag.stories.tsx
I noticed a console warning about how we're using `options` in `argTypes` in our stories. It looks like we just need to move that property outside of the `control` object so they're siblings. This PR goes through and makes that change for all the relevant components.
Navigate to all the changes components (and `Checkbox` because that also uses `options` but didn't have this issue) and verify none of the components have this warning in the console now.
=> chore: move options out of control in story argTypes

.storybook/components/DesignTokens/Tier1/TypographyPresets.js
I noticed a console warning in storybook about:
>Warning: Each child in a list should have a unique "key" prop.
>
>Check the render method of `Tier1TypographyPresets`.
In this PR, I'm adding a key to quell react's concerns.
Navigate to any of the token stories in storybook and verify this error is now gone.
=> chore(token-presets): add key to map

.storybook/components/TokenSpecimen/TokenSpecimen.js
I noticed a console error in storybook about:
>Warning: A component is `contentEditable` and contains `children` managed by React.
I think what it's concerned about is that a user can click into the typography token sample text, edit the text, and then something could cause react to rerender the component, which would wipe away the user's changes. This editing capability is just so people can see what different strings will look like with these presets, so I think it's fine to just suppress the warning, which I'm doing in this PR. (I don't expect people to actually use this, especially since there's nothing in the UI to communicate that it's even possible, so I would also be fine with just removing the content editable feature.)
Navigate to any of the token stories in storybook and verify …
=> chore(token-specimen): suppress content editable warning

package.json, plop-templates/Component/Component.module.css.hbs, plop-templates/Recipe/Recipe.module.css.hbs, plopfile.js, yarn.lock
In the css modules files for components and recipes, we have a headline text that looks like `# A COMPONENT NAME`. Right now, the plop generator doesn't add spaces between the words (so it would come out like `# ACOMPONENTNAME`, which is really hard to read). In this PR, I updated the helper that formats that text to place spaces between the words.
Test out plop for both components and recipes using both a spaced component name (ex: "a component name") and pascal cased component name (ex: "AComponentName"), and verify that all of these cases produce an uppercase text headline in the css file with spaces between the words, as expected.
=> chore(plop): add spaces in css file headline

package.json
`stylelint` is currently only running on files in the `src` directory, which means it's not running on recipes and pages in the `.storybook` directory. This PR just adds `.storybook` to the list of places to lint.
Add an empty css class in the css modules file for a recipe and a page,
run `yarn lint`,
and verify those errors are reported.
=> test: make stylelint run on .storybook files

src/components/PageLevelBanner/PageLeveBanner.module.css, src/components/PageLevelBanner/PageLeveBanner.stories.tsx, src/components/PageLevelBanner/PageLeveBanner.test.tsx, src/components/PageLevelBanner/PageLeveBanner.tsx, src/components/PageLevelBanner/__snapshots__/PageLeveBanner.test.tsx.snap, src/components/PageLevelBanner/index.ts, src/index.ts
Shortcut: https://app.shortcut.com/czi-edu/story/199935/banner-align-with-eds-in-figma
Figma: https://www.figma.com/file/Ff7hJoSvXX9hkAmIklnsT2/EDS---UI-Components-(Main)?node-id=2974%3A17980
Follow-up to https://github.com/chanzuckerberg/edu-design-system/pull/1114 In that PR, I'm updating the `Banner` styles to match the new designs a little more. As I explained there, I'm going to leave the `Banner` component to support existing usage (section banner inside the page) and make a new `PageLevelBanner` component for the new usage (top level banner only used at the top of the page). This PR adds that component.
This component is mostly copy/pasted from `Banner` with a few important changes:
- no `action` prop (this component does not support buttons, just links in the text)
- this banner …
=> feat(page-level-banner): add component

.storybook/recipes/CardWithNotification/CardWithNotification.tsx
- CardWithNotification indirect export causes component naming issues:
- Direct importing and re-exporting fixes component naming issues:
- names correctly represented when built
=> fix(cardwithnotification): re-export subcomponents directly

src/components/TimelineNav/TimelineNav.tsx
While running tests, I noticed there's a `console.log` in `TimelineNav` that I'm guessing was for testing. This PR removes that logging.
Run `yarn test` and verify you don't see any logging.
=> chore(timeline-nav): remove console log from testing

src/components/Heading/Heading.tsx, src/components/Modal/Modal.stories.tsx, src/components/ModalTitle/ModalTitle.tsx
- allows the heading props for the modal title
- this allows more flexibility and control over the modal title
- unit tests
[sc-202061]
=> chore(modaltitle): allow heading props for modal title

.storybook/pages/ProjectOverview/ProjectOverview.tsx
I was looking for lint suppression comments we could clean up, and I found an easy one – the `href` attributes in the `ProjectOverview` page want actual URLs instead of hashtags.
Verify there are no lint errors or chromatic changes.
=> chore(project-overview): replace hrefs with valid urls

src/components/ModalHeader/ModalHeader.tsx
- more flexibility is requested in styling the brand asset
- adds `assetClassName` prop to be appended to the brand asset wrapper
=> chore(modalheader): allow class names for brand asset wrapper

.storybook/recipes/GlobalHeader/GlobalHeader.module.css, .storybook/recipes/PageShell/PageShell.module.css, docs/CODE_GUIDELINES.md, src/components/Card/Card.module.css, src/components/DragDrop/DragDrop.module.css, src/components/DropdownMenu/DropdownMenu.module.css, src/components/Header/Header.module.css, src/components/LinkList/LinkList.module.css, src/components/NavContainer/NavContainer.module.css, src/components/Popover/Popover.module.css, src/components/PrimaryNavItem/PrimaryNavItem.module.css, src/components/ProjectCard/ProjectCard.module.css, src/components/ShowHide/ShowHide.module.css, src/components/Tabs/Tabs.module.css, src/components/TimelineNav/TimelineNav.module.css, src/design-tokens/mixins.css, src/upcoming-components/AccordionPanel/AccordionPanel.module.css, src/upcoming-components/Drawer/Drawer.module.css, src/upcoming-components/LoadingIndicator/LoadingIndicator.module.css, src/upcoming-components/SkeletonBar/SkeletonBar.module.css, src/upcoming-components/Tags/Tags.module.css
Most of the animations in the repo right now don't have an override for animations when the user has the OS accessibility feature "prefers reduced motion" turned on, so I went ahead and added those overrides. I also added a section about this to the documentation.
I spot-checked a couple of the components to verify that the animation runs when the setting is turned off and does not run when the setting is turned on.
=> chore: override transition for prefers reduced motion everywhere

src/components/ShowHide/ShowHide.tsx, src/upcoming-components/Drawer/Drawer.tsx
`event.code` for some reason doesn't work in our environment, but `event.key` does. There are 4 components using `e.code`:
- `TimelineNav` (being updated in https://github.com/chanzuckerberg/edu-design-system/pull/1157)
- `ShowHide` (being updated in this PR)
- `Drawer` (being updated in this PR)
Verify that the `ShowHide` component now closes when clicking the escape key while the component is open and you're focused on the trigger. (`Drawer` is not in storybook because it's in the `upcoming-components` directory, so I just tested `ShowHide` for now.)
=> chore(show-hide, drawer): use e.key instead of e.code in keyboard events

.github/workflows/test.yml
- build storybook in a step separate from chromatic
- should fix [ci errors](https://github.com/chanzuckerberg/edu-design-system/runs/6941477884?check_suite_focus=true) when chromatic thinks there are no differences in code and hence never builds storybook for axe testing
https://github.com/chanzuckerberg/edu-design-system/runs/7047367707?check_suite_focus=true
- check that storybook is built in separate step
- check that chromatic does not build storybook
- check that axe tests work
=> chore(ci): build storybook separately from chromatic

src/components/Modal/Modal.module.css, src/components/Modal/Modal.tsx
- increases modal z-index
- allows passing of `modalContainerClassName` to style the container
[sc-203638]
- styling allowed via classname: 
- no jest failures
=> chore(modal): allow passing of modalContainerClassName to target modal container

src/components/Modal/Modal.module.css, src/components/Modal/Modal.stories.tsx, src/components/Modal/__snapshots__/Modal.test.tsx.snap, src/components/Tooltip/Tooltip.tsx
- Tooltips have a default z-index of 9999
- Tooltips need to render on top of modal
- Modal z-index shrank to 1050 to match [bootstrap modal z-index](https://github.com/FB-PLP/traject/blob/fe07779f6bca7920df27be8750dabf7517b34a74/app/assets/stylesheets/v2/_overrides/_bootswatch_variables.scss#L263-L276)
- Tooltips props extended with Tippy props (the base component) to allow custom z-index if 9999 is too high
- Created story to align more z-indexes https://app.shortcut.com/czi-edu/story/203871
- Unit tests pass
- No visual regression
- Manual test tooltip spawning above modal:
- In Modal stories, hover over button 1
=> fix(modal): render tooltips on top of modal

src/components/Banner/__snapshots__/Banner.test.tsx.snap, src/components/Button/__snapshots__/Button.test.tsx.snap, src/components/ButtonDropdown/__snapshots__/ButtonDropdown.test.tsx.snap, src/components/ButtonGroup/__snapshots__/ButtonGroup.test.ts.snap, src/components/ClickableStyle/ClickableStyle.tsx, src/components/FieldNote/__snapshots__/FieldNote.test.ts.snap, src/components/Link/__snapshots__/Link.test.tsx.snap, src/components/Modal/__snapshots__/Modal.test.tsx.snap, src/components/PageLevelBanner/__snapshots__/PageLevelBanner.test.tsx.snap, src/components/Popover/__snapshots__/Popover.test.tsx.snap, src/components/ProjectCard/__snapshots__/ProjectCard.test.tsx.snap, src/components/ShowHide/__snapshots__/ShowHide.test.tsx.snap, src/components/TextField/__snapshots__/TextField.test.ts.snap, src/components/TimelineNav/__snapshots__/TimelineNav.test.ts.snap, src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
I tested the new link styles in `traject` using an alpha build, and I noticed that bootstrap styles are adding an underline for `a` tags on hover and focus for "primary" and "secondary" variants, and that's also reducing the text-decoration thickness for "link" variants on hover and focus.
This PR adds data-bootstrap-override attributes for the different `ClickableStyle` variants so I can override these styles in `traject`.
There should be no visible changes in chromatic or storybook.
=> chore(clickable-style): add data-bootstrap-override attributes

src/components/ClickableStyle/ClickableStyle.test.tsx, src/components/ClickableStyle/ClickableStyle.tsx
We're now throwing an error in `Button` and `Link` components if an unsupported `status`/`variant` prop combination is being used. Unfortunately, there's an instance in `traject` that is using an invalid combination and it will take a little work to fix it. (The instance is in `Token`, which is being used in a few different places with different styling overrides, so I don't want to update it without taking the time to work out the styles and verify there are no regressions.) Ticket to fix this: https://app.shortcut.com/czi-edu/story/204850/fix-variant-in-token-in-traject
This PR downgrades the error to a console warning so we're still alerting devs that they're using the wrong combination but it doesn't break every page with a token on it.
I also added a default `as` to `ClickableStyle` …
=> chore(clickable-style): downgrade error to warning for invalid combos

src/design-tokens/mixins.css
This is super tedious but on the link styles, the focus background is moved down 100% except on focus, and there is the tiniest sliver visible. This PR changes it to 101% to push it just a little bit further down so it's fully off-screen.
Verified on the `Link` component default story (be advised that, for whatever reason, this only appears when the element underneath is also a link). This change isn't being picked up by chromatic, presumably because the line is too small?
=> chore(link): translateY 101% so the focus bg is fully off-screen

src/components/Banner/__snapshots__/Banner.test.tsx.snap, src/components/Button/__snapshots__/Button.test.tsx.snap, src/components/ButtonDropdown/__snapshots__/ButtonDropdown.test.tsx.snap, src/components/ButtonGroup/__snapshots__/ButtonGroup.test.ts.snap, src/components/ClickableStyle/ClickableStyle.module.css, src/components/ClickableStyle/ClickableStyle.tsx, src/components/Link/__snapshots__/Link.test.tsx.snap, src/components/Modal/__snapshots__/Modal.test.tsx.snap, src/components/PageLevelBanner/__snapshots__/PageLevelBanner.test.tsx.snap, src/components/Popover/__snapshots__/Popover.test.tsx.snap, src/components/ProjectCard/__snapshots__/ProjectCard.test.tsx.snap, src/components/ShowHide/__snapshots__/ShowHide.test.tsx.snap, src/components/TextField/__snapshots__/TextField.test.ts.snap, src/components/TimelineNav/__snapshots__/TimelineNav.test.ts.snap, src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap, src/design-tokens/mixins.css
In testing the new link styles in LP, I noticed that the margin is for some reason not allowing local styles to override it. Here I'm adding `:where` around those specific styles, which the button margin style already has. 
No changes in `Button` and `Link` storybook.
=> chore(link): lower spacing specificity

src/components/HorizontalStep/HorizontalStep.module.css, src/components/HorizontalStep/HorizontalStep.tsx, src/components/HorizontalStepper/HorizontalStepper.module.css, src/components/HorizontalStepper/HorizontalStepper.stories.module.css, src/components/HorizontalStepper/HorizontalStepper.stories.tsx, src/components/HorizontalStepper/HorizontalStepper.tsx, src/components/HorizontalStepper/__snapshots__/HorizontalStepper.test.tsx.snap, src/components/NumberIcon/NumberIcon.module.css, src/components/NumberIcon/NumberIcon.tsx, src/components/TimelineNav/__snapshots__/TimelineNav.test.ts.snap
- allows passing `linesClassName` to `<HorizontalStepper>` to custom style the dividing lines between steps
- changes incomplete dot icon to "icon-disabled" (#C0C4C8)
[sc-205022]
- incomplete dots color changes in chromatic snaps where used
- capped line horizontal story
- unit tests pass with snap updates
=> chore(horizontalstepper): allow line class names and change dot color

src/components/ProjectCard/ProjectCard.stories.tsx, src/components/ProjectCard/ProjectCard.tsx, src/components/ProjectCard/__snapshots__/ProjectCard.test.tsx.snap
- Add conditional around `CardFooter` in `ProjectCard` so that dropdown doesn't render when `buttonDropdownItems` aren't defined
Ticket link: https://app.shortcut.com/czi-edu/story/204517/projectcard-make-buttondropdownitems-optional
- yarn lint passes
- yarn test passes
- yarn types passes
- yarn start works
=> 204517 project card optional dropdown

src/components/ProjectCard/ProjectCard.tsx
- Added conditional to include `numberAriaLabel` around the `NumberIcon` within project card. Emma was getting warnings implementing since that prop is required in `NumberIcon` but the number isn't always in the card. This should fix that.
- `yarn test` runs
- `yarn types` runs
- `yarn lint` runs
- `yarn start` runs
=> fix: numberAriaLabel conditional project card

src/components/Modal/__snapshots__/Modal.test.tsx.snap, src/components/TimelineNav/TimelineNav.module.css
https://app.shortcut.com/czi-edu/story/204977/timeline-nav-styles
- Spacing between items: < lg breakpoints: space between each nav item should be --eds-size-5 (40px); lg and > breakpoints: space between each nav item should be --eds-size-10 (80px)
- Border and box shadow: < lg breakpoints: no background color, no box shadow; lg and > breakpoints: background is neutral default, top-left and bottom-left border radii are border-radius-xl, box shadow (on timeline-nav__body) is 0px 2px 8px var(--eds-theme-color-border-neutral-subtle)
- Fixed issue with background color behind .timeline-nav__link-left
=> chore(timeline nav): fix styling issues

src/components/ProjectCard/ProjectCard.stories.tsx, src/components/ProjectCard/ProjectCard.tsx, src/components/ProjectCard/__snapshots__/ProjectCard.test.tsx.snap
- Added conditional wrapper around `meta` in `ProjectCard` to make that optional for Emma
- Added story with this to show that this is possible
`yarn lint` runs through
`yarn test` runs through
`yarn types` runs through
`yarn start` runs
=> fix: optional meta in project card

CHANGELOG.md, package.json
Just keeping `next` up-to-date with `main`.
=> chore(release): 1.6.1

src/components/Modal/Modal.module.css, src/components/Modal/Modal.stories.tsx, src/components/Modal/Modal.tsx, src/components/Modal/__snapshots__/Modal.test.tsx.snap
- there have been a couple requests to make modal smaller
- this pr allows the setting of the modal size to not break larger
- keeps responsiveness
- [slack context](https://czi-edu.slack.com/archives/CTFV79JH4/p1658331665549089)
- updated modal snaps
- no visual regressions on non affected chromatic tests
- new modal size stories captured in chromatic
=> chore(modal): expose modal sizes

src/components/Text/Text.module.css
We're using the `neutral-default` color token for the "neutral" `Text` `variant`, but it should be `neutral-subtle`. (Not sure how this got out of sync; oh well, it happens.)
This is a really subtle change, but you can see in the second screenshot that the neutral text is now visible in the third column because it's lighter than the token used for the background.
Verify the "neutral" text is now using the `subtle-neutral` token in the `variants` `Text` story: http://localhost:9009/?path=/story/atoms-text-text--variants
=> chore(text): use neutral-subtle for neutral variant

.storybook/pages/FeedbackOverview/FeedbackOverview.tsx, src/components/Table/Table.module.css
https://app.shortcut.com/czi-edu/story/207521/table-card-mobile-treatment-for-feedback-overview
Adds extra padding beneath first cell when the Highlight First Cell and Stacked variants are used.
For breakpoints > md: table in Feedback Overview should remain unchanged
For smaller breakpoints: each row should appear as a card that closely matches the formatting in Figma (see screenshot or link above)
=> chore(feedback overview): card display for tables on < md breakpoints

src/components/Banner/Banner.tsx, src/components/Banner/__snapshots__/Banner.test.tsx.snap, src/components/PageLevelBanner/PageLevelBanner.tsx, src/components/PageLevelBanner/__snapshots__/PageLevelBanner.test.tsx.snap
In https://github.com/chanzuckerberg/edu-design-system/pull/1162 I made the "neutral" variant of the `Text` component lighter. The `Banner` and. `PageLevelBanner` are using that variant, but the figma designs show them having darker text, like before that change. This change makes them dark again by adding `variant="base"` to their `Text` usage.
Verify that banner text content is darker again.
=> fix(banner, page-level-banner): darken content text to base

src/components/Banner/Banner.stories.tsx, src/components/Banner/Banner.tsx, src/components/Banner/__snapshots__/Banner.test.tsx.snap, src/components/PageLevelBanner/PageLevelBanner.stories.tsx, src/components/PageLevelBanner/PageLevelBanner.tsx, src/components/PageLevelBanner/__snapshots__/PageLevelBanner.test.tsx.snap
The close button in our `Banner` and `PageLevelBanner` components comes before the content of the banners for screen reader users. That could be confusing because they don't know what the close button would actually be closing. The close button and content are contained in an `article` element, so they're semantically grouped, but screen reader users shouldn't have to read the content and then go *back* to the close button to remove the component. This PR moves the button to the end of the component, after the content. The appearance of the banner is unchanged.
https://user-images.githubusercontent.com/7761701/180834055-f8a5b8fe-5942-4033-8aca-dd80aeb7eda5.mp4
https://user-images.githubusercontent.com/7761701/180834088-677469e6-a63e-4805-8156-f3f71ca01a8d.mp4
Verify there are no visual …
=> fix(banner): move close button to end of content

.storybook/pages/CoursePlannerEdit/CoursePlannerEdit.tsx, .storybook/pages/ProjectOverview/ProjectOverview.tsx, .storybook/recipes/TableCard/TableCard.tsx, README.md, src/components/Banner/Banner.tsx, src/components/Banner/__snapshots__/Banner.test.tsx.snap, src/components/Heading/Heading.module.css, src/components/Heading/Heading.tsx, src/components/HorizontalStepper/__snapshots__/HorizontalStepper.test.tsx.snap, src/components/InlineNotification/InlineNotification.tsx, src/components/InlineNotification/__snapshots__/InlineNotification.test.tsx.snap, src/components/NumberIcon/NumberIcon.tsx, src/components/NumberIcon/__snapshots__/NumberIcon.test.tsx.snap, src/components/PageHeader/PageHeader.tsx, src/components/PageHeader/__snapshots__/PageHeader.test.tsx.snap, src/components/PageLevelBanner/PageLevelBanner.tsx, src/components/PageLevelBanner/__snapshots__/PageLevelBanner.test.tsx.snap, src/components/ProjectCard/ProjectCard.tsx, src/components/ProjectCard/__snapshots__/ProjectCard.test.tsx.snap, src/components/Text/Text.module.css, src/components/Text/Text.stories.tsx, src/components/Text/Text.tsx, src/components/TimelineNav/__snapshots__/TimelineNav.test.ts.snap
We have 3 different neutral color tokens for text:
- `neutral-subtle`
- `neutral-default`
- `neutral-strong`
Currently the `Text` component only supports `neutral-default` via the "base" variant and `neutral-subtle` via the "neutral" variant. The `Heading` component only supports `neutral-strong` via both the "base" and "neutral" variants.
I talked to design and they said all 3 tokens should be available to both components. I suggested that we replace the "base" and "neutral" variant options with 3 different options representing the 3 neutral tokens:
- "neutral-subtle"
- "neutral-medium"
- "neutral-strong"
I suggested using "medium" instead of "default" because the `neutral-strong` token is typically used for the `Heading` component, so it feels confusing to me to use "default" when …
=> feat(text, heading): allow all 3 neutral text colors via variant prop

src/components/TimelineNav/TimelineNav.tsx, src/components/TimelineNav/__snapshots__/TimelineNav.test.ts.snap
This fixes an issue where a keyboard user who has focus on the  'Back' button could use alt-tab to put keyboard focus back on the menu, which is currently off-canvas. To prevent this unwanted behavior, we add an onFocus event listener to the 'Back' button that sets the currently active menu item's tabIndex to "-1", making it unable to receive focus via sequential keyboard navigation. The 'Back' button should be the only way users are able to return to the nav list, both visually and via sequential keyboard navigation.
Larger breakpoints should be unaffected by this work, since the 'Back' button is only visible on < lg breakpoints (and this ticket is adding a function to the Back button's `onFocus` listener).
Smaller breakpoints:
1. Open the browser's console and create a live expression …
=> chore(timeline nav): a11y issue  - sequential keyboard navigation

docs/GETTING_STARTED.md
The "Getting Started" cover page in storybook has some "[TODO]" comments. I'm actually not sure what the author was thinking we would write there, so I'd like to just remove them for now. I would like to expand this page to include tips for things people get stuck on (or I used to get stuck on) in storybook (canvas vs docs tabs, keyboard shortcuts), and there are probably other things we can expand on, but I'm fine with iterating on this page over time.
Ticket for expanding on this page: https://app.shortcut.com/czi-edu/story/208951
Verify there are no "[TODO]" comments in the "Getting Started" storybook page.
=> docs(getting-started): remove todo comments

src/components/DropdownMenu/DropdownMenu.tsx
Clears TS error, "No overload matches this call" in DropdownMenu.tsx
If this solution is accepted, it can also be applied to:
ButtonDropdown.tsx:172
Tabs.tsx:306
TimelineNav.tsx:252
`yarn types` should run without errors.
=> chore(dropdown): ts error

src/components/ClickableStyle/ClickableStyle.module.css
I just noticed that `ClickableStyle` content isn't horizontally centered, which normally doesn't matter because we determine the component width using padding, but buttons using the `fullWidth` prop have their content on the left side, which looks weird. (This prop isn't being used in `traject` yet.)
Verify the text is now horizontally centered in the "full width" story for the `Button` and `Link` components.
=> chore(clickable-style): center content horitontally

src/components/ProjectCard/ProjectCard.test.tsx, src/components/ProjectCard/ProjectCard.tsx
- `numberAriaLabel` should not be required if there is no `number`
- warns if doesn't exist if `number` is passed
- wrote unit test
=> fix(projectcard): make numberAriaLabel optional but warn

src/components/DrawerHeader/DrawerHeader.tsx
- need to refer to the correct color token as the DrawerHeader no longer lives in `upcoming-components`
- will follow up with an eds patch fix
- built file refers to correct token
=> fix(drawerheader): correctly refer to color token

CHANGELOG.md, package.json
From changelog:
* **drawerheader:** correctly refer to color token ([a92c92b](https://github.com/chanzuckerberg/edu-design-system/commit/a92c92b1df000737839bb2473cc60c8563549b1e))
(this double committed for some reason, probably because I fumbled the tags (is why this branch is `-b` but is correct now), but is correct in the source)
A patch release as a followup to fix #1226
=> chore(release): v3.1.1

src/components/PageHeader/PageHeader.module.css, src/components/PageHeader/PageHeader.stories.tsx, src/components/PageHeader/PageHeader.tsx, src/components/PageHeader/__snapshots__/PageHeader.test.tsx.snap
- Motivation:
- There was a request to add an area above the pageheader title for components like breadcrumbs
- Turned out the area exists, but is wrapped with a div with some set margins
- Execution:
- Removes the div wrapper
- unit tests pass, pageheader snap updated
- no visual regressions except for pageheader overline story
=> fix(pageheader): remove wrapping div for overline

.storybook/recipes/BaselineCard/BaselineCard.tsx, src/components/Score/Score.module.css, src/components/Score/Score.stories.tsx, src/components/Score/Score.test.tsx, src/components/Score/Score.tsx, src/components/Score/__snapshots__/Score.test.tsx.snap, src/components/Score/index.ts, src/components/Tag/Tag.module.css, src/components/Tag/Tag.tsx, src/index.ts
[sc-209039]
- Motivation
- a score is needed for Cards and Tables in the Student Refinement Pilot
- Tag needed styles update to align with UI Kit
- Arguably, score component itself may not be needed but this incorporates multiple styles overrides and keeps scores components consistent
- Execution
- <Score> component wraps <Tag>
- Wraps <Tag> variant styles in `:where()` to allow classname styling
- Uses tag typography token
- No visual regression except for Tag styles changes
- Score snaps written
=> feat(score): add score component

README.md
[sc-209860]
for some reason [4a4668214dbc47af6b51adf30ae15e8de266bd05](https://github.com/chanzuckerberg/edu-design-system/commit/4a4668214dbc47af6b51adf30ae15e8de266bd05) changes that were previously landed are not applied on `next` or `main`, re-raising
=> docs(readme): add token imports to README

src/components/ClickableStyle/ClickableStyle.module.css, src/components/FieldNote/__snapshots__/FieldNote.test.ts.snap, src/components/Link/Link.module.css, src/components/Link/Link.stories.tsx, src/components/Link/Link.tsx, src/components/Link/__snapshots__/Link.test.tsx.snap, src/components/StackedBlock/__snapshots__/StackedBlock.test.tsx.snap, src/design-tokens/mixins.css
We got a comment about how links aren't wrapping well in paragraphs – if the link text is in a paragraph that wraps but the link text itself does not wrap it's fine; but if the link text is situated in such a way that the link text wraps, it will break away from the rest of the text and sit on its own line. This is because we have `display: inline-flex` on the link styles.
We were aware of this behavior, but it had been like that for a long time and no one had commented on it – *until now*. And since we're pushing for more mobile-friendly designs and less ultra-short link text (ie "here" and "learn more"), I think it's going to keep coming up.
There are 2 side effects from removing `display: inline-flex`:
- the animation for the focus state won't work (which is fine; that was just a fun …
=> chore(clickable-style, button, link): set display to inline on link variant

src/components/Modal/Modal.stories.tsx, src/components/Modal/__snapshots__/Modal.test.tsx.snap
- disables possibly flaky modal snap where the opening of the modal auto hovers the tooltip trigger. Tooltip snaps are known to be flaky.
- other tests pass
- referred snap is removed
=> test(modal): disable flaky snap

.storybook/recipes/GlobalHeader/GlobalHeader.tsx, src/components/FieldNote/FieldNote.module.css, src/components/FieldNote/FieldNote.tsx, src/components/TextField/TextField.tsx, src/components/TextField/__snapshots__/TextField.test.ts.snap, src/components/TextInput/TextInput.tsx, src/components/TextInput/__snapshots__/TextInput.test.ts.snap, src/design-tokens/css/base/body.css, src/design-tokens/mixins.css, src/upcoming-components/CheckboxField/CheckboxField.tsx, src/upcoming-components/Counter/Counter.module.css, src/upcoming-components/Counter/Counter.tsx, src/upcoming-components/FileUploadField/FileUploadField.module.css, src/upcoming-components/FileUploadField/FileUploadField.tsx, src/upcoming-components/RadioField/RadioField.module.css, src/upcoming-components/RadioField/RadioField.tsx, src/upcoming-components/Textarea/Textarea.tsx, src/upcoming-components/TextareaField/TextareaField.tsx
- motivation 
- for input field migration, error and disabled handling is better styled more conventionally to our repo
- execution
- this renames `eds-is-error` and `eds-is-disabled` which are BM remnants to `--error` and `--disabled` or the psuedoclass`:disabled` and unnests those classes from their stylesheets
- also un-italicizes placeholder mixin to match mocks
- new unit snaps
=> chore: rename disabled and error classes conventionally

docs/CODE_GUIDELINES.md, src/components/ButtonGroup/ButtonGroup.tsx
A while back I updated the component comments to match our preferred pattern, but I didn't update the docs to explain this. This PR updates the documentation and also updates the component I referenced. I added that component comments should include example usage, which we've sometimes been doing but not always, so I'm wondering how people feel about adding that to the guidelines. I think it's useful and I find that sort of thing really helpful when reading documentation for other systems, but I also understand if people feel like it's overkill for simple components.
Verify the `ButtonGroup` comment is showing properly in storybook and that the new documentation section appears as expected.
=> docs: add guidelines for component comment

package.json, yarn.lock
- removes [cz-convetional-changelog](https://github.com/commitizen/cz-conventional-changelog) which seems abandoned
- we don't use `npx cz` or `git cz` to make commits
- stops dependabot alerts regarding [minimist](https://github.com/chanzuckerberg/edu-design-system/security/dependabot/17)
- doesn't seem to affect standard-version:
- standard-version works
- no test fails in anything
=> chore(deps): remove abandoned cz-conventional-changelog dep

src/components/FieldNote/FieldNote.module.css
- icon was not properly receiving color token
- fixes css selection to receive color token
- visual regression on error icon color only
=> fix(fieldnote): match error icon color to mocks

.storybook/recipes/DataSummaryCard/DataSummaryCard.module.css, .storybook/recipes/DataSummaryCard/DataSummaryCard.stories.tsx, .storybook/recipes/DataSummaryCard/DataSummaryCard.tsx, .storybook/recipes/DataSummaryCard/index.ts, plop-templates/Recipe/Recipe.tsx.hbs, src/components/Checkbox/Checkbox.stories.tsx
[sc-211849]
- motivation
- Data Summary Card is used in the school and district tools pilot
- Data Summary Card displays simple data of students to provide status at a quick glance
- Communicates 'off-track' status if necessary
- execution
- Wraps the `Card` component
- Relevant mocks: [Recipe](https://www.figma.com/file/CQu6m6sxvFO0zYSrWq6jsH/Data-Summary-Card---Creation-Exploration?node-id=5961%3A12067), [usage in poc](https://www.figma.com/file/PJ6pnQy2J68vLiYJwTCy2y/SDT-Course-%3E-Students-Proof-of-Concept-Pilot?node-id=158%3A20107)
=> feat(datasummarycard): adds DataSummaryCard recipe

src/components/Tooltip/Tooltip.module.css, src/components/Tooltip/Tooltip.stories.tsx, src/components/Tooltip/Tooltip.test.tsx, src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
Our `Tooltip` component currently doesn't work on disabled buttons (which is a relatively common pattern). The reason is, `Tippy` only worked on elements that have a `tabIndex`, which disabled elements don't have. The solution is to wrap the children in a `span` with a `tabIndex` of 0.
I was originally going to add documentation and a story to this effect, but then I noticed the `react-bootstrap` `OverlayTrigger` component has a `childDisabled` prop. If we use a prop like that, we can wrap the children in a `span` with a `tabIndex` so our users don't have to. (I also noticed some weirdness around needing a different `display` styling for top and bottom alignment, so we can bake that in too.
I verified the tooltip looked okay with all 4 alignments in storybook.
=> feat(tooltip): add childDisabled prop

src/components/ClickableStyle/ClickableStyle.module.css
Currently our buttons don't have visible focus outlines in Safari. Through process of elimination, I found that the source of the issue is the `transition` styling. The `transition` is targeting `all`, not specific CSS properties (which is considered best practice). I don't know exactly what's going on, but making the transition specific, which I was planning to do anyway at some point, fixes this.
Open storybook in Safari,
navigate to either the `Button` component and a component that uses it (like the dismissable `PageLevelBanner` stories),
tab to the button with your keyboard,
and verify the focus outline is visible.
(Please note that you need to have turned on the "Press Tab to highlight each item on a webpage" accessibility setting in Safari to see this functionality.)
=> chore(clickable-style): make transition target more specific

.storybook/pages/FeedbackOverview/FeedbackOverview.tsx, .storybook/preview.tsx, .stylelintrc, package.json, postcss.config.js, src/components/Drawer/DrawerExample.tsx, src/components/HorizontalStepper/HorizontalStepper.stories.module.css, src/components/HorizontalStepper/HorizontalStepper.stories.tsx, src/components/HorizontalStepper/__snapshots__/HorizontalStepper.test.tsx.snap, src/design-tokens/css/base/tailwind.css, tailwind.config.js, yarn.lock
[ch213288]
Tailwind utilities are easier to use than the BM-defined ones, and especially for reference pages & recipes, are easier for app developers to copy & paste in.
Note that this matches our behavior before BM -- it's a separate question whether & how to use utilities in component styles themselves.
This PR has 5 commits:
1: Adds back all the necessary config stuff to get Tailwind working again
2-4: Converts styles in each of the types of files we want to support Tailwind utilities in to make sure it's working.
5: Turn off preflight reset styles to ensure no visual changes
I'd also expect to see no changes in chromatic
=> Add back tailwind utilities for stories & recipes

src/components/Modal/__snapshots__/Modal.test.tsx.snap, src/components/TextField/TextField.stories.tsx, src/components/TextField/TextField.tsx, src/components/TextField/__snapshots__/TextField.test.ts.snap
[sc-213670]
- during design crit, discussed need of the optional indicator
- if optional, just don't passed required was decided
- no usage of optional indicator in platform
- no visual regression except removal of optional variant textfields
=> chore(textfield): remove optional indicator

src/components/Score/Score.module.css, src/components/Score/Score.stories.tsx, src/components/Score/Score.tsx, src/components/Score/__snapshots__/Score.test.tsx.snap
[sc-213671]
- during design crit, discussed using the transparent border score variant advised for use in the Table component only
- decided on renaming variant to `table`
- no visual regression except change of `neutral` to `table` variant
=> chore(score): rename neutral variant to table

docs/COMPONENTS.md
This PR updates the component documentation to describe our new beta process. In https://github.com/chanzuckerberg/edu-design-system/pull/1266 I'm removing a bunch of beta tags from mature existing components.
Almost all of our components have a beta tag (in storybook and also in the component docstring) even though some of them were completed months ago. This morning we discussed what should be the threshold for component graduation out of beta status, and it was decided that:
- when a component is in beta when it's first released/announced
- upon the following release, the component is no longer in beta
- releases will probably happen about once/month
Verify the new documentation looks okay in the visual studio preview.
=> docs(components): add information about beta status

src/components/Tooltip/Tooltip.module.css, src/components/Tooltip/Tooltip.stories.tsx, src/components/Tooltip/Tooltip.test.tsx, src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
We're seeing `Tooltip` usage in `traject` where the child is not an interactive element (like an icon that's not a button). We just added the `childDisabled` prop so the `Tooltip` supports disabled buttons and such as `children`. This prop also works for other non-interactive children, but the prop name is a little confusing to use in those situations. To make this usage clearer, I'm renaming the `childDisabled` prop to `childNotInteractive`.
I added a story that has text in a react fragment to verify the prop works for that situation.
=> chore(tooltip)!: rename childDisabled to childNotInteractive

.storybook/recipes/GlobalHeader/GlobalHeader.module.css, src/components/BreadcrumbsItem/BreadcrumbsItem.module.css, src/components/Drawer/Drawer.module.css, src/components/DropdownMenu/DropdownMenu.module.css, src/components/LinkList/LinkList.module.css, src/components/Logo/Logo.module.css, src/components/Popover/Popover.module.css, src/components/PrimaryNavItem/PrimaryNavItem.module.css, src/components/Tabs/Tabs.module.css, src/components/TimelineNav/TimelineNav.module.css, src/design-tokens/mixins.css, src/upcoming-components/AccordionPanel/AccordionPanel.module.css, src/upcoming-components/Tags/Tags.module.css
When discussion https://github.com/chanzuckerberg/edu-design-system/pull/1250 we realized that the browser versions we support don't all support the `focus-visible` CSS feature, which we're currently using in a few places in the codebase.
This PR just replaces `:focus-visible` with `:focus`.
Spot check that these now show focus on both mouse and keyboard interaction.
=> chore: use focus instead of focus-visible

src/components/NotificationList/NotificationList.module.css
@jinlee93 flagged that the button in notification list items does not currently have a visual state change on focus. (This button serves as the "read" indicator, and the user can trigger it to flip the "read" state.)
This PR just adds the regular focus outline on focus.
- navigated to http://localhost:9009/?path=/story/molecules-lists-notificationlist--default
- verified I could tab through the notification text and buttons
- verified there's now a focus outline on the buttons when focused
- verified I can flip the "read" status on the buttons with the keyboard
=> fix(notification-list): add focus state to button

src/components/ModalBody/ModalBody.tsx
The `ModalBody` component isn't passing down extra props, which means you can't put a `data-testid` on it for end-to-end tests. This PR just passes extra props down onto the wrapper `div`.
I temporarily added a `data-testid` to a `Modal.Body` in the `Modal.stories.tsx` file and verified in the browser that the attribute is being passed down.
=> chore(modal-body): pass down extra props to wrapper div

src/components/ClickableStyle/ClickableStyle.module.css, src/design-tokens/tier-2-usage/typography-usage.css
The "sm" `Button` styles are being updated to make the text smaller and horizontal padding bigger.
- font size: 14px => 12px
- line height: 24px => 20px
- height: unchanged (24px)
- left/right padding: 4px => 8px
Verify "sm" `Button` styles reflect new size properties.
=> chore(clickable-style): update sm button styles

src/components/Popover/Popover.stories.tsx
Like the overlay component that relies on Headless (*cough* Dropdown *cough*) Popover seems to have Chromatic flakiness. This introduces Chromatic delay to attempt to resolve said flakiness.
=> chore(popover): add delay to reduce chromatic flakiness

src/components/Popover/Popover.stories.tsx
I'm sadly still seeing flaky `Popover` snapshots in chromatic even after a delay was added 😞 I think this may be related to the issue with `Tooltip`, but I don't know what that is, so I'm just disabling the tests for now so they don't get in devs' way.
For an example of the issue, I have a [PR that just updated some documentation](https://github.com/chanzuckerberg/edu-design-system/pull/1287), but it still managed to trigger [5 Popover snapshot changes in chromatic](https://www.chromatic.com/build?appId=61313967cde49b003ae2a860&number=2608).
There's already a [shortcut story for investigating the Tooltip chromatic issue](https://app.shortcut.com/czi-edu/story/200684/fix-tooltip-chromatic-issues).
Verify there are no chromatic changes for this PR.
=> test(popover): skip chromatic testing

.storybook/recipes/NotificationListPopover/NotificationListPopover.stories.tsx, src/components/DataBar/DataBar.stories.tsx, src/components/Popover/Popover.stories.tsx
Follow-up to https://github.com/chanzuckerberg/edu-design-system/pull/1288 in which I turned off the chromatic snapshots for the `Popover` component.
The `NotificationListPopover` chromatic snapshots are also flaky because that component uses the `Popover`, so I'm disabling this one as well. Here's an example of a build where the snapshot appeared changed even though the code couldn't possibly have caused the change: https://www.chromatic.com/build?appId=61313967cde49b003ae2a860&number=2621
No chromatic changes triggered for the `NotificationListPopover`.
=> test(notification-list-popover): skip chromatic snapshots

src/components/ClickableStyle/ClickableStyle.module.css, src/design-tokens/mixins.css
This is part of the work for https://app.shortcut.com/czi-edu/story/191861/consider-using-focus-visible-in-button-styles
It was brought to our attention that the focus style for links looks like a bug to mouse users because it's so prominent. As users, we mostly ignore focus outlines on buttons when clicking around, but the link style (white text on a flat dark background) really catches the user's attention. We would like to move towards removing focus states on mouse interaction for most interactive components (input fields are one exception we're aware of but there may be more we'll decide on later). Technically we could just remove it for links right now, but I would like for us to be consistent about it or else it will look like links are buggy in a different way.
Along already has …
=> chore(clickable-style): only show focus state for keyboard users

.storybook/recipes/GlobalHeader/GlobalHeader.module.css, docs/CODE_GUIDELINES.md, src/components/BreadcrumbsItem/BreadcrumbsItem.module.css, src/components/CheckboxInput/CheckboxInput.module.css, src/components/Drawer/Drawer.module.css, src/components/DropdownMenu/DropdownMenu.module.css, src/components/LinkList/LinkList.module.css, src/components/Logo/Logo.module.css, src/components/ModalBody/ModalBody.module.css, src/components/NotificationList/NotificationList.module.css, src/components/PrimaryNavItem/PrimaryNavItem.module.css, src/components/RadioInput/RadioInput.module.css, src/components/Tabs/Tabs.module.css, src/components/TimelineNav/TimelineNav.module.css, src/upcoming-components/AccordionPanel/AccordionPanel.module.css
In https://github.com/chanzuckerberg/edu-design-system/pull/1290 I updated the buttons and links to only show the focus state when the user interacts with them using a keyboard (as opposed to with a mouse/trackpad). The implementation method was done using `focus-visible` along with a fallback block for browsers that don't support it yet. (I added a [ticket to remove the fallback blocks](https://app.shortcut.com/czi-edu/story/215843/remove-focus-fallback-css) once we're only supporting browser versions that support `focus-visible`.)
In this PR, I'm expanding to use this method on almost all `:focus` states. Exceptions include:
- `inputStyles` mixin and `SearchField` component
- I talked to design and we determined that we want mouse users to see the focus state so they know that typing on …
=> chore: use focus-visible instead of focus everywhere

src/components/Tooltip/Tooltip.module.css, src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
I recently added `childNotInteractive` prop to `Tooltip` for cases where the `children` passed into the tooltip is, as you might guess, not interactive (e.g. an icon, some text, or a disabled button). In order for the tooltip to work on non-interactive elements, the child needs to be wrapped in a `span` or `div` with `tabIndex=0`, so this prop allows us to add the wrapper for the consumer.
I also added `display: inline-flex` to the wrapper if the tooltip's placement is `top` or `bottom` because otherwise the tooltip arrow isn't in quite the right position. But when I tried to use this in `traject`, some of the elements didn't appear at all, which I didn't notice (and then [someone else had to go revert the commit](https://github.com/FB-PLP/traject/pull/12244)). Since it's much worse for …
=> chore(tooltip): remove disply: inline-flex from non-interactive wrapper

CHANGELOG.md, package.json
Just keeping `next` in sync with `main`.
=> chore(release): 5.1.0

package.json
- We removed the dependency for cz-conventional-commit in the last 6 months. This PR removes the lingering configuration in package.json, which references that dependency. Conventional commits are still enforced by linting rules (commitlint/config-conventional)
- ensure CI passes and `install` works as expected
=> chore: remove unused commitizen config from package.json

src/components/Tag/Tag.module.css, src/components/Tag/Tag.stories.tsx, src/components/Tag/Tag.tsx, src/components/Tag/__snapshots__/Tag.test.ts.snap
Addresses #686, #794
These issues are a little old but still valid
- Passes `other` props for broad data attributes for Tag
- Removes `max-width` for tag
- added `data-testid` to a story
- no errors and seen in storybook
- snap updated including `data-testid`
- no other unit test failures
=> fix(tag): allow data attributes on tag and remove max-width

src/components/Layout/Layout.tsx, src/components/LayoutSection/LayoutSection.tsx
I happened to notice some "expandable" prop thingies in `Layout` and `LayoutSection` that don't seem to be used, and I don't think we have any plans to make these things expandable, so I'm removing them.
All automated tests pass and there are no visual changes detected by chromatic.
=> chore(layout): remove expandable prop options

src/components/DragDrop/DragDrop.module.css, src/components/DragDrop/DragDrop.stories.module.css, src/components/DragDrop/DragDrop.stories.tsx, src/components/DragDrop/DragDrop.tsx, src/components/DragDrop/DragDropTypes.ts, src/components/DragDrop/__snapshots__/DragDrop.test.tsx.snap, src/components/DragDropContainer/DragDropContainer.tsx
- [slack discussion](https://czi-edu.slack.com/archives/CTFV79JH4/p1663958436719399?thread_ts=1663181721.585879&cid=CTFV79JH4)
- This allows classnames to be passed in to style the dragdrop containers, containers wrapper, dragdrop containers columns, and does a little cleanup regarding
https://user-images.githubusercontent.com/86632227/192334637-18577425-98ff-4c12-8eb1-af3447d7348d.mov
- DragDrop itself is not the easiest to read and could definitely [use some clean up or even a refactor](https://app.shortcut.com/czi-edu/story/216547)
- Adds interactive story in DragDrop showing the customizable wrapper, container, and column
- No other visual regression
- Unit tests pass
=> chore(dragdrop): allow further styling

src/components/FiltersDrawer/FiltersDrawer.tsx
- guilty of using `createRef` and was reminded by https://github.com/chanzuckerberg/edu-design-system/pull/1314#discussion_r979126279
- uses `useRef` not `createRef` for `filtersDrawer`
- all tests pass
=> chore(filtersdrawer): use useRef not createRef

src/components/DragDropContainer/DragDropContainer.tsx, src/components/Tabs/Tabs.tsx, src/components/TimelineNav/TimelineNav.tsx, src/custom.d.ts
[sc-196807]
Add types for `react-children-by-types`, to improve the types, of some of our types.
Inspired by the cleanups in #1311.
- Type checking
- Unit tests
=> Add types for react-children-by-type

package.json
We use Sauce Labs for testing on various browsers and devices. [Sauce Labs only supports certain ports for testing localhost](https://docs.saucelabs.com/secure-connections/sauce-connect/advanced/specifications/#supported-browsers-and-ports), and the current port (9009) isn't on the list. This PR updates the storybook port to 9000 to make Sauce Labs testing easier.
- run `yarn storybook`
- verify it runs on `localhost:9000` instead of `localhost:9009`
=> chore: run storybook on port 9000 instead of 9009

package.json, src/components/Tabs/Tabs.tsx, src/custom.d.ts, yarn.lock
[sc-196807]
Follow up to #1314. This PR does a couple (somewhat related) things:
- Updates TypeScript to 4.8
- Fixes the types for react-children-by-type
- Cleans up some comments and names in Tabs a bit
- Tests
=> More tabs cleanup

docs/CONTRIBUTING.md
From onboarding: I believe the new process is rolled out, so updating the text here to reflect how to use `next` when making new changes.
- n/a (documentation change)
=> docs: update language around 'next' base branch

src/components/Tabs/Tabs.test.tsx, src/components/Tabs/Tabs.tsx, src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
More tabs cleanup:
- Remove unused prop
- Simplify getting tab children, refs, and ids
- Don't clone elements that won't be shown
- Fix some logic
- Use good keys
- Storybook
- Tests
=> Tabs cleanup #3

src/components/Tooltip/Tooltip.stories.tsx, src/components/Tooltip/Tooltip.tsx
Someone ran into an issue when using the `Tooltip` where Typescript complains when you pass it an `id` prop. To avoid running into this again in the future when someone needs to pass in a `data-testid` or something, I'm extending the prop type to include `React.HTMLAttributes<HTMLElement>`.
- I added an `id` prop to one of the stories,
- verified that Typescript threw an error before making the change to the prop types,
- and verified the error stopped after I made the change to the prop types.
=> chore(tooltip): allow HTMLElement attributes as props

src/components/Tooltip/Tooltip.tsx
Exposes the `appendTo` prop from Tippy with docstring
- No visual regressions
- Unit tests pass
=> chore(tooltip): expose appendTo prop and add docstring

src/components/ButtonDropdown/ButtonDropdown.stories.tsx, src/components/ButtonDropdown/ButtonDropdown.tsx, src/components/ButtonDropdown/__snapshots__/ButtonDropdown.test.tsx.snap, src/components/DropdownMenu/DropdownMenu.module.css, src/components/DropdownMenu/DropdownMenu.tsx, src/components/DropdownMenu/__snapshots__/DropdownMenu.test.tsx.snap, src/components/DropdownMenuItem/DropdownMenuItem.tsx, src/components/ProjectCard/__snapshots__/ProjectCard.test.tsx.snap
[sc-216210]
- [slack context](https://czi-edu.slack.com/archives/CTFV79JH4/p1665004863841489)
Motivation: 
- After opening button dropdown via click, the focus lands on the first item, but previously due to `:focus-visible` this is not indicated
- This means that there needs to be separate hover and focus indicators for the dropdown menu items
- In safari, apparently clicking a `<button>` [doesn't focus it](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#clicking_and_focus) for some odd reason and hence keyboard functionality is lost after clicking button
Execution:
- go back to `:focus` from `:focus-visible` and separate from `:hover`
- close dropdown menu on click and on tab to make safari not focusing not a problem (sorry double negative)
- Items are no longer …
=> chore(dropdownmenu): close with tab, revert to :focus, close on click

CHANGELOG.md, package.json
Keeps `next` in sync with `main`
Just a package.json version bump and changelog auto adds
=> chore(release): 5.2.0

src/components/ButtonDropdown/ButtonDropdown.tsx, src/components/DropdownMenu/DropdownMenu.tsx, src/components/DropdownMenuItem/DropdownMenuItem.tsx, src/components/InputField/InputField.tsx, src/components/TextField/TextField.tsx
Due to `projectCard` using `buttonDropdown`/`dropdownMenu` and not `popover` some issues arise as it tries to use secondary functionality when dropdown menus should purely be primary functionality (aka anchor and button elements only)
This panel with the `TextField` and `ButtonGroup` is rendered when a menu item is clicked, so it initially made sense to use a dropdown menu.
[While projectCard is being worked on to use popover instead](https://app.shortcut.com/czi-edu/story/224122/use-popover-and-not-dropdown-in-project-card), we need to support this secondary functionality in a dropdown menu.
Hence changes in this pr: 
- no longer closes dropdownmenu on close
- forwards ref to the input element in `TextField` and `InputField`
- clean up work with types
- alpha build created with the …
=> chore(dropdownmenu, textfield, inputfield): clean up types and onclick, forward ref 

package.json
- runs prettier on built tokens after building them
- resolves the double quote being spat out from style dictionary causing lint errors
- no lint errors after running `yarn build:tokens`
- tokens build unaffected
=> chore(build): run prettier on tokens dist after building them

src/icons/play-arrow.svg, src/icons/spritemap/spritemap.svg
[sc-201336] This icon included a bounding rectangle in figma, which was causing a strange appearance in Firefox, and was inconsistent with the other icons. Import a new icon that does not have this mask, but preserves the same dimensions. Tested in Firefox and other Webkit-based browsers.
- test icon layout in chrome / firefox : http://localhost:9000/?path=/story/atoms-icons-icongrid--default
- ensure icon is not clipped
=> fix(icons): remove mask from play icon

src/components/Tabs/Tabs.module.css, src/components/Tabs/Tabs.stories.tsx
- noticed right mask for tabs was not being styled correctly, adds size to show mask
- right mask exists in deployed storybook
=> chore(tabs): add size for tabs right mask

.github/workflows/test.yml
Auto accept chromatic changes on the `next` and `main` branches.
I noticed there were changes on `next`. Definitely indicates some flakiness, but I think it's best to assume that what's on `main`/`next` is correct (or at least that's what we do in LP and Along... but what do YOU think?).
🤞
=> Auto accept chromatic

src/components/Tabs/Tabs.stories.tsx
- scrolls even farther to ensure scrolled fully
- adds delay to account for viewport size change
- this story should just be removed if chromatic continues to flake
- ran chromatic locally 3 times and got the same visual result
- https://www.chromatic.com/build?appId=61313967cde49b003ae2a860&number=2863
- https://www.chromatic.com/build?appId=61313967cde49b003ae2a860&number=2862
- https://www.chromatic.com/build?appId=61313967cde49b003ae2a860&number=2861
=> chore(tabs): unflake scroll end story

src/components/ButtonDropdown/ButtonDropdown.tsx, src/components/ProjectCard/ProjectCard.tsx, src/components/ProjectCard/__snapshots__/ProjectCard.test.tsx.snap
- applies the className prop in `ButtonDropdown` to `DropdownMenu` and not the wrapper
- the trigger button and the items can already be styled individually, just not the menu through `ButtonDropdown`
=> chore(buttondropdown): apply class name to dropdown menu

docs/PUBLISHING.md
I was just going through the release publish flow, following our publishing documentation, with @booc0mtaco and accidentally published the version before sending it through the pull request review process because of that message printed in the terminal after running `yarn release`. I normally don't publish the version until after the release PR has been reviewed (which is what our documentation says to do), but I was led astray by the siren song of the confusing terminal message. The message (which reads "Run \`git push --follow-tags origin release-v[some version] && npm publish\` to publish") comes from the [standard-release package](https://github.com/conventional-changelog/standard-version/blob/f5bff12515aadf5f532c2e7a992c929c5f633469/lib/lifecycles/tag.js#L38), so I don't think we can …
=> docs(publishing): add warning about terminal message suggesting you publish the version

CHANGELOG.md, package.json
Just keeping `next` up-to-date with `main`.
=> chore(release): 5.3.0

src/icons/play-arrow.svg, src/icons/spritemap/spritemap.svg
In https://github.com/FB-PLP/traject/pull/12532 we updated the `play-arrow` icon to no longer have a mask. This involved reexporting the icon from figma, which brought along a hard-coded fill color. That hard-coded fill color blocked the icon color from being changed. This PR removes the `fill` attribute to be consistent with the other icons.
Navigate to the [icon story in storybook](http://localhost:9000/?path=/docs/atoms-icons-icon--default),
switch to the "docs" tab (if it's not there already),
in the props list, change the icon to "play-arrow" and the color to something random (like grape 800),
and verify the icon color changes to the selected color.
=> fix(icons): remove play-arrow hard-coded fill color

.storybook/pages/CoursePlannerEdit/CoursePlannerEdit.tsx, src/components/DragDrop/DragDrop.stories.tsx, src/components/DragDrop/__snapshots__/DragDrop.test.ts.snap, src/components/ProjectCard/ProjectCard.stories.tsx, src/components/ProjectCard/ProjectCard.tsx, src/components/ProjectCard/__snapshots__/ProjectCard.test.tsx.snap
[slack context](https://czi-edu.slack.com/archives/CTFV79JH4/p1666915992251169)
There's a request to allow custom icons on the ProjectCard component.
Due to high specificity of the ProjectCard, it should probably live in LP ([ticket](https://app.shortcut.com/czi-edu/story/226852)
But due to immediate need, this pr is raised
No visual regression outside ProjectCard stories
Unit tests pass
=> chore(projectcard)!: add metaIconName to allow custom meta icons and remove if not present

CHANGELOG.md, package.json
keep `next` in sync with `main` with [release v6.0.0](https://github.com/chanzuckerberg/edu-design-system/pull/1360)
=> chore(release): v6.0.0

tsconfig.json
[sc-225828]
- Thought about trying to change the source to the `lib` folder but doesn't make too much sense since the source file itself is not part of the publish
- Including the source files in the publish is unnecessary and makes it heavier
- Source maps don't seem too useful as devs hopefully don't need to debug EDS components from consuming apps and and its currently not working state can either block or spam warnings
- As a result remove source maps
- Build is unaffected besides source maps
=> chore(build): remove source map

postcss.config.js
This PR is to configure the tailwind to allow nested css in eds ,to handle the bunch of warnings in the dev console in EDS storybook complaining about tailwind not being configured to handle nested CSS.
=> chore: configure tailwind to allow nested css in eds

src/components/Tooltip/Tooltip.module.css
In order for theming to work properly, components should only be using tier 2 or 3 tokens (except in cases of deprecated components or variants which we don't want people to theme anyway). There are a couple of instances where tier 1 tokens are being used, notably in the `Tooltip` component. I'll address the others in a separate PR.
Verify there are no color changes to the `Tooltip` component when open.
=> chore(Tooltip): replace tier 1 token usage in styles

.storybook/recipes/CalendarCard/CalendarCard.tsx, .storybook/recipes/NotificationListPopover/NotificationListPopover.tsx, .storybook/recipes/StackedCardsToTable/StackedCardsToTable.tsx, docs/CODE_GUIDELINES.md, src/components/ButtonDropdown/ButtonDropdown.tsx, src/components/ButtonGroup/ButtonGroup.tsx, src/components/Card/Card.tsx, src/components/CardBody/CardBody.tsx, src/components/CardFooter/CardFooter.tsx, src/components/DefinitionList/DefinitionList.tsx, src/components/DragDropContainer/DragDropContainer.tsx, src/components/DragDropItem/DragDropItem.tsx, src/components/DropdownMenu/DropdownMenu.tsx, src/components/FiltersCheckboxField/FiltersCheckboxField.tsx, src/components/Modal/Modal.tsx, src/components/Popover/Popover.tsx, src/components/ProjectCard/ProjectCard.tsx, src/components/Table/Table.tsx, src/components/Text/Text.tsx, src/components/TimelineNav/TimelineNav.tsx, src/components/Toolbar/Toolbar.tsx, src/components/ToolbarItem/ToolbarItem.tsx
This PR contains a grab bag of various component comment cleanups, such as:
- removing any references to "Primary UI component for user interaction", which was the old default component comment and is still hanging around in a couple of places where the comment was updated to include actual useful information
- adding backticks around elements being used as text (mostly in `Text.tsx`)
- code blocks use `tsx` instead of `ts`
- various grammar touch-ups (like adding periods at the end of sentences)
- general wordsmithing to reduce redundancy
Viewed the updated components in storybook to verify their documentation has updated.
=> docs: misc cleanup for component comments

README.md
updates the workflow badge directory so it shows up when landing on our Github page
=> fix(readme): update workflow badge directory

docs/CODE_GUIDELINES.md
Follow-up to https://github.com/chanzuckerberg/edu-design-system/pull/1377 in which I moved and removed jsdoc tags because they mess up how documentation appears in storybook. This PR updates the documentation to advise against using jsdoc tags to avoid hitting these issues again in the future.
Previewed the documentation in visual studio code and verified it looked good.
=> docs: advise against using jsdoc tags

src/tokens-dist/json/css-variables-nested.json, style-dictionary.config.js, tailwind.config.js
[EDS-736]
[EDS-259]
Relates to #1375, except instead of replacing `-@` with `-default`, assigns the appropriate `child-grandchild` key to the respective value.
**<i>Please let me know if I could word the helper utility function comment any better to make it clearer.</i>**
- The `colors-background.json` and other similar files are where we define our tier 2 / 3 tokens, looks like: 
- In this screenshot, `{ eds: {theme: {color: {background: {neutral: {default: {@: {value: "{eds.color.neutral.white}"` compiles to `EdsThemeColorBackgroundNeutralDefault` in `src/tokens-dist/ts/colors.ts` and css custom property `--eds-theme-color-background-neutral-default`. 
- However the formatter used to generate `css-variables-nested.json` (primarily used for TW) compiles to `{ eds: {theme: {color: …
=> chore(tailwind): remove -@ in token bulding

src/components/Banner/Banner.tsx, src/components/Banner/__snapshots__/Banner.test.ts.snap, src/components/PageLevelBanner/PageLevelBanner.tsx, src/components/PageLevelBanner/__snapshots__/PageLevelBanner.test.ts.snap
Ticket: https://czi-tech.atlassian.net/browse/EDS-110
We're currently using the [article](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/article) element tag for the `Banner` and `PageLevelBanner` components, but, after some discussion, we decided that [aside](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/aside) is a better semantic choice here.
Snapshots for `Banner` and `PageLevelBanner` show the components are now using `aside` instead of `article`.
=> fix(banner, page-level-banner): use aside instead of article

docs/CODE_GUIDELINES.md, src/components/Drawer/__snapshots__/Drawer.test.ts.snap, src/components/DrawerHeader/DrawerHeader.tsx, src/components/FiltersDrawer/__snapshots__/FiltersDrawer.test.tsx.snap, src/components/NavContainer/__snapshots__/NavContainer.test.ts.snap, src/components/PrimaryNav/__snapshots__/PrimaryNav.test.ts.snap, src/components/PrimaryNavItem/PrimaryNavItem.module.css, src/components/PrimaryNavItem/PrimaryNavItem.tsx, src/components/TimelineNav/TimelineNav.module.css, src/components/TimelineNav/TimelineNav.tsx, src/components/TimelineNav/__snapshots__/TimelineNav.test.ts.snap
Ticket: https://czi-tech.atlassian.net/browse/EDS-705
In order to support theming, we only want to use CSS variables, not JavaScript variables, for styling components. This will allow other downstream products to override the variables we use for styling. The `Icon` component is typically colored by passing in a JS variable via the `color` prop. This is fine in other products, and it's fine in storybook files, but we don't want to use this convention in components themselves.
This PR updates components with colored `Icon`s to use css variables for the color, and I updated the documentation that says to do the opposite.
There is also one icon color change—the `DrawerHeader` was overriding the close button icon color to be lighter. I checked the [figma design for the Filter …
=> chore: use css variables instead of js variables for color in icons

.storybook/data/tokens.json, src/components/ModalHeader/ModalHeader.module.css, src/design-tokens/tier-3-component/modals.json, src/tokens-dist/css/variables.css, src/tokens-dist/json/css-variables-nested.json, src/tokens-dist/json/variables-nested.json, src/tokens-dist/scss/_variables.scss, src/tokens-dist/ts/colors.ts
Ticket: https://czi-tech.atlassian.net/browse/EDS-704
We only want tier 2 and tier 3 tokens to be used in components so that downstream products using the components can easily override the token values using css variables. We have just 1 left I believe, which is in the `ModalHeader` brand background color. We synced with design today and decided a new tier 3 token would be added, and it would be called "color modal brand header background". This PR adds the new token and uses it in the `ModalHeader` `brand` variant.
No visual changes in the brand modal.
=> chore(modal-header): use tier 3 token for brand header background color

.storybook/pages/AlongDemo/GlobalStyles.module.css
Part of https://czi-tech.atlassian.net/browse/EDS-741
Couple of small updates for the Along theming demo CSS variables:
- fix copy/paste error where it says "WIREFRAME" at the top
- update comment above the EDS overrides to match the one in the [wireframe demo](https://github.com/chanzuckerberg/edu-design-system/pull/1395/files)
- remove the comment separating tier 2 and tier 3 token overrides
- sort the variables
No visual changes picked up by chromatic.
=> chore(along-demo): tidy up css variables

src/tokens-dist/json/css-variables-nested.json, style-dictionary.config.js
[EDS-743]
- deletes empty objects in `css-variables-nested.json` to prevent potential TW utility class bugs and housekeeping
- run `yarn build:tokens`
- `css-variables-nested.json` eds theme objects should not have empty objects as properties
[EDS-743]: https://czi-tech.atlassian.net/browse/EDS-743?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(style-dictionary): delete empty object in css-variables-nested

.eslintrc
Ticket: https://czi-tech.atlassian.net/browse/EDS-706
There are a couple of coding patterns we've been using that interfere with theming. After having cleaned up those patterns, I'm looking at adding lint rules to avoid them creeping back in in the future.
This PR adds an eslint rule for importing JS color variables into component files. (Importing JS color variables into the `.storybook` directory and `*.stories.ts/x` files is still okay.)
I added `import { EdsThemeColorIconNeutralSubtle } from '../../tokens-dist/ts/colors';` to the `DrawerHeader.tsx` file (it could be any color variable and any component file, but I used a code example from [when I cleaned up this pattern earlier](https://github.com/chanzuckerberg/edu-design-system/pull/1391)) and verified the JS color variable import …
=> chore: lint for JS color variables imported into components

src/components/Menu/Menu.module.css, src/components/Menu/Menu.stories.tsx, src/components/Menu/Menu.tsx, src/components/Menu/__snapshots__/Menu.test.tsx.snap
In [our designs](https://www.figma.com/file/Ff7hJoSvXX9hkAmIklnsT2/branch/4xGGJyfPCeoAvYX5Fjssdf/EDS-Paper-v1.1-%7C-UI-Components?node-id=7831%3A24711&t=tafQ4kj7AkliGAew-0), we have the popover content for menus match the width of the trigger, but the initial implementation didn't follow this pattern. use a non-fragment react node to allow width to be determined by DOM structure
=> fix(Menu): sync width of trigger and popover

.github/renovate.json5, .github/workflows/update-dependencies.yml
[EDS-758]
- Uses Renovate to auto bump EDS dependencies
- Runs Every Monday 0600 PST
- Supposed to:
- based off `next` branch
- assign `edu-design-system` [team](https://docs.renovatebot.com/configuration-options/#reviewers) as reviewers
- have one concurrent pr 
- bump non major versions, except for < 0.1.0 and > 0.1.0 and < 1.0.0
- and some other similar behavior as the [LP renovate](https://github.com/FB-PLP/traject/blob/master/.github/renovate.json5)
- tested somewhat working in `jlee/renovate-run` where renovate did create pr's #1403 and #1404 
- need someone to confirm this is correct behavior since it was 2 concurrent prs and attempted to bump major versions
- didn't assign `edu-design-system` team 
- these might be some funky behavior due to not having a ["special …
=> Use renovate to auto bump deps

src/components/DataBar/DataBar.module.css, src/components/DataBar/DataBar.tsx, src/components/DataBar/__snapshots__/DataBar.test.tsx.snap, src/components/DataBarSegment/DataBarSegment.module.css, src/components/DataBarSegment/DataBarSegment.tsx
- whilst working on the progress bar noticed that the databar styles were not in sync with the mocks
- syncs styles with the mocks and cleans up some now obsolete code
- stylistically, shrinks spacing between the label wrapper and the databar from 1rem to 0.5rem and the height of the databar from 1rem to 0.875rem
- impact is indicated by visual diffs of the recipes/pages, and in LP the only page impacted is the [`CoursePlanEdit` page](https://www.chromatic.com/test?appId=614b969675171d003ac6f98a&id=638974d54f0d45e3f3992aa2). This uses the [`estimatedInstructionalBlocks` lp component](https://www.chromatic.com/test?appId=614b969675171d003ac6f98a&id=638974d54f0d45e3f3992aa3) where visual diffs are again represented.
- Change is safe since only one page is impacted, and only in about 10px of …
=> Update databar styles

.storybook/pages/AlongDemo/AlongDemo.module.css, .storybook/pages/AlongDemo/AlongDemo.tsx, .storybook/pages/WireframeDemo/WireframeDemo.module.css, .storybook/pages/WireframeDemo/WireframeDemo.tsx
Ticket: https://czi-tech.atlassian.net/browse/EDS-741
Just some polish on the theming demos:
- in both demos, global footer is an unordered list
- in both demos, the reflection text and response text area is the same width as the video
- wireframe demo watch page background is white
- along demo watch page white background extends to the bottom
- along demo logged out page user illustrations have relevant alt text
- along demo global footer has vertical dividers between the links
- along watch page heading text is not bold and has a margin above it
- along demo watch page dropdown button has transparent background and horizontally centered content
Verify the listed changes are present in the theming demos in storybook.
=> chore: tidy up theming demos

.storybook/pages/WireframeDemo/GlobalStyles.module.css
Ticket: https://czi-tech.atlassian.net/browse/EDS-734
In https://github.com/chanzuckerberg/edu-design-system/pull/1385 I added a wireframe theme demo, which overrides a bunch of eds tokens with tokens specifically made for wireframe prototypes. I only updated the EDS tokens I needed in order to make the demo work and therefore didn't touch tokens that were not present in the demo (and I also skipped over some tokens that were already gray because it didn't make a difference).
But the wireframe theme will, we think, be used in prototypes that may use more components than the ones I did, so, just to be safe, I'm overriding all the color tokens with wireframe tokens. Now this set of tokens can be copy/pasted into a different app using EDS to apply the wireframe theme and it should just work. …
=> chore(wireframe-demo): update remaining color variables

.storybook/pages/WireframeDemo/WireframeDemo.stories.ts
I've been seeing some instability in the wireframe demo watch page in chromatic. [Here's an example test result.](https://www.chromatic.com/test?appId=61313967cde49b003ae2a860&id=638fe69db3f2bd66f548e4d2) Specifically, for some reason, sometimes the form border and border neutral strong variables aren't being updated correctly, and they're falling back to the value set in EDS. Why only these 2 variables are an issue, I don't know. This isn't not showing up as a problem in the Along demo, which I don't understand either.
I'm not terribly motivated to dig too deep into the issue because this is just a demo page, and people won't notice if the gray we use on those borders is slightly different from the other grays on the page. I'm more interested in quieting the test so it doesn't get in the …
=> chore(wireframe-demo): disable chromatic snapshot tests

.github/renovate.json5, .github/workflows/update-dependencies.yml
- Saw that putting only [major version of renovate](https://github.com/chanzuckerberg/edu-design-system/actions/runs/3634187356/jobs/6132023885#step:1:35) is not recognized
- Sets renovate version to prevent
- Also prevents onboarding renovate pr according to https://github.com/renovatebot/github-action#configurationfile
- https://github.com/chanzuckerberg/edu-design-system/actions/workflows/update-dependencies.yml update deps jobs ran with push on this branch (which was reverted cuz we want it on cron)
- Saw that renovate action works since it generated the onboarding prs (which I closed since we don't want this behavior)
- Will have to see if job runs correctly on Monday as scheduled
=> Set renovate version and prevent onboarding pr

docs/ICONS.md
In https://github.com/chanzuckerberg/edu-design-system/pull/1396 I updated all the icons that were using colors in their `fill` properties that were not tier 2 or tier 3 css color variables.
To avoid this happening in the future, I considered adding a linter, but decided it was too much work considering we don't add icons very often. ([There is a ticket, set to "won't do", for this in case it turns out to be a problem in the future.](https://czi-tech.atlassian.net/browse/EFI-819))
Instead, I'm updating the documentation for adding icons to include a snippet about this.
I previewed the file in VS Code and verified the new text looked like I was expecting.
=> docs(icons): specify that colored icons should use tier 2 or 3 variables

docs/THEMING.md
Ticket: https://czi-tech.atlassian.net/browse/EDS-732
This PR expands on the documentation around theming in EDS storybook. Lemme know if there's anything else you think it should cover.
Tested in storybook locally that the changes appear as expected and the links work (except for the one to the along theme variables because that change isn't on the `main` branch yet).
=> docs(theming): describe how to use theming in EDS and other products

package.json
- `deploy:docs` command also broke with node 18, applies workaround similar to running storybook
- `deploy:docs` runs without erroring
=> fix(deploy): apply workaround for node 18

CHANGELOG.md, package.json
Keeping `next` up to date with `main`.
=> chore(release): 7.1.0

CHANGELOG.md, package.json
Keeping `next` up-to-date with `main`.
=> chore(release): 7.1.1

src/components/Menu/Menu.module.css, src/components/Menu/Menu.tsx, src/components/Menu/__snapshots__/Menu.test.tsx.snap, src/components/PopoverContainer/PopoverContainer.module.css, src/components/Select/Select.module.css, src/components/Select/Select.stories.module.css, src/components/Select/Select.tsx, src/components/Select/__snapshots__/Select.test.tsx.snap
align styles, layout, and focus changes to `Menu`, `Select` and their shared sub-components. make sure the spacing works the same between the components, their text and icons, and that they match the mocks where noted. This is applying design feedback to the current implementations, but changes no behavioral details.
Select Component (before/after):
Menu Component (before/after): 
(essentially the "after" pictures show how this updates the two components to remove unwanted inconsistencies)
=> fix: apply consistency updates to popovers

package.json, src/components/LoadingIndicator/LoadingIndicator.module.css, src/components/LoadingIndicator/LoadingIndicator.stories.ts, src/components/LoadingIndicator/LoadingIndicator.test.ts, src/components/LoadingIndicator/LoadingIndicator.tsx, src/components/LoadingIndicator/__snapshots__/LoadingIndicator.test.ts.snap, src/components/LoadingIndicator/index.ts, src/index.ts, yarn.lock
Add in a loader component, which can be used when there's a non-finite amount of time until loading is completed. Allow for some preliminary props to control size, and apply color overrides by CSS (blocking the component interface).
use the [react loader spinner](https://mhnpd.github.io/react-loader-spinner/docs/components/oval)'s `Oval` implementation. 
Future use case, apply an `as` prop to allow any other loader types using the same component (for example).
=> feat(LoadingIndicator): add loader indicator component

src/components/LoadingIndicator/LoadingIndicator.module.css
Define a fallback behavior when reduce motion is enabled. This accessibility behavior is esp. useful in context of many loading indicators on screen at once, which could produce some undesirable optical effects.
=> fix(LoadingIndicator): add reduced motion behavior

package.json, src/components/Dropdown/__snapshots__/Dropdown.test.tsx.snap, src/components/Menu/__snapshots__/Menu.test.tsx.snap, src/components/Select/__snapshots__/Select.test.tsx.snap, yarn.lock
Pin headlessui/react to 1.7.5, to resolve E2E test failures in https://github.com/FB-PLP/traject/pull/13040.
Seeing
```
Error: RangeError: Maximum call stack size exceeded.
at HTMLDocument.enforceFocus (http://localhost:3003/javascripts/js/vendor.js:134963:21)
at S (http://localhost:3003/javascripts/js/vendor.js:162697:1335)
at onBlur (http://localhost:3003/javascripts/js/vendor.js:161872:2651)
at onBlur (http://localhost:3003/javascripts/js/vendor.js:162820:954)
at HTMLUnknownElement.callCallback (http://localhost:3003/javascripts/js/vendor.js:110567:14)
at Object.invokeGuardedCallbackDev (http://localhost:3003/javascripts/js/vendor.js:110616:16)
at invokeGuardedCallback (http://localhost:3003/javascripts/js/vendor.js:110678:31)
at invokeGuardedCallbackAndCatchFirstError …
```
=> Pin headlessui/react to 1.7.5

src/components/Accordion/Accordion.tsx, src/components/AccordionButton/AccordionButton.tsx, src/components/AccordionPanel/AccordionPanel.tsx, src/components/Badge/Badge.tsx, src/components/LoadingIndicator/LoadingIndicator.tsx, src/components/Menu/Menu.tsx, src/components/Popover/Popover.tsx, src/components/ProgressBar/ProgressBar.tsx, src/components/Select/Select.tsx, src/components/Skeleton/Skeleton.tsx
- Pull in the documentation from zeroheight to synchronize with what's in zeroheight (see ticket for link(s)).
=> docs: sync doc.s for new components with zeroheight

docs/CODE_GUIDELINES.md, src/components/Heading/Heading.stories.tsx, src/components/Heading/Heading.tsx, src/components/Modal/Modal.stories.tsx, src/components/Modal/Modal.test.tsx, src/components/Modal/Modal.tsx, src/components/Tag/Tag.stories.tsx, src/components/Tag/Tag.tsx, src/components/Text/Text.tsx, src/components/Toast/Toast.stories.ts, src/components/Toast/Toast.tsx
- removes default exports from 5 components
- correctly points affected files to named import
- all other components don't have default exports
- resolves eslint errors that were happening locally 
- doesn't break LP
- tested via [7.3.0-alpha.0](https://www.npmjs.com/package/@chanzuckerberg/eds/v/7.3.0-alpha.0) release and [tests pass](https://app.circleci.com/pipelines/github/FB-PLP/traject?branch=jlee%2FtestNoDefaultComponentExportEDS) in LP test branch
- manually looked for imports to `@czi/eds/lib/components/{component}/{component}` and didn't find default import instances
=> refactor: remove default exports from components

.storybook/recipes/GlobalHeader/GlobalHeader.tsx, .storybook/recipes/NotificationListPopover/NotificationListPopover.tsx, src/components/Popover/Popover.stories.tsx, src/components/Popover/Popover.tsx, src/components/Popover/__snapshots__/Popover.test.tsx.snap
- after discussion with design, will remove the example showing the (already deprecated) `showArrow` prop
- update test snapshots
=> refactor(Popover)!: remove showArrow from popover

.github/workflows/test.yml, package.json
Turns on Chromatic's [turbosnap](https://www.chromatic.com/docs/turbosnap) feature (again).
Needs building storybook with `--webpack-stats-json` flag
[GH action](https://github.com/chanzuckerberg/edu-design-system/actions/runs/3963705567/jobs/6791843654#step:6:52) shows turbosnap on and this pr skipped all snapshots
=> ci(chromatic): turn on turbo snap

docs/PUBLISHING.md
- add clarity on the message to use for the PR to `main`
- clarify when not to do what is output from the console
- n/a (documentation)
=> docs: update and clarify publishing instructions

package.json
This PR specifies that EDS does not have [sideEffects](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free)
- Let's esbuild and webpack tree shake EDS.
- Meaning apps using EDS only ship code for the components they use, as opposed to all components.
- I actually made this change 1.5 years ago in #554, but it seems to have gotten wiped out in the BM repo changes 🤨 
- Before this change: in the Remix test app code for all EDS components is present, despite only using Heading.
- After this change: only the Heading code is present.
=> Side effects

src/components/Accordion/__snapshots__/Accordion.test.tsx.snap, src/components/Banner/__snapshots__/Banner.test.ts.snap, src/components/Breadcrumbs/Breadcrumbs.tsx, src/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.tsx.snap, src/components/Button/__snapshots__/Button.test.tsx.snap, src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap, src/components/Drawer/__snapshots__/Drawer.test.ts.snap, src/components/Fieldset/__snapshots__/Fieldset.test.ts.snap, src/components/FiltersDrawer/__snapshots__/FiltersDrawer.test.tsx.snap, src/components/FiltersPopover/__snapshots__/FiltersPopover.test.tsx.snap, src/components/HorizontalStepper/__snapshots__/HorizontalStepper.test.tsx.snap, src/components/Icon/Icon.tsx, src/components/Icon/__snapshots__/Icon.test.ts.snap, src/components/InlineNotification/__snapshots__/InlineNotification.test.ts.snap, src/components/Link/__snapshots__/Link.test.tsx.snap, src/components/Modal/__snapshots__/Modal.test.tsx.snap, src/components/PageHeader/__snapshots__/PageHeader.test.ts.snap, src/components/PageLevelBanner/__snapshots__/PageLevelBanner.test.ts.snap, src/components/PrimaryNav/PrimaryNav.tsx, src/components/PrimaryNav/__snapshots__/PrimaryNav.test.ts.snap, src/components/Radio/__snapshots__/Radio.test.tsx.snap, src/components/SearchBar/__snapshots__/SearchBar.test.ts.snap, src/components/Section/__snapshots__/Section.test.ts.snap, src/components/Table/__snapshots__/Table.test.ts.snap, src/components/TextField/__snapshots__/TextField.test.ts.snap, src/components/TimelineNav/__snapshots__/TimelineNav.test.ts.snap, src/components/Toast/__snapshots__/Toast.test.ts.snap
Removed usage of `useUID` from the three following components: `<Icon />`, `<PrimaryNav />` , and `<Breadcrumbs />`. Note, the `id` prop can still be passed to the components.
Why are we making this change?
To remove `console.error` messages from SSR in remix-run. Rendering these components would log errors like
> Warning: Prop `id` did not match. Server: "1" Client: "2"
Follow-up, there is still a fair bit of usage of `react-uid` in the EDS repo. Those IDs are being used for accessibility and will be dealt with in a separate PR. This PR removes unnecessary usages
=> [EFI-875] chore: remove uneccessary usage of react-uid

src/components/ClickableStyle/ClickableStyle.stories.tsx
- as we are recommending `ClickableStyle` for use with router-based link components, expose the doc.s for this so that it can be referenced in zeroheight and other places
=> test(ClickableStyle): add stories for the utility component

package.json
- tokens are not being provided since css marked as side effect free https://614b969675171d003ac6f98a-jstsqkayzt.chromatic.com/?path=/story/core-components-projectcard--default
- adds css files as having side effects
- LP storybook unbroken
- install `@chanzuckerberg/eds: 8.1.0-alpha.4` in LP, where `8.1.0-alpha.4` is the latest alpha publish off next
- in `traject/node_modules/@chanzuckerberg/eds/package.json` change `sideEffects: false` to 
```
"sideEffects": [
"lib/tokens/css/variables.css",
"lib/tokens/fonts.css"
]
```
- run `npm run storybook` and see that storybook is unbroken
- chromatic: https://www.chromatic.com/build?appId=614b969675171d003ac6f98a&number=16062
- alternatively install `8.1.0-alpha.5` which is alpha publish off of this branch
- chromatic: …
=> fix(build): add css as having side effects

.eslintrc, .storybook/pages/AlongDemo/AlongDemo.tsx, .storybook/pages/CoursePlannerEdit/CoursePlannerEdit.tsx, .storybook/pages/WireframeDemo/WireframeDemo.tsx, .storybook/recipes/NumberIconList/NumberIconList.stories.tsx, .storybook/recipes/PrimaryNav/PrimaryNav.stories.tsx, docs/CODE_GUIDELINES.md, src/components/Checkbox/Checkbox.stories.tsx, src/components/DragDrop/DragDrop.stories.tsx, src/components/Drawer/Drawer.tsx, src/components/Drawer/DrawerExample.tsx, src/components/Dropdown/Dropdown.stories.tsx, src/components/FiltersDrawer/FiltersDrawer.tsx, src/components/Modal/Modal.stories.tsx, src/components/Modal/Modal.test.tsx, src/components/Tag/Tag.stories.tsx, src/components/TimelineNav/TimelineNav.tsx, src/components/Tooltip/Tooltip.stories.tsx
- Just refactors `<Component prop={true}>` to just `<Component prop>` to match rest of repo 
- Lint warns on `react/jsx-boolean-value` for this 
- n/a
=> refactor: shorthand prop={true}

package.json, yarn.lock
- the `commit` script isn't working since `./node_modules/.bin/cz` doesn't exist
- this actually fixes the `commit` script and runs off our `commitlint.config.js` 
- if no one is using this script, I can also remove the devdep `@commitlint/prompt-cli`
- running `yarn commit` works
- if no one is using `yarn commit`, n/a
=> refactor(scripts): remove broken script

jest/jest.setup.ts, package.json, src/components/Icon/Icon.tsx, yarn.lock
Removes use of `svg4everybody`. It was brought over from BM to support rendering icon sprites in Internet Explorer, but:
- we don't support IE (and never did ... should have just removed this in the first place 🤦 )
- we also no longer use an svg spritemap for icons due to SSR
I was inspired seeing @jeremiah-clothier's PR for EDS jest config requirements in product apps and remembered we needed some mocking for this package
should be no visual changes
=> chore: remove usage of svg4everybody

src/components/Text/Text.stories.tsx, src/components/Text/Text.tsx
- deprecates the `as="div"` aka Text Passage variant of the Text component since its utility can be easily replicated with utility classes
- deprecates the `spacing` variants of the Text component since its utility can be easily replicated with utility classes, of which there are more options
- Text passage stories have the `deprecated` badge
- Text spacing story has the `deprecated` badge
- Text docstrings render fine in storybook
=> refactor(text): deprecate text passage and spacing variants

CHANGELOG.md, package.json
keeping `next` in sync with `main` for release v9 #1495
=> chore(release): 9.0.0

src/components/Badge/Badge.test.tsx
- suppresses expected console error that was missed previously
=> test(badge): suppress expected console error

src/components/TextArea/TextArea.module.css, src/components/TextArea/TextArea.tsx, src/components/TextArea/index.ts, src/components/TextareaField/TextareaField.module.css, src/components/TextareaField/TextareaField.stories.tsx, src/components/TextareaField/TextareaField.test.ts, src/components/TextareaField/TextareaField.tsx, src/components/TextareaField/__snapshots__/TextareaField.test.ts.snap, src/components/TextareaField/index.ts, src/design-tokens/mixins.css, src/index.ts
- create TextArea component
- for now exporting, but we would want to treat this similar to how we do the input base component
- will sync with latest design before merging
=> feat(TextareaField): add TextArea base component and TextareaField

src/components/Select/Select.stories.tsx, src/components/Select/__snapshots__/Select.test.tsx.snap
- add a new story for showing a value selected on component load
- update typing in story file for clarity
This is to ensure the behavior of selected values when using the component, as this was not previously covered in our wrapper
=> test(Select): add story for selected value

.prettierrc, prettier.config.js
Not sure if this was intended from #1457 or not, but it turns out we aren't actually using our shared prettier config. More deets inline.
This PR
- Fixes that so we're using prettier-config-edu.
- Introduces an override to avoid a large diff. We may want to remove this override at some point, though.
- Introduced prettier violations
- Observed prettier complaining/fixing
=> Use our shared prettier config

package.json, src/components/Slider/Slider.test.tsx, yarn.lock
- was getting a bunch of error messages about state updates not being wrapped in `act` after bump to v14
- reverts so these are gone 
- also sneaks in moving mocks to test blocks b/c for some reason those were logging error messages in the console too
https://github.com/testing-library/react-testing-library/issues/1180
=> Revert "chore(deps): bump @testing-library/react to v14 (#1515)"

docs/CONTRIBUTING.md
Add some extra details on how we'd like to approach breaking changes when they occur. This is to help with two aspects of developing on EDS:
- when to make breaking changes
- now to deal with release branches (already documented above these changes)
We can avoid most conflicts or delays in merging breaking changes by making use of our existing release branch process. 
- n/a
=> docs(Contributing): add clarity for approaching breaking changes

src/components/Checkbox/Checkbox.stories.tsx, src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap, src/components/CheckboxInput/CheckboxInput.module.css, src/components/CheckboxInput/CheckboxInput.test.tsx, src/components/CheckboxInput/CheckboxInput.tsx, src/util/useForwardedRef.test.tsx, src/util/useForwardedRef.ts
EFI-949
Breaking change! (although I'm not aware of any consumers affected by it)
- Give the Checkbox component separate `checked` and `indeterminate` props.
- Also makes `indeterminate` checkboxes officially indeterminate in the DOM.
Thought about this while working on #1511.
https://html.spec.whatwg.org/multipage/input.html#checkbox-state-(type=checkbox) calls out `indeterminate` as a separate piece of state than `checked`.
> The control is never a true tri-state control, even if the element's [indeterminate](https://html.spec.whatwg.org/multipage/input.html#dom-input-indeterminate) IDL attribute is set to true. The [indeterminate](https://html.spec.whatwg.org/multipage/input.html#dom-input-indeterminate) IDL attribute only gives the appearance of a third state.
Practically this means a …
=> feat!: split apart checkbox checked and indeterminate props

docs/COMPONENTS.md
- clarify documentation to reflect current Storybook structure (flattened component hierarchy)
=> docs(Components): update storybook component categorization docs

src/components/Breadcrumbs/Breadcrumbs.tsx
- with react 18, [useEffect fires synchronously before layout](https://github.com/reactjs/reactjs.org/blob/d14cbdca2445cd676526c4c52e1e106342ff7bb3/content/docs/hooks-reference.md?plain=1#L155) so can use useEffect over useLayoutEffect
=> refactor(breadcrumbs): use useEffect over useLayoutEffect

.github/workflows/docs.yml, .github/workflows/size-limit.yml, .github/workflows/test.yml
Was getting warnings about deprecations in ci jobs:
Bumps actions/checkout to v3 and commitlint-github-action to v5
- Deprecation messages now gone
- CI tests run without fail
=> ci: bump gh action checkout and commitlint

package.json, src/components/LoadingIndicator/LoadingIndicator.module.css, src/components/LoadingIndicator/LoadingIndicator.tsx, src/components/LoadingIndicator/__snapshots__/LoadingIndicator.test.ts.snap, yarn.lock
- we only have one particular loading indicator we want to use at this time
- apply styles and parameters to match previous implementation's output
- update the snapshots as needed. verify results are otherwise the same
- verify all existing tests pass
=> feat(LoadingIndicator): extract and use SVG animation directly

package.json, yarn.lock
- bumps storybook addon badges to v1
- with https://github.com/chanzuckerberg/edu-design-system/pull/1540 should get rid of `styled-components`
- Badges still render:
=> chore(deps): bump sb addon badges to v1

docs/COMPONENTS.md
- add instructions for creating new recipes
- update structure of page to sync section documentation
- clarify purpose of recipes in general, and how to contribute new recipes
- n/a (documentation updates)
=> docs(Components): clarify component and recipe documentation

src/components/Avatar/Avatar.stories.ts, src/components/Avatar/Avatar.tsx, src/components/Avatar/__snapshots__/Avatar.test.ts.snap
- mark ariaLabel prop as optional
- ensure labels are always generated via additional tests
=> fix(Avatar): loosen props for avatar aria-label component

.github/workflows/test.yml, package.json, tailwind.config.js
[EDS-813]
- dedupes words for TW utility classes
- in screenshot: 
- can see it's no longer `border-border-link-neutral` and simply `border-link-neutral`
- `bg-link-neutral` is not associated with any styles because `link-neutral` is border specific
- `bg-icon-neutral-default` is still applicable since `icon-neutral-default` is not bg/border/text specific
- grabs tokens from one file in `lib` instead of `src` since `lib` is part of EDS package
- purpose is so pilots can import eds tw config and use out of the box with only adding `content` property to config
- does not provide primary color tokens for use 
- Create an [alpha publish](https://github.com/chanzuckerberg/edu-design-system/blob/main/docs/PUBLISHING.md#alpha-release) and try out in `edu-stack` or `traject` as a sanity check if …
=> refactor(tailwind): configure tw config for export

.storybook/recipes/PrimaryNav/PrimaryNav.module.css, .storybook/recipes/PrimaryNav/PrimaryNav.stories.tsx, src/components/Breadcrumbs/Breadcrumbs.module.css, src/components/BreadcrumbsItem/BreadcrumbsItem.module.css, src/components/DropdownMenu/DropdownMenu.module.css, src/components/Modal/Modal.module.css, src/components/PageHeader/PageHeader.module.css, src/components/Tabs/Tabs.module.css, src/components/TimelineNav/TimelineNav.module.css, src/components/Toast/Toast.module.css, src/design-tokens/mixins.css
[EDS-835]
- removes reset mixin which is duplicative of tailwind preflight 
- also removes resetAll mixin which was never used
- No visual regression expected
- Checked on storybook of changed stories and saw that the styles were being applied from preflight after removing
[EDS-835]: https://czi-tech.atlassian.net/browse/EDS-835?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: remove unused unnecessary resets

docs/PUBLISHING.md
make use of the updated repository config to release without creating unsynced merge commits
- n/a
=> docs: update release docs to prevent orphaned merge commits

src/components/Button/Button.module.css, src/components/Button/Button.tsx, src/components/Button/__snapshots__/Button.test.tsx.snap
- replace the inline icon (loading) with our <LoadingIndicator />
- remove custom animation as well
- update snapshots to account for this
- don't use the visible prop, as this breaks ARIA for buttons
- mark `loading` as deprecated (we will direct people and designers to compose instead, like we do with icons)
=> feat(Button): use LoadingIndicator for loading state

src/components/Checkbox/Checkbox.test.tsx, src/components/Checkbox/Checkbox.tsx, src/components/InputField/InputField.tsx, src/components/Radio/Radio.test.tsx, src/components/Radio/Radio.tsx, src/components/Slider/Slider.test.tsx, src/components/Slider/Slider.tsx, src/components/TextareaField/TextareaField.tsx, src/components/Toggle/Toggle.tsx, src/util/utility-types.ts
- we have a chunk of boilerplate code for checking labels on some components. since the text was the same from component to component, there was some confusion on which component was causing the error. use types to assert the needed props (1 of 2 labeling props as necessary), and document this in the intellisense popups as a component note
- existing test suite with language updates
=> feat: add utility types to enforce either label or aria-label 

.storybook/recipes/MenuWithIconButton.stories.tsx
Storybook 7.0 deprecates using argTypes.$propName.defaultValue to infer what control value to select. Use the migration guide to fix up the cases in EDS that violate that (just one).
- Verify the vertical dots icon is selected when refreshing story "?path=/docs/recipes-menuwithiconbutton--with-vertical-dots-button"
=> docs: use args.defaultValue instead of argTypes.prop.defaultValue

.storybook/recipes/MenuWithAvatarButton.stories.tsx, src/components/Menu/Menu.module.css
- icons and other items within .PlainButton should be centered
- add recipe showing use of menu with Avatar component
- adding new snapshot for avatar story in `Menu`
=> feat(Menu): update centering with plain button

docs/PUBLISHING.md
- make sure to advise eng to refer to the documentation on `next`
- code snippet formatting
- add step to wait on builds to main to complete
=> docs: update publishing docs post-release

package.json
In #1568 I converted the `tailwind.config.js` to typescript, but forgot to update the `files` entry to include the TS version in the package 😐.
So now consuming apps can no longer access the EDS tailwind config to get theme variables.
This PR fixes that.
- `npm publish --dry-run`
=> fix: include tailwind config in package

src/components/TextareaField/TextareaField.module.css, src/components/TextareaField/TextareaField.stories.tsx, src/components/TextareaField/TextareaField.tsx, src/components/TextareaField/__snapshots__/TextareaField.test.ts.snap
- only shows up if max length is specified
- turns red if the default value is greater than allowed
- updates as you type
- currently no warning color as you approach limit
- by default textareas do not allow entry above maxlength
- but you can delete if somehow above maxlength
- field not in error state when above max length
- review snapshot / chromatic changes
=> feat(TextareaField): add character length counter

src/components/Checkbox/Checkbox.tsx, src/components/InputField/InputField.tsx, src/components/TextareaField/TextareaField.tsx, src/util/utility-types.ts
[EDS-893]
- with upcoming conditional exports of EDS, we have to be explicit about what we want to export
- this adds subcomponents of `InputField`, `TextareaField`, and `Checkbox` to their respective parent components as object values
- adds `ForwardedRefComponent` type, which is the return type of `forwardRef` to make this possible
[EDS-893]: https://czi-tech.atlassian.net/browse/EDS-893?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: export some subcomponents

src/components/Popover/Popover.test.tsx
- re #1389 , remove an old and redundant test. `getElement` already verifies you can attach to the element from the trigger
-  verify all tests continue passing (no dependency on this test)
=> test(Popover): remove redundant test

.storybook/recipes/CardWithNotification/CardWithNotification.stories.tsx, src/components/Accordion/Accordion.stories.tsx, src/components/Badge/Badge.stories.tsx, src/components/Breadcrumbs/Breadcrumbs.stories.tsx, src/components/ButtonDropdown/ButtonDropdown.stories.tsx, src/components/ButtonGroup/ButtonGroup.stories.tsx, src/components/DragDrop/DragDrop.stories.tsx, src/components/Drawer/Drawer.stories.tsx, src/components/DropdownMenu/DropdownMenu.stories.tsx, src/components/Fieldset/Fieldset.stories.tsx, src/components/FiltersDrawer/FiltersDrawer.stories.tsx, src/components/FiltersPopover/FiltersPopover.stories.tsx, src/components/Grid/Grid.stories.tsx, src/components/Layout/Layout.stories.tsx, src/components/LayoutContainer/LayoutContainer.stories.tsx, src/components/LayoutLinelengthContainer/LayoutLinelengthContainer.stories.tsx, src/components/Menu/Menu.stories.tsx, src/components/Modal/Modal.stories.tsx, src/components/PageLevelBanner/PageLevelBanner.stories.tsx, src/components/Popover/Popover.stories.tsx, src/components/SearchBar/SearchBar.stories.tsx, src/components/Table/Table.stories.tsx, src/components/Tabs/Tabs.stories.tsx, src/components/TimelineNav/TimelineNav.stories.tsx, src/components/Toolbar/Toolbar.stories.tsx, src/components/Tooltip/Tooltip.stories.tsx
Storybook is showing stringified versions of some of the components' `children` and other props. Trying to edit any of these will break the storybook UI and require a page refresh. This disables those ones in the controls, which appears not to be a global option.
- n/a (only affects storybook)
=> docs: hide non-functional children controls in stories

.storybook/pages/AlongDemo/AlongDemo.tsx, .storybook/pages/WireframeDemo/WireframeDemo.tsx, docs/CODE_GUIDELINES.md, package.json, src/components/Checkbox/Checkbox.tsx, src/components/DataBar/DataBar.tsx, src/components/FiltersDrawer/FiltersDrawer.tsx, src/components/InputField/InputField.tsx, src/components/ProgressBar/ProgressBar.tsx, src/components/Radio/Radio.tsx, src/components/Slider/Slider.tsx, src/components/Tabs/Tabs.tsx, src/components/TextareaField/TextareaField.stories.tsx, src/components/TextareaField/TextareaField.tsx, src/components/TimelineNav/TimelineNav.tsx, src/util/useId.ts, yarn.lock
- attempts to polyfill useid for react <18 with incremental numbers
- uses default React.useId from react 18 if exists
- polyfill is not ssr safe since it's generated upon usage, which is render timing dependent
- prefixes with `eds-` to avoid collision with other number id's if number id's are used elsewhere
- `12.0.1-alpha.1` created and tested in https://github.com/chanzuckerberg/along/pull/5942
=> fix: polyfill for useid for react <18

src/components/TextareaField/TextareaField.stories.tsx, src/components/TextareaField/__snapshots__/TextareaField.test.ts.snap, src/util/useId.ts
- move the `console.warn` inside the function usage ~(TODO: consider deduping its output)~
- use proper camelCase prop name in textarea tests
=> fix: suppress warnings from useId imports and prop usage

.storybook/data/tokens.json, src/tokens-dist/css/variables.css, src/tokens-dist/json/variables-nested.json
- somehow these values weren't part of any commit
- add them in now
- (note: all build releases run agains a build, including these changes)
=> fix: add missing token updates

src/design-tokens/external-fonts.css, src/design-tokens/tier-1-definitions/fonts.css, src/index.ts
- removing the font import from mixins caused Open Sans to stop appearing in storybook
- similar to Graphik, we should import the fonts from our fonts.css file
- existing instructions won't need changing, as they specify using this file already (README, storybook, etc.)
I think our Chromatic setting to do TurboSnaps meant that it didn't detect this change as a snapshot diff, so there was no clue the font had disappeared :( 
Busted snapshots start appearing later: #1613, #1614 
More long term, we should revisit [getting fonts from google anyway](https://wpspeedmatters.com/self-host-google-fonts/)
- verify lib/ contents are correct:
- no import lines in index.css
- import for google font in fonts.css
- no snapshot updates for typography page
=> fix: group all font imports together

src/components/Menu/Menu.module.css, src/components/Select/Select.module.css
- for menu, it was falling back to an incorrect, tho similar, color value
- for select, it was inheriting the correct hex value b/c the specific theme value was not defined
Following the naming conventions defined in [this file][variables-link]
[variables-link]: https://github.com/chanzuckerberg/edu-design-system/blob/main/src/tokens-dist/css/variables.css#L203
=> fix: correct misspelled color token names

.storybook/components/DesignTokens/Tier2/Colors.jsx, .storybook/components/DesignTokens/Tier2/Forms.jsx, .storybook/components/DesignTokens/Tier3/Colors.jsx, .storybook/components/DesignTokens/Tier3/Sizes.jsx, .storybook/components/DesignTokens/Tier3/Tier3Tokens.stories.jsx, .storybook/components/Docs/Guildelines/Tokens.stories.mdx
- remove outdated or non-existent token categorization
- update token tiers to highlight tier 3 tokens
- update existing token pages to separate different tiered tokens
- other small updates to language around tokens
For ease of reviewing, refer to attached screenshots, and review snapshot and storybook in the build info below.
- review and matched token documentation to make sure all non-legacy tokens were accounted for from https://github.com/chanzuckerberg/edu-design-system/blob/main/src/tokens-dist/css/variables.css
=> docs: align token documentation to token code

package.json, src/components/Input/Input.tsx, src/components/InputField/InputField.tsx
[EFI-1103]
- builds declaration files separately since with the typescript rollup config the files exporting only types get pruned 
- `v12.0.4-alpha.1`: ![Screenshot 2023-05-24 at 11 18 33 PM](https://github.com/chanzuckerberg/edu-design-system/assets/86632227/22f29336-22ec-4698-a6da-8d9250665c9a) shows the `onChange` type being inherited properly and can navigate `node_modules/eds` to find the missing utility types in `edu-stack`
- …
=> fix(build): build type declarations separately

src/components/TextareaField/TextareaField.stories.tsx, src/components/TextareaField/TextareaField.test.ts, src/components/TextareaField/TextareaField.test.tsx, src/components/TextareaField/__snapshots__/TextareaField.test.tsx.snap
- remove storybook test which was printing a console statement
- instead, add a jest test for the component with content and without
- use expect statements to make sure the mock function is called
=> test(TextareaField): add better custom event handler tests

.storybook/pages/AlongDemo/AlongDemo.module.css, .storybook/pages/AlongDemo/AlongDemo.tsx, .storybook/pages/WireframeDemo/WireframeDemo.tsx, src/components/Select/Select.stories.tsx, src/components/Select/Select.tsx
- uses Select component over old deprecated Dropdown component in the Along demo and Wireframe demo pages
- this removes usage of the old Dropdown component in the repo (except in its respective story file)
- not to be confused with the ButtonDropdown component which is tied to the DropdownMenu component (confusing, I know)
-  select is interact-ible and looks similar to the Dropdown it's replacing in the story
=> refactor: use select over deprecated dropdown in demos

.storybook/pages/CoursePlannerEdit/CoursePlannerEdit.module.css, .storybook/pages/CoursePlannerEdit/CoursePlannerEdit.tsx, .storybook/pages/CoursePlannerEdit/ProjectCard/ProjectCard.tsx
[EDS-1002]
- uses the supported Menu component over the deprecated ButtonDropdown/DropdownMenu component
- along with #1646 completes removal of usage of the deprecated ButtonDropdown/DropdownMenu component to be set for removal
- The project cards in the course planner edit page in storybook has working menu functionality
[EDS-1002]: https://czi-tech.atlassian.net/browse/EDS-1002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor(projectcard): use menu component over buttondropdown

src/components/Input/Input.tsx
Allow all valid input type attributes.
Needed so the type `conform.input` returns matches EDS's. Without this, we run into type errors with the latest version of React's types -> https://github.com/chanzuckerberg/edu-stack/pull/129/files#r1215506643
=> fix: allow all valid input types

src/components/Breadcrumbs/Breadcrumbs.stories.tsx, src/components/Breadcrumbs/Breadcrumbs.tsx, src/components/BreadcrumbsItem/BreadcrumbsItem.module.css, src/components/BreadcrumbsItem/BreadcrumbsItem.tsx
[EFI-1002]
- uses the supported Menu component over the deprecated ButtonDropdown/DropdownMenu component
- #1647 removes old ButtonDropdown use in the recipes/pages
- Ellipsis breadcrumbs works with the links in Storybook
[EDS-1002]: https://czi-tech.atlassian.net/browse/EDS-1002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[EFI-1002]: https://czi-tech.atlassian.net/browse/EFI-1002?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor(breadcrumbs): use menu over deprecated buttondropdown

.storybook/components/DesignTokens/Tier2/TypographyUsage.jsx, src/components/Text/Text.module.css, src/components/Text/Text.tsx, src/components/Tooltip/Tooltip.stories.tsx, src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
- [feat(Text): add support for caption-md and caption-lg](https://github.com/chanzuckerberg/edu-design-system/commit/53fd4e04ea1845d614b505ef1da25d288b13543f)
- [fix(Tooltip): use caption-lg for tooltip text](https://github.com/chanzuckerberg/edu-design-system/commit/f0772c7e148051fd3c3b16af874bcb74831e1b4f)
- review chromatic diffs to make sure they comply with design
=> feat(Text): add support for caption-md and caption-lg

src/components/Menu/Menu.tsx, src/components/Popover/Popover.tsx, src/components/Select/Select.tsx
- wraps `createportal` used in the Menu, Popover, and Select components in a conditional checking for `window`
- tested working with v12.2.0-alpha.2 release on running edu-stack locally
- tried wrapping `document.body` in `useEffect` but still got ssr errors
=> fix: make menu, popover, select ssr friendly

README.md
- change link from old markdown files to new storybook pages (MDX-based markdown files)
- n/a
=> docs: point to published storybook in readme

.storybook/pages/FeedbackOverview/FeedbackOverview.tsx, .storybook/pages/ProjectOverview/ProjectOverview.tsx, src/components/Breadcrumbs/Breadcrumbs.stories.tsx, src/components/Breadcrumbs/Breadcrumbs.tsx, src/components/Breadcrumbs/__snapshots__/Breadcrumbs.test.tsx.snap, src/components/BreadcrumbsItem/BreadcrumbsItem.tsx
[EDS-922]
- allows separator string to be passed to parent <Breadcrumb> wrapper for <BreadcrumbItems>
- follows similar code pattern in Modal, Popover, etc of using React Context to pass parent prop to children components
- no longer references uses to <BreadcrumbItems> children components and instead to <Breadcrumb.Items> which has the modified <BreadcrumbItems> with the context
smallest breakpoint no separator, so stays same:
- new story with 3 viewports for visual regression testing
[EDS-922]: https://czi-tech.atlassian.net/browse/EDS-922?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(breadcrumbs): allow custom separators

.storybook/data/tokens.json, src/design-tokens/tier-2-usage/colors-background.json, src/tokens-dist/css/variables.css, src/tokens-dist/json/variables-nested.json, src/tokens-dist/ts/colors.ts
[EDS-1042]
- adds t2 color token background/brand-primary-subtle
- along request and adds a subtle token for background-brand-primary
- currently maps to grape-100 which is same as background-brand-primary-default but it's the lightest grape we have and not using internally or in SLP theme so for use in products only and they can map the default / subtle to different colors for their own use as said by design team
[EDS-1042]: https://czi-tech.atlassian.net/browse/EDS-1042?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(tokens): add t2 color bg-brand-primary-subtle

src/components/Tooltip/Tooltip.stories.tsx
- just marks the tooltip stories as needing revision as it needs design revision, is marked as so in ZH, and is not SSH friendly
=> refactor(tooltip): mark as needing revision

.storybook/pages/WireframeDemo/GlobalStyles.module.css, CHANGELOG.md, README.md, package.json, src/components/Badge/Badge.module.css, src/components/ClickableStyle/ClickableStyle.module.css, src/components/DataBar/DataBar.module.css, src/components/DataBarSegment/DataBarSegment.module.css, src/components/Menu/Menu.module.css, src/components/NumberIcon/NumberIcon.module.css, src/components/Skeleton/Skeleton.module.css, src/components/Slider/Slider.module.css, src/components/Tag/Tag.module.css, src/design-tokens/mixins.css
- when a `var()` property spans multiple lines, it will insert that directly into the CSS, which won't read the token
- for some components (mainly `ClickableStyle`) this caused bugs in the values used in the styling
- update the code to remove these, and add a few `/* prettier-ignore */` declarations to lines that are too long to fit into the prettier rules
- Validate any snapshot changes
=> fix: make sure all var properties exist on one line

src/components/Layout/Layout.stories.tsx, src/components/Layout/Layout.tsx, src/components/LayoutContainer/LayoutContainer.stories.tsx, src/components/LayoutContainer/LayoutContainer.tsx, src/components/LayoutLinelengthContainer/LayoutLinelengthContainer.stories.tsx, src/components/LayoutLinelengthContainer/LayoutLinelengthContainer.tsx, src/components/LayoutSection/LayoutSection.tsx
- point users of the components to use tailwind CSS instead
- n/a (no component changes)
- verify that built storybook adds the "Deprecated" badge to the right pages
=> feat(Layout): mark layout components as deprecated

src/components/InputField/InputField.module.css, src/components/InputField/InputField.tsx, src/components/InputField/__snapshots__/InputField.test.ts.snap
[EFI-1228]
- after some discussion we're keeping `Input` component as its not a subcomponent for just `InputField` and possibly has use as utility component in other areas
- using `InputLabel` component over `Label` component be in line with `Checkbox` and `Radio`
- aligns closer to the mocks for font
[EFI-1228]: https://czi-tech.atlassian.net/browse/EFI-1228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor(inputfield): use inputlabel and re-export as subcomp

src/components/Modal/Modal.tsx
- Link to relevant HeadlessUI documentation
- Add recommendations for how to use with inline examples
- Typo and other documentation improvements
- n/a (only documentation changes)
=> docs(Modal): add clarity on how to use open prop

.storybook/components/Docs/Guidelines/Theming.stories.mdx, .storybook/pages/WireframeDemo/WireframeDemo.tsx
This is some leftover cleanup after removing the along theme example from the codebase.
=> docs: remove references to along themed demo

.omletrc.json
this prevents bifurcation of components so that it doesn't confuse built versions with their typescript equivalents
- validate scan result using `--dry-run`
=> chore(omlet): only scan components in src directory

.storybook/components/Docs/Guidelines/Layout.stories.mdx, src/design-tokens/tier-1-definitions/layout.json, src/tokens-dist/css/variables.css
- remove Grid and Layout component examples
- add deprecation warning
- provide useful links to tailwind documentation
=> docs: point Layout storybook to Zeroheight

src/components/Accordion/Accordion.stories.tsx, src/components/Checkbox/Checkbox.stories.tsx, src/components/DataBar/DataBar.stories.tsx, src/components/FiltersDrawer/FiltersDrawer.stories.tsx, src/components/InputField/InputField.stories.tsx, src/components/Select/Select.stories.tsx, src/components/Table/Table.stories.tsx, src/components/Toggle/Toggle.stories.tsx
[EDS-1074]
- found some [documentation](https://storybook.js.org/docs/react/api/doc-block-source#type) on how to show the code more properly with the docs addon: 
- `parameters: {docs: {source: 'dynamic'}}` renders the story source with dynamically updated arg values, allowing stories with `render` functions to show the code
- `parameters: {docs: {code: '*code string*'}}` allows custom code to be shown
- addresses Along want for "Show Code" working for Sortable Interactive story for the Table component
- Makes "Show Code" working for some more components
- stories used for visual regression only were not addressed
- "Show Code" in docs addon shows code
[EDS-1074]: https://czi-tech.atlassian.net/browse/EDS-1074?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLW …
=> docs: show more code in component stories docs

src/components/Avatar/Avatar.module.css, src/components/Avatar/Avatar.stories.ts, src/components/Avatar/Avatar.tsx, src/components/Avatar/__snapshots__/Avatar.test.ts.snap
- add new prop for display name to allow for avatar text not based on the user's real name
- add tests for sensible fallbacks when using this component
=> fix(Avatar): support display names using emoji and multi-byte

docs/PUBLISHING.md
it's possible to hotfix an older version of EDS. in those cases, we don't necessarily want to merge back into `main`. add a note explaining this situation (which should be rare). Also diminish the hotfix instructions so that the document is easier to follow at a glance.
- n/a (documentation only changes)
=> docs: clarify hotfix release process

src/util/useId.ts
This updates the emitted warning message when using the built-in fallback for `useId` in react < 18 projects. Includes a recommendation as well.
- n/a (documentation only change)
=> docs: add clearer warning and recommendation for useId

package.json, src/components/Avatar/Avatar.test.ts, src/components/Avatar/Avatar.tsx, yarn.lock
use [Graphemer](https://github.com/flmnt/graphemer) to:
- add handling for unicode surrogate pairs (mark1)
- handling for extended BMP (Basic Multilingual Plane) characters
=> fix(Avatar): improve support for generating initials

docs/PUBLISHING.md
- add in **brief** breaking change instructions based on what we did for the release of version 13. Covers example to follow, with some notes on which features to apply in those cases. 
=> docs: include steps on documenting breaking change(s)

src/components/Tabs/Tabs.test.tsx, src/components/Tabs/Tabs.tsx, src/components/Tabs/__snapshots__/Tabs.test.tsx.snap
Noted in https://czi-edu.slack.com/archives/CTFV79JH4/p1693505461086869, we're generating invalid ids for tabs. Here we fix that.
=> Generate valid tab ids

package.json
- fix warning in the `start` and `storybook` commands for redundant path 
- make sure no build errors occur
- verify development environment still loads font files
- verify no snapshots change w.r.t. font files
=> chore: remove static directive from dev script

src/components/Menu/Menu.stories.tsx
- this is to help prevent storybook flakiness. The menu opens but for a brief moment, it will be in a repositioning state, which causes it to slip left and right on some snapshots.
- re-run chromatic a few times with this delay to see if that prevents the snapshot from changing
=> chore(Menu): add chromatic delay to interactive story

.eslintrc, .storybook/main.ts
I noticed that classnames are hashed while working on #1742. This makes finding the origin of styles in the codebase harder and is straightforward to toggle off via webpack.
**Before:**
**After:**
=> chore: make `.module.css` class names human readable in local development

rollup.config.mjs
This PR attempts (still needs to be verified) to fix a weird issue in Along with EDS's dependency with Graphemer (same thing #1745 is fixing).
Here we tell Rollup to explicitly add an es module compatibility layer to the CJS build, just like TS does.
=> TS module interop

docs/PUBLISHING.md
When performing a regular release, I noticed it only published to GH registry when it used to publish to NPM at the CLI. It was related to a new line added to my `~/.npmrc` after testing an alpha version. This adds doc.s to explain this may happen. 
- n/a (documentation-only change
=> docs: add clarification on alpha publishing process

.storybook/pages/WireframeDemo/GlobalStyles.module.css
we deprecated these inconsistent tokens from the library, but they were remaining in the page demo. Remove them to avoid any confusion
- make sure no snapshots change
=> fix: remove deprected tokens

.vscode/launch.json
Found that i had this config for running the debugger when using `jest`, which enables stepping thru code to discover the problems. add as an option for anyone working on EDS.
- n/a (developer-only config update)
=> chore: add launch.json config for debugging

README.md
Add a small block of text to describe how to enable this nice DX improvement.
=> docs: add instructions for CSS var. autocomplete

src/components/Select/Select.stories.tsx, src/components/Select/Select.test.tsx, src/components/Select/Select.tsx
There have been a few recent cases where `Select` presented problems for consumers. Namely, certain frameworks expect a form field to appear so that data can be submitted (no pun intended). This is an important behavior, and luckily HeadlessUI supports this in the underlying [`Listbox`](https://headlessui.com/react/listbox#listbox) component.
Add some documentation to explain this, and a dev-time warning to double-down on the recommendation. In the future, `name` may be a required prop when using any/all form elements.
- Create an [alpha publish](https://github.com/chanzuckerberg/edu-design-system/blob/main/docs/PUBLISHING.md#alpha-release) and try out in `edu-stack` or `traject` as a sanity check if changes affect build or deploy, or are breaking, such as token changes, widely used …
=> feat(Select): add warning when name is missing from component props

src/components/Accordion/Accordion.stories.tsx, src/components/Accordion/Accordion.tsx, src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
testing added to show how the `data-testid` props work on `Accordion`. Also include an example showing how they can render based on `AccordionRow` state.
Add link to documentation for [`Disclosure`](https://headlessui.com/react/disclosure) from HeadlessUI.
=> docs(Accordion): add tests revealing passing of data- props

src/components/Accordion/Accordion.stories.tsx, src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
Test and document compositions using `Accordion`, `Icon`, and `Text` to customize headers.
=> docs(Accordion): add implementation example for accordion, icon, text

src/components/Accordion/Accordion.module.css, src/components/Accordion/Accordion.stories.tsx, src/components/Accordion/Accordion.test.tsx, src/components/Accordion/Accordion.tsx, src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
- adding an `isExpandable={false}` to an `AccordianRow` will hide the feature that afford clicking
- add tests to verify this behavior
- add new snapshots
=> feat(Accordion): allow empty or hidden accordion rows

src/components/TextareaField/TextareaField.stories.tsx, src/components/TextareaField/TextareaField.test.tsx, src/components/TextareaField/TextareaField.tsx, src/components/TextareaField/__snapshots__/TextareaField.test.tsx.snap
- new prop `recommendedLength` allows for showing an error but letting the user continue typing content
- `maxLength` still works, and can be a different (larger or equal) value
- update snapshots and tests
=> feat(TextareaField): support recommendedMaxLength prop for display-only errors

src/components/Badge/Badge.stories.tsx, src/components/InputField/InputField.module.css, src/components/InputField/InputField.stories.tsx, src/components/InputField/InputField.test.tsx, src/components/InputField/InputField.tsx, src/components/InputField/__snapshots__/InputField.test.tsx.snap, src/components/TextareaField/TextareaField.tsx, src/util/getMinValue.test.ts, src/util/getMinValue.ts
- allow handling for `maxlength` and `recommendedMaxLength` like TextareaField
- update snapshots and tests
=> feat(InputField): support recommendedMaxLength prop for display-only errors

src/components/Text/Text.stories.tsx, src/components/Text/__snapshots__/Text.test.tsx.snap, tailwind.config.ts
expose more tokens used in EDS to tailwind, to allow for utility classes for the preconfigured font families, or for any custom font families added by consumers. Can be used in isolation like `font-primary` or `font-secondary`, or as an occasional override to any typography components like `Heading` or `Text`.
- add the example config to tailwind.config.js with brief documentation
- add example to Text component
=> feat(Tailwind): add config to expose primary and secondary fonts

src/components/Menu/Menu.stories.tsx
Attempt nr. 2 at making the open menu test less flaky. Add a delay to the user event that triggers the open menu. 
Trying this, as the snapshot likely happens right after the event completes, when the positioning library is calculating the final location and width of the popover. 
=> test(Menu): add delay to menu open user event trigger

src/components/Menu/Menu.stories.tsx, src/components/Menu/Menu.test.tsx, src/components/Menu/Menu.tsx
Remove this artificial constraint on `Menu.Item` components so that additional behavior can be attached to menu items along with an `href` with `onClick`. Like with an `<a>`, it will be up to the consumer to avoid undesired behavior.
=> feat(Menu): allow href and onClick to co-exist on a menu item

src/components/Popover/Popover.stories.tsx, src/components/Popover/Popover.tsx, src/components/Popover/__snapshots__/Popover.test.tsx.snap
Merge in the props from [HeadlessUI](https://headlessui.com/react/popover#popover-panel) for the panel, to support `focus`. This allows consumers to send focus to a particular piece of content within the content container. `onFocus` also allows for hooking into the internals in case there are some arguments to trigger upon focus.
=> feat(Popover): allow focus upon popover panel open

src/components/Accordion/Accordion.module.css, src/components/Accordion/Accordion.stories.tsx, src/components/Accordion/__snapshots__/Accordion.test.tsx.snap
- set a constant size for the state caret
- allow text to roll over to multiple lines
- add snapshots to test rollover behavior
=> fix(Accordion): handle multi-line text in headers

package.json, src/components/Accordion/Accordion.test.tsx, src/components/DataBar/DataBar.test.tsx, src/components/Drawer/Drawer.test.tsx, src/components/FiltersDrawer/FiltersDrawer.test.tsx, src/components/FiltersPopover/FiltersPopover.test.tsx, src/components/InputField/InputField.test.tsx, src/components/Menu/Menu.test.tsx, src/components/Modal/Modal.test.tsx, src/components/Popover/Popover.test.tsx, src/components/Radio/Radio.test.tsx, src/components/Select/Select.test.tsx, src/components/Tabs/Tabs.test.tsx, src/components/TextareaField/TextareaField.test.tsx, yarn.lock
re: https://github.com/testing-library/user-event/issues/1104#issuecomment-1759110918 update version of testing-library for react to latest major v14.
After validating stable tests, try removing/reducing calls to `act()` that might now be superfluous.
- validate build with existing `act()` tests
- validate build after removing some superfluous `act()` calls in test
=> chore: upgrade testing-library/react to v14

.omletrc.json
- add TS and TSX files to `include`
- make sure `exports` is defined to mark the package entry point
- confirm package analytics match expectations
- n/a (dev-only change affecting component analytics)
=> chore: update omlet config

src/components/Select/Select.stories.tsx, src/components/Select/Select.test.tsx, src/components/Select/Select.tsx
- add in `name` prop to sharedProps
- add test to ensure prop causes hidden input to be generated
- improvements to documentation in uncontrolled components
=> fix(Select): ensure name prop gets to Listbox

src/components/Modal/Modal.test.tsx, src/components/Modal/__snapshots__/Modal.test.tsx.snap
Noticed [some flakiness with the Modal's interactive examples tests](https://github.com/chanzuckerberg/edu-design-system/actions/runs/6788858470/job/18454751418). Fixed here by adding a small delay.
Alternatively could try to wait for a specific class. But I don't think there's a good one. The classes in question seem to be generated, and I don't want to rely on them.
=> chore: add a bit of delay to reduce Modal test flakiness

package.json, yarn.lock
Update Rollup to v4.
Tested by running `yarn build`, looking at the lib/ dir, and linking into edu-stack and running it there.
=> chore: update rollup to v4

src/components/Tag/Tag.stories.tsx, src/components/Tag/Tag.tsx, src/components/Tag/__snapshots__/Tag.test.ts.snap
- After syncing with design, will remove this variant from the component, and lean toward `warning` instead
- update corresponding snapshots
=> feat(Tag): mark yield color variant as deprecated

.storybook/main.ts, package.json, yarn.lock
The docs addon comes pre-installed with storybook 7.x, so we don't need to install it or configure it directly. This clears up that duplicate install and use (which also cleans up some small output from the console when starting storybook. Slightly quicker now.
As it's now pre-installed, we also don't have to worry about keeping it up to date anymore.
- verify the "Docs" tab works normally on build in CI
=> fix: remove duplicate addon-docs loading

src/components/DragDrop/DragDrop.stories.tsx, src/components/DragDrop/DragDrop.tsx, src/components/DragDrop/__snapshots__/DragDrop.test.ts.snap
- in its current form, it is far too application-specific to be generally usable
- also, the underlying library is now deprecated and no longer supported
- marking this as not recommended for current use, to move on to another codebase
- n/a (component metadata change)
=> chore(DragDrop): mark component as deprecated

src/components/Select/Select.stories.tsx, src/components/Select/Select.tsx, src/components/Select/__snapshots__/Select.test.tsx.snap
- add in proper description for generated form fields based on key/value info
- hide a field from the documentation table that is currently non-fuctional
=> fix(Select): update incorrect documentation

src/components/Avatar/Avatar.module.css, src/components/Avatar/Avatar.tsx, src/components/Avatar/__snapshots__/Avatar.test.ts.snap
- use typography token values from design
- scale icons at 80 percent of size value, centered vertically and horizontally
=> feat(Avatar): adjust typography usages and sizing for icons

src/components/InputField/InputField.tsx, src/components/InputLabel/InputLabel.stories.ts, src/components/Label/Label.tsx
- this was leftover from some previous factoring
- this behavior is not available in design, so marking to remove
=> fix(InputField): mark unused prop as deprecated

src/components/Label/Label.stories.ts, src/components/Label/Label.tsx, src/components/Label/__snapshots__/Label.test.ts.snap
- optional text should not appear next to the label
- remove any stories or docs demonstrating this behavior
=> feat(Label): mark optional as deprecated

.storybook/components/Docs/GettingStarted.stories.mdx, .storybook/components/Docs/Guidelines/CodeGuidelines.stories.mdx, .storybook/components/Docs/Guidelines/Theming.stories.mdx, .storybook/components/Docs/Guidelines/Tokens.stories.mdx, README.md
- remove the detailed instructions for setting up tailwind in README.md
- move this instead to the Theming documentation, along with other related setup
- clean up the references to this content to better align with the new structure in Theming.mdx
=> docs(Theming): update details on using theming tooling and tailwind config

src/components/Select/Select.module.css, src/components/Select/Select.stories.tsx, src/components/Select/Select.test.tsx, src/components/Select/Select.tsx, src/components/Select/__snapshots__/Select.test.tsx.snap
- provide a cleaner API for implementing the label similar to other form fields
- add disabled prop should a user want to still detach and use Select.Label
- update styles to support this
- docs: clean up all Select stories and API table in storybook
- docs: greatly simplify the presentation of Select documentation
- update relevant snapshots
=> feat(Select): add support for label prop

src/components/Select/Select.tsx
- when a button is in a form tag, it automatically becomes able to submit
- our wrapper doesn't include this which is usually fine
- sometimes during a slow load, the handler preventing propagation allows submit
- fixing this by adding a non-editable type
- verify trigger buttons include type in snapshots
=> fix(Select): set trigger type to button to prevent submits

.github/workflows/test.yml
Our usage of `wagoid/commitlint-github-action@v5` is causing upgrade to commitlint 18.6.0 to fail (source: https://github.com/chanzuckerberg/edu-design-system/actions/runs/7847650438/job/21417042874?pr=1841). I'm updating the workflow to use own implementation that way we aren't held back from updating libraries.
https://czi-tech.atlassian.net/browse/EFI-1617
=> ci: replace commitlint action with our own implementation

CHANGELOG.md, package.json, src/components/PopoverListItem/PopoverListItem.module.css, src/components/PopoverListItem/PopoverListItem.tsx, src/components/Select/Select.module.css, src/components/Select/Select.stories.tsx, src/components/Select/Select.tsx, src/components/Select/__snapshots__/Select.test.tsx.snap
- loosen types to be based more closely match HeadlessUI
- add story for multi select
- update styles for selected and unselected items
- remove need for SelectOption
=> feat(Select): enable multi-select

.eslintrc, src/components/Breadcrumbs/Breadcrumbs.tsx, src/components/Icon/Icon.stories.tsx, src/components/Table/Filters.tsx, src/components/Table/StackedCardsToTable.tsx, src/components/Tabs/Tabs.tsx
This PR updates our usage of Lodash so that we replace named imports
```ts
import {at} from 'lodash';
```
with deep ones
```ts
import at from 'lodash/at';
```
This should help tree shaking work better. I don't think this is a problem in our existing Remix apps (tree shaking works properly), but I'm running into an issue when trying to use ESM modules in Remix apps.
---
Alternatives:
- Use `lodash-es` instead (which is esm). Downside of that is we'd need to have our existing Remix apps pre-bundle lodash so that it's cjs.
- Maybe there's some Vite config I'm missing to make this work
=> Lodash tree shaking

src/components/InputField/InputField.module.css, src/components/InputField/InputField.tsx, src/components/InputField/__snapshots__/InputField.test.tsx.snap, src/components/Select/Select.module.css, src/components/Select/Select.stories.tsx, src/components/Select/Select.test.tsx, src/components/Select/Select.tsx, src/components/Select/__snapshots__/Select.test.tsx.snap
- model it to work and look like what exists for InputField
- add tests and new snapshots
=> feat(Select): add support for required in overline

src/index.ts
Export `ClickableStyleProps` from the top-level `index.ts`.
Usages in our Remix apps won't need to deeply import anymore (in fact, they can't with Vite due to how module resolution works)
```diff
- import type {ClickableStyleProps} from '@chanzuckerberg/eds/lib/components/ClickableStyle';
+ import type {ClickableStyleProps} from '@chanzuckerberg/eds';
```
We need the `ClickableStyleProps` [for our custom Remix Link component](https://github.com/chanzuckerberg/edu-stack/blob/6f2ad5c03485ec93c5681e5bde64cf5700f189b6/app/components/Link.tsx#L2), so we properly integrate the Remix and EDS Link components.
Re-exporting the props from the top-level index.ts is easier to work with. The deep import edu-stack uses was always a hack.
=> feat: export ClickableStyleProps

src/components/Slider/Slider.tsx, src/components/Tooltip/Tooltip.module.css, src/components/Tooltip/Tooltip.stories.tsx, src/components/Tooltip/Tooltip.test.tsx, src/components/Tooltip/Tooltip.tsx, src/components/Tooltip/__snapshots__/Tooltip.test.tsx.snap
- remove `align` prop, in place of the better-named `placement` prop
This has been marked as deprecated for a while now, so cleaning up the code associated with this. In order to address in a consuming project, you can replace `align` with `placement` in all use cases (this was happening internally already).
- remove `variant` prop
The prop was used for a partially-implemented handling of light/dark mode, and had been marked as deprecated. Removing now, making usage of the light token values as the current, and only, option.
- clean up documentation, storybook config, and test snapshots
=> feat(Tooltip)!: remove deprecated props

src/components/Tag/Tag.module.css, src/components/Tag/Tag.stories.tsx, src/components/Tag/Tag.tsx, src/components/Tag/__snapshots__/Tag.test.ts.snap
- remove deprecated value "yield" from variant list
We had both "warning" and "yield" as possible values for this component's variants, which was confusing. Going forward, we will start with just "warning", and remove this option from the component list. If using "yield", please consider using "warning" instead, or some other treatment.
- change "icon" prop to be of type `IconName` to be consistent with all other components
This syncs up the headless Icon handling across all components, meaning that the names and possible values are determined by the mapped icons, and not any possible ReactNode instance. For consumers, replace any usages of `<Icon />` with the string provided to this cmoponent. Any other nodes used will have to be removed.
- tidy up usage of `<Text />` and typography …
=> feat(Tag)!: remove deprecated props and update API

src/components/Skeleton/Skeleton.stories.tsx, src/components/Skeleton/Skeleton.tsx, src/components/Skeleton/__snapshots__/Skeleton.test.ts.snap
- `Skeleton` provides the same functionality as `.Rect` so simplify by removing this abstraction.
In each case, `Skeleton.Rect` can be replaced with `Skeleton` and retain the same functionality.
=> feat(Skeleton)!: deprecate .Rect subcomponent mapping

src/components/Badge/Badge.stories.tsx, src/components/Badge/Badge.test.tsx, src/components/Badge/Badge.tsx
Removing this prop `name` for consistency with other components. The practice is that any component using another component in a prop should use a camelCase version of the component's name. Because both were supported, users of the now-removed `name` component can change the prop to `icon` without any issue.
=> feat(Badge)!: deprecate name prop on component

src/components/Card/Card.module.css, src/components/Card/Card.stories.tsx, src/components/Card/Card.tsx, src/components/Card/__snapshots__/Card.test.ts.snap
This prop was marked as deprecated so removing in this PR. Instead, rely on consumers to provide any orientation and padding desired on the sub-components.
Anyone using `orientation="horizontal"` can replace this with, e.g., TailwindCSS utility class `flex-row` or a similar class definition on the container.
=> feat(Card)!: deprecate orientation prop

src/components/InlineNotification/InlineNotification.module.css, src/components/InlineNotification/InlineNotification.stories.tsx, src/components/InlineNotification/InlineNotification.tsx
- remove `inactive` prop from component
This had been marked as deprecated, so now removing. As of today, it is not used in any components, and likely too specific a use case to warrant the additional complexity. Usages of this should be removed from code and associated designs.
- remove `yield` variant
Removing this variant, as it overlaps with the usage of the "warning" prop, but is a different color and treatment. For users of the value, designs and code should move to the "warning" value.
=> feat(InlineNotification)!: remove deprecated props from component

src/components/Select/Select.module.css, src/components/Select/Select.tsx
- remove `variant` from component
`variant` was partially implemented and inconsistent with other components which have control for display width (they use boolean `fullWidth`). Remove this prop, and rely on utility classes for width control.
- remove redundant alignment prop `optionsAlign`
Consumers should use the `placement` prop to control how to display the popover. All popover-components share the same API for placement, as determined by PopperJS.
When using `left`, you can set `placement="bottom-start` and when using `right`, you can set `placement="bottom-end`. See more documentation at
https://popper.js.org/docs/v2/constructors/#options
=> feat(Select)!: remove deprecated props

src/components/Link/Link.module.css, src/components/Link/Link.stories.tsx, src/components/Link/Link.tsx
- restore `size` to available
This is used sparingly, but will be used more effectively in the future.
- remove `fullWidth` from component
This is a holdover from linkages to `Button`, so removing now that link is its own component. Use utility classes to alter layout.
=> feat(Link)!: remove and reset deprecated props

src/components/Grid/Grid.tsx, src/components/Toast/Toast.tsx
A little tidying up before release; remove deprecation markers from `Grid` and `Toast`.
=> chore: unmark components as deprecated

docs/PUBLISHING.md
Small note to include the package name in the release field in the github UI
=> docs: add release naming instructions

.storybook/components/Docs/Guidelines/CodeGuidelines.stories.mdx, .storybook/components/Docs/Guidelines/Components.stories.mdx, .storybook/components/Docs/Guidelines/Layout.stories.mdx, .storybook/components/Docs/Guidelines/Typography.stories.mdx, .storybook/components/TokenSpecimen/TokenSpecimen.tsx, src/components/Accordion/Accordion.tsx, src/components/Badge/Badge.tsx, src/components/Breadcrumbs/Breadcrumbs.tsx, src/components/Checkbox/Checkbox.tsx, src/components/Heading/Heading.tsx, src/components/HorizontalStepper/HorizontalStepper.tsx, src/components/InlineNotification/InlineNotification.tsx, src/components/InputLabel/InputLabel.tsx, src/components/Menu/Menu.tsx, src/components/Popover/Popover.tsx, src/components/PopoverContainer/PopoverContainer.tsx, src/components/Radio/Radio.tsx, src/components/SearchBar/SearchBar.tsx, src/components/Slider/Slider.tsx, src/components/Tag/Tag.tsx, src/components/Text/Text.tsx, src/components/Toast/Toast.tsx, src/components/Toggle/Toggle.tsx, src/components/Tooltip/Tooltip.tsx, src/util/flattenReactChildren.ts, src/util/utility-types.ts
A little tidying for v14 release leftover in the docs:
- cleaning a mix of imports for `ReactNode`
- naming of some concepts in doc.s
- the docs and references to removed or updated props
=> docs: clean up documentation post v14

src/components/Link/Link-v2.module.css, src/components/Link/Link-v2.stories.tsx, src/components/Link/Link-v2.tsx, src/components/Link/index.ts
- add stories and styles to match new design
=> feat(Link)!: introduce v2.0 component

src/components/NumberIcon/NumberIcon-v2.module.css, src/components/NumberIcon/NumberIcon-v2.stories.tsx, src/components/NumberIcon/NumberIcon-v2.tsx, src/components/NumberIcon/index.ts
- add in new styles
- create new stories for future snapshots
=> feat(NumberIcon)!: introduce 2.0 component

src/components/TabGroup/TabGroup.module.css, src/components/TabGroup/TabGroup.stories.tsx, src/components/TabGroup/TabGroup.test.tsx, src/components/TabGroup/TabGroup.tsx, src/components/TabGroup/__snapshots__/TabGroup.test.tsx.snap, src/components/TabGroup/index.ts
- add stories and styles for new component theme
- update snapshot
=> feat(TabGroup)!: introduce 2.0 component

src/components/Checkbox/Checkbox-v2.module.css, src/components/Checkbox/Checkbox-v2.stories.tsx, src/components/Checkbox/Checkbox-v2.tsx, src/components/Checkbox/index.ts
- also export V2 to index and nest stories
=> feat(Checkbox)!: introduce 2.0 component

src/components/Button/index.ts, src/components/FieldNote/FieldNote-v2.module.css, src/components/FieldNote/FieldNote-v2.stories.tsx, src/components/FieldNote/FieldNote-v2.tsx, src/components/FieldNote/index.ts, src/components/Input/Input-v2.module.css, src/components/Input/Input-v2.tsx, src/components/Input/index.ts, src/components/InputField/InputField-v2.module.css, src/components/InputField/InputField-v2.stories.tsx, src/components/InputField/InputField-v2.tsx, src/components/InputField/index.ts, src/components/InputLabel/index.ts, src/components/Link/Link-v2.tsx, src/design-tokens/mixins.css, src/util/variant-types.ts
- this updates the separate sub-components as well as ancillary components (FieldNote, Input)
- updates to variant types and mixins
- export updates and added stories
=> feat(InputField)!: introduce 2.0 component

style-dictionary.config.js, tailwind.config.ts
- remove export for old reference-based config output
- internally use the new output with value literals in the JSON
- verify color chips and literal values appear in VSCode when using the tailwind extension
- no changes to story snapshots
=> feat(config)!: use literal values in style-dictionary config

src/components/InputField/InputField-v2.module.css, src/components/InputLabel/InputLabel-v2.tsx, src/components/PopoverListItem/PopoverListItem-v2.module.css, src/components/Select/Select-v2.module.css, src/components/Select/Select-v2.stories.tsx, src/components/Select/Select-v2.tsx, src/components/Select/index.ts
- add new 2.0 component
- add new stories
- add new api options
- align styles for popover sub-components
=> feat(Select)!: introduce 2.0 component

src/components/InlineNotification/InlineNotification-v2.module.css, src/components/InlineNotification/InlineNotification-v2.stories.ts, src/components/InlineNotification/InlineNotification-v2.tsx, src/util/variant-types.ts
- add in 2.0 component with style/token changes
- add in updated design API properties
=> feat(InlineNotification)!: introduce 2.0 component

src/components/PopoverContainer/PopoverContainer-v2.tsx, src/components/PopoverContainer/index.ts, src/components/Tooltip/Tooltip-v2.module.css, src/components/Tooltip/Tooltip-v2.stories.tsx, src/components/Tooltip/Tooltip-v2.test.tsx, src/components/Tooltip/Tooltip-v2.tsx, src/components/Tooltip/__snapshots__/Tooltip-v2.test.tsx.snap, src/components/Tooltip/index.ts
- add in new styles
- preserve existing API, tests, etc.
=> feat(Tooltip)!: introduce 2.0 component

src/components/ButtonGroup/ButtonGroup-v2.module.css, src/components/ButtonGroup/ButtonGroup-v2.stories.tsx, src/components/ButtonGroup/ButtonGroup-v2.tsx, src/components/ButtonGroup/index.ts, src/components/Modal/Modal-v2.module.css, src/components/Modal/Modal-v2.stories.tsx, src/components/Modal/Modal-v2.tsx, src/components/Modal/index.ts
- add in style changes
- simplify interface and update with new semantics
- update test snapshots for chromatic
-
=> feat(Modal)!: introduce 2.0 component

src/components/Card/Card-v2.module.css, src/components/Card/Card-v2.stories.tsx, src/components/Card/Card-v2.test.ts, src/components/Card/Card-v2.tsx, src/components/Card/__snapshots__/Card-v2.test.ts.snap
- add tests and stories
- add new component styles
=> feat(Card)!: introduce 2.0 component

src/components/BannerNotification/BannerNotification.tsx, src/components/InlineNotification/InlineNotification-v2.tsx, src/components/Toast/Toast-v2.tsx, src/util/getIconNameFromStatus.ts
- build step and chromatic snapshots
=> refactor(util): add and use getIconNameFromStatus function

src/components/InputField/InputField-v2.tsx, src/components/TextareaField/TextareaField-v2.module.css, src/components/TextareaField/TextareaField-v2.stories.tsx, src/components/TextareaField/TextareaField-v2.tsx, src/components/TextareaField/index.ts, src/design-tokens/mixins.css
- add stories
- add component updates
- include checks and integrtion between InputField
=> feat(TextareaField)!: introduce 2.0 component

src/components/Accordion/index.ts, src/components/Card/index.ts, src/components/InlineNotification/index.ts, src/components/Toast/index.ts, src/index.ts
- check size export and build succeeds
=> chore: add temporary 2.0 exports

src/components/Button/Button-v2.stories.tsx, src/components/Button/Button-v2.tsx, src/components/Link/Link-v2.stories.tsx, src/components/Link/Link-v2.tsx
- add type param.s to Button and Link to handle extending type
- allow use of `as` for extension
- provide code examples in story documentation
=> feat: add support for extended nav and action components

.storybook/components/Docs/GettingStarted.stories.mdx, .storybook/components/Docs/Guidelines/CodeGuidelines.stories.mdx, .storybook/components/Docs/Guidelines/Components.stories.mdx, .storybook/components/Docs/Guidelines/Icons.stories.mdx, .storybook/components/Docs/Guidelines/Layout.stories.mdx, .storybook/components/Docs/Guidelines/Tokens.stories.mdx, .storybook/components/Docs/Guidelines/Typography.stories.mdx
- separate out the user-facing docs from the contributor docs
- relabel pages to better represent content and intent
- clean up usage of components in pages to be from V2 set
=> docs: reorganize storybook documentation section

src/components/ButtonGroup/ButtonGroup-v2.stories.tsx, src/components/ButtonGroup/ButtonGroup-v2.test.ts, src/components/ButtonGroup/__snapshots__/ButtonGroup-v2.test.ts.snap
- add example showing how to align tertiary buttons
- remove and update stories
=> fix(ButtonGroup): address QA design updates

bin/eds-apply-theme.js, tailwind.config.ts
- support non-subset theming overrides
- support spacing (with proper open typing)
=> fix: update token and theming

src/components/Accordion/Accordion-v2.module.css, src/components/Accordion/Accordion-v2.tsx
- better positioning of `NumberIcon` when used with `Accordion`
- fixes to color token when using `Icon` instances
=> fix(Accordion): address QA updates from design

src/components/AppNotification/AppNotification.module.css, src/components/AppNotification/AppNotification.stories.tsx, src/components/AppNotification/AppNotification.tsx, src/components/AppNotification/__snapshots__/AppNotification.test.ts.snap, src/components/AppNotification/index.ts, src/index.ts
- spacing for close button when text is brief
- better storybook handling
- add type exports
=> fix(AppNotification): apply usage feedback

src/components/Accordion/Accordion-v2.stories.tsx, src/components/Accordion/Accordion-v2.tsx, src/components/Accordion/__snapshots__/Accordion-v2.test.tsx.snap, src/components/Card/Card-v2.stories.tsx, src/components/Card/Card-v2.tsx, src/components/Card/__snapshots__/Card-v2.test.ts.snap, src/components/InlineNotification/InlineNotification-v2.stories.tsx, src/components/InlineNotification/InlineNotification-v2.tsx, src/components/InlineNotification/__snapshots__/InlineNotification-v2.test.ts.snap, src/components/PageNotification/PageNotification.stories.tsx, src/components/PageNotification/PageNotification.tsx, src/components/PageNotification/__snapshots__/PageNotification.test.ts.snap
A few components have a `subTitle` prop, which can contain links in some identified use cases. Allow for this by expanding the types on the relevant components.
=> feat: allow react nodes on subtitle

src/components/Modal/Modal-v2.module.css, src/components/Modal/Modal-v2.stories.tsx, src/components/Modal/Modal-v2.test.tsx, src/components/Modal/Modal-v2.tsx, src/components/Modal/__snapshots__/Modal-v2.test.tsx.snap
- add low and high emphasis
- add detail to story descriptions
- add in button component instead of clickable icon
- remove tooltips from stories
=> fix(Modal): address QA updates

src/components/FieldNote/FieldNote-v2.module.css, src/components/InputField/InputField-v2.stories.tsx, src/components/InputField/__snapshots__/InputField-v2.test.tsx.snap
=> fix(FieldNote): adjust layout for icon and text lockup

src/components/LoadingIndicator/LoadingIndicator-v2.module.css, src/components/LoadingIndicator/LoadingIndicator-v2.stories.ts, src/components/LoadingIndicator/LoadingIndicator-v2.test.ts, src/components/LoadingIndicator/LoadingIndicator-v2.tsx, src/components/LoadingIndicator/__snapshots__/LoadingIndicator-v2.test.ts.snap, src/components/LoadingIndicator/index.ts, src/index.ts
- add tests and snapshots
- update API and component documentation
- update token usages
=> feat(LoadingIndicator)!: introduce 2.0 component

src/components/Button/Button-v2.module.css, src/components/Menu/Menu-v2.module.css, src/components/Menu/Menu-v2.stories.tsx, src/components/Menu/Menu-v2.tsx, src/components/Menu/__snapshots__/Menu-v2.test.tsx.snap, src/components/PopoverContainer/PopoverContainer-v2.module.css, src/components/PopoverListItem/PopoverListItem-v2.module.css
- use primary button with trailing icon
- update stories to reflect change
- also update button handling to prevent UI breaking on long text
=> feat(Menu): set new default for menu trigger

src/bin/migrate/migrations/alpha14-to-alpha15.test.ts, src/bin/migrate/migrations/alpha14-to-alpha15.ts, src/components/FieldNote/FieldNote-v2.stories.tsx, src/components/FieldNote/FieldNote-v2.tsx, src/components/Input/Input-v2.tsx, src/components/InputField/InputField-v2.stories.tsx, src/components/InputField/InputField-v2.tsx, src/components/Select/Select-v2.stories.tsx, src/components/Select/Select-v2.tsx, src/components/TextareaField/TextareaField-v2.stories.tsx, src/components/TextareaField/TextareaField-v2.tsx, src/components/TextareaField/__snapshots__/TextareaField-v2.test.tsx.snap
- update all (sub-)components to use status instead of two sep. props
- refactor stories to use the new prop
- ensure snapshots do not change (not updating class names at the moment)
- add simple-case migration
=> feat!: move from isWarning and isError to status prop

src/components/AppNotification/AppNotification.stories.tsx, src/components/AppNotification/__snapshots__/AppNotification.test.ts.snap, src/components/Link/Link-v2.module.css, src/components/Link/Link-v2.stories.tsx, src/components/Link/Link-v2.tsx, src/components/Link/__snapshots__/Link-v2.test.tsx.snap
- properly apply standalone and non-standalone colors
- add notes on runtime warnings to generate
- add missing stories to demonstrate color inheritance
=> fix(Link): address problems with link color inheritance

src/components/Button/Button-v2.module.css, src/components/Button/Button-v2.stories.tsx, src/components/Button/__snapshots__/Button-v2.test.tsx.snap
=> fix(Button): add in missing inverse disabled treatments

src/components/Button/Button-v2.module.css
- text-utility-default-secondary-* (hover|active)
=> fix(Button): use text-utility-default state tokens

.storybook/data/tokens.json, src/components/Link/Link-v2.module.css, src/design-tokens/themes.json, src/tokens-dist/css/variables.css, src/tokens-dist/json/variables-nested.json, src/tokens-dist/ts/colors.ts
=> feat(Link): add inverse text visited color token and apply

.storybook/preview.tsx, src/components/Tooltip/Tooltip-v2.module.css, src/components/Tooltip/Tooltip-v2.stories.tsx, src/components/Tooltip/Tooltip-v2.tsx, src/components/Tooltip/__snapshots__/Tooltip-v2.test.tsx.snap
- support variants (default and inverse)
- add tests and snapshots
- also add background color treatments thru storybook config
- add chromatic delay to account for some tooltip jitter
=> feat(Tooltip): add inverse variant

src/components/Button/Button-v2.stories.tsx, src/components/Button/__snapshots__/Button-v2.test.tsx.snap, src/components/Link/Link-v2.stories.tsx, src/components/Link/__snapshots__/Link-v2.test.tsx.snap, src/components/TabGroup/TabGroup.stories.tsx, src/components/TabGroup/__snapshots__/TabGroup.test.tsx.snap
=> refactor: update background color integration

src/components/Checkbox/Checkbox-v2.stories.tsx, src/components/Checkbox/Checkbox-v2.tsx, src/components/Radio/Radio-v2.module.css, src/components/Radio/Radio-v2.stories.tsx, src/components/Radio/Radio-v2.test.tsx, src/components/Radio/Radio-v2.tsx, src/components/Radio/__snapshots__/Radio-v2.test.tsx.snap
- stop using radio icons which can now be removed
- replace with styling using in-DOM elements (future proof for transitions)
- better application of color tokens
- add tests
=> refactor(Radio): address component QA feedback

src/components/Checkbox/Checkbox-v2.module.css, src/components/Checkbox/Checkbox-v2.stories.tsx, src/components/Checkbox/__snapshots__/Checkbox-v2.test.tsx.snap, src/components/FieldLabel/FieldLabel.tsx, src/components/FieldNote/FieldNote-v2.tsx, src/components/InputField/InputField-v2.stories.tsx, src/components/InputField/InputField-v2.tsx, src/components/InputField/__snapshots__/InputField-v2.test.tsx.snap, src/components/Radio/Radio-v2.stories.tsx, src/components/Radio/__snapshots__/Radio-v2.test.tsx.snap, src/components/Select/Select-v2.stories.tsx, src/components/Select/Select-v2.tsx, src/components/TextareaField/__snapshots__/TextareaField-v2.test.tsx.snap
=> fix: use aria-disabled when disabled prop is applied

src/components/InputField/InputField-v2.stories.tsx, src/components/InputField/InputField-v2.tsx, src/components/InputField/__snapshots__/InputField-v2.test.tsx.snap, src/components/Select/Select-v2.module.css, src/components/Select/Select-v2.tsx
=> fix: handle required disabled field hints

src/components/FieldLabel/FieldLabel.tsx, src/components/Select/Select-v2.test.tsx, src/components/Select/Select-v2.tsx, src/components/Select/__snapshots__/Select-v2.test.tsx.snap
=> fix(Select): allow attachment of headlessUI props to label

.storybook/data/tokens.json, src/components/Text/Text.module.css, src/design-tokens/tier-2-usage/typography.json, src/tokens-dist/css/variables.css, src/tokens-dist/json/variables-nested.json, src/util/variant-types.ts
- also mark of the non-sized token as deprecated
=> feat(Typography): add typography-overline-lg

src/components/Table/Table.stories.tsx, src/components/Table/Table.tsx, src/components/Table/__snapshots__/Table.test.ts.snap
Expand type usages that are allowed in `.HeaderCell` instances. This will allow for some flexibility needed.
=> fix(Table): allow nodes in header cells

src/components/InputField/InputField.stories.tsx, src/components/InputField/InputField.tsx, src/components/InputField/__snapshots__/InputField.test.tsx.snap
- add tests and snapshots
- implement show/hide button to appear after any inputWithin elements
=> feat(InputField): add show/hide button for password field type

src/components/AppNotification/AppNotification.tsx, src/components/Button/Button.test.tsx, src/components/Button/Button.tsx, src/components/Link/Link.test.tsx, src/components/Link/Link.tsx, src/components/Modal/Modal.tsx, src/components/PageNotification/PageNotification.tsx, src/components/Slider/Slider.stories.tsx, src/components/ToastNotification/ToastNotification.tsx, src/util/findLowestTenMultiplier.ts, src/util/logging.ts
- add utility function for doing the logging
- use in various components (Link, Button, util.s)
- add additional tests
=> feat: add runtime warning/errors to components

src/components/Select/Select.stories.tsx, src/components/Select/Select.tsx, src/components/Select/__snapshots__/Select.test.tsx.snap
- borrow type value determination from HeadlessUI internals
- add test to make sure types used map to params
=> fix(Select): expose generic types to allow by to work

src/components/InputField/InputField.stories.tsx, src/components/InputField/InputField.test.tsx, src/components/InputField/InputField.tsx, src/components/InputField/__snapshots__/InputField.test.tsx.snap
- document ability with stories
- add snapshots for the UI icons generated by the browsers
=> docs(InputField): add stories for date and time support

src/components/AppNotification/__snapshots__/AppNotification.test.ts.snap, src/components/Link/Link.module.css, src/components/Link/Link.test.tsx, src/components/Link/Link.tsx, src/components/Link/__snapshots__/Link.test.tsx.snap
- fix handling of size so it isn't applied where it can't be used
- add assert for using size with context=inline
- update tests and snapshots
=> fix(Link): apply font weight to standalone sizes

.github/pull_request_template.md, .github/workflows/test.yml
When doing a release, the commits have already been pre-validated, and the current check will sometimes look back thru old commits which 1-2 have longer titles/text than the lint check allows, yielding failed builds on `main`.
Only run checks for release that can involve actual build-breaking checks by running on any branch but `main`.
Also update the commit template to be more concise
- simplify commit template
- don't do commitlint checks when merging into main
- added change to build config to see if the commit lint would be skipped
=> chore: update github config

src/components/Button/Button.module.css
Update the padding for `Button`, fixing some glitches in the layout.
=> fix(Button): update button padding to match design

src/components/Menu/Menu.module.css
- remove style overrides left from 1.0 component
- update snapshots and re-run tests
Before:
After:
=> fix(Menu): remove style overrides to Menu.Button

src/components/Checkbox/Checkbox.module.css, src/components/Checkbox/Checkbox.stories.tsx, src/components/Checkbox/__snapshots__/Checkbox.test.tsx.snap
Specify a font-size for the glyph in the checkbox so that wrapping adjacent text doesn't change the size of the glyph when `:checked`
Before:
After:
=> fix(Checkbox): specify a font size for the checked glyph

src/components/Popover/Popover.stories.tsx
Just update the component version number used in the storybook config, which should have happened in #2031 
=> fix(Popover): update component version number

src/components/Button/Button.tsx
`ClickableStyle` is gone, so we shouldn't mention it
=> docs(Button): remove reference to ClickableStyles

src/components/Link/Link.module.css, src/components/Link/Link.stories.tsx, src/components/Link/Link.test.tsx, src/components/Link/Link.tsx, src/components/Link/__snapshots__/Link.test.tsx.snap
- update documentation to explain cases
- add warning for misaligned prop usages
- update snapshots and tests
=> fix(Link): handle inverse variant for standalone links

.github/workflows/test.yml
Looks like we had a typo in the config for the commitlint job. [According to this](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/accessing-contextual-information-about-workflow-runs#github-context), `github.ref` uses the full path, which takes the form like `refs/heads/X`, and we were missing the `s`
So, why do we want this extra line anyway, and not check `main`?
* the list of commits used in the action corresponds to what's in the release branch
* in the case of a release, the count corresponds to the commits in that branch, but then indexes that count on commits on `main`
* it looks back on `main` and will run the check on every commit to the previous merge commits, so it can be hundreds of commits being re-linted (and will fail sporadically b/c …
=> chore: fix ref name

tailwind.config.ts
- not giving a type to the data extracted from the internal config results in an `any` being emitted in the package
- replace that with a similar form used by `sizes`
=> fix(tailwind): update animation token export types

src/components/Button/Button.module.css, src/components/Button/Button.tsx, src/components/Button/__snapshots__/Button.test.tsx.snap, src/components/SearchBar/__snapshots__/SearchBar.test.ts.snap
=> feat(Button): support for not-allowed cursor when disabled

package.json, src/components/DataTable/DataTable.module.css, src/components/DataTable/DataTable.stories.tsx, src/components/DataTable/DataTable.tsx, src/components/DataTable/__snapshots__/DataTable.test.ts.snap, yarn.lock
**NOTE**: this merges into the existing branch for EDS-1209. posting to generate the snapshots and such, but will just merge into that in-progress work
- use tanstack as basis for table implementation
- add in relevant stories for styles
=> feat(DataTable): implement TanStack Table

src/components/Button/Button.stories.tsx, src/components/Button/Button.tsx, src/components/Button/__snapshots__/Button.test.tsx.snap, src/components/SearchBar/__snapshots__/SearchBar.test.ts.snap
Make sure that, when `Button` is used, any utility classes applied to the button get applied to the wrapper (e.g., positioning, etc.)
=> fix(Button): apply external styles when disabled

src/index.ts
Provide the transition component from HeadlessUI to consumers, since there is no bound UI or design for this helper component, and would otherwise take time to implement separately.
=> feat: re-export HeadlessUI's Transition component

src/components/Select/Select.test.tsx, src/components/Select/Select.tsx
- remove throw from code that is for a complex a11y check
- update tests
This allows for any external, automated accessibility tests to provide a better contextual error without breaking behavior during development.
=> fix(Select): remove label checks from component

src/components/DataTable/DataTable.module.css, src/components/DataTable/DataTable.stories.tsx, src/components/DataTable/DataTable.tsx, src/components/DataTable/__snapshots__/DataTable.test.ts.snap
- add classes for (header) cell containers
- fix cell height size
- tune up tests, stories, and snapshots
=> fix(DataTable): fix cell size and border in FF

src/components/DataTable/DataTable.module.css, src/components/DataTable/DataTable.stories.tsx, src/components/DataTable/DataTable.tsx, src/components/DataTable/__snapshots__/DataTable.test.ts.snap, src/components/DataTable/index.ts, src/index.ts
- component to support standard EDS statuses per row
- update tests and snapshots (new story for comparison)
=> feat(DataTable): add support for table row statuses

docs/PUBLISHING.md
Adding a `git pull` to grab the latest on `next` before attempting to back-merge, so that the push isn't rejected unnecessarily. Makes collaboration a little smoother :)
Without that, if any PRs land on `next` before a release is completed, it can cause some merge noise and a little off-script actions that can leave the repository in an ambiguous state.
=> docs: add clarifying back-merge instruction

src/components/Select/Select.module.css
Give the select field the highest token value for z-index so that it will appear above modal containers (both portal to the top edge of the DOM, so z-index and sequencing can cause `Select.Options` to appear beneath the modal container). Modals currently use z-index of 1050 and are set manually to that level, so this will go above that.
No stacking context changes are needed.
=> fix(Select): pull z-index of select options to top

src/components/DataTable/DataTable.module.css, src/components/DataTable/DataTable.stories.tsx, src/components/DataTable/DataTable.tsx, src/components/DataTable/__snapshots__/DataTable.test.ts.snap
- first column is pinned by default
- allow for other columns to be pinned
=> feat(DataTable): allow for pinning columns

.storybook/components/Docs/Guidelines/CodeGuidelines.mdx, .storybook/components/Grid/Grid.tsx, .storybook/components/Section/Section.tsx, plop-templates/Component/Component.tsx.hbs, src/components/AppNotification/AppNotification.tsx, src/components/Card/Card.tsx, src/components/FieldNote/FieldNote.tsx, src/components/Icon/Icon.tsx, src/components/InputChip/InputChip.tsx, src/components/Label/Label.tsx, src/components/Menu/Menu.tsx, src/components/NumberIcon/NumberIcon.tsx, src/components/PopoverListItem/PopoverListItem.tsx, src/components/TabGroup/TabGroup.tsx
Change TS convention to consistently use `type` instead of a mix of `type` and `interface` for components. Mark any types that get exported as to be updated at the next major version.
**NOTE**: some changes come from tweaks to `prettier` config, so accepting those
=> refactor: update non-exported types from interface to type

.storybook/data/tokens.json, src/components/VisualPageIndicator/VisualPageIndicator.module.css, src/components/VisualPageIndicator/VisualPageIndicator.stories.ts, src/components/VisualPageIndicator/VisualPageIndicator.test.tsx, src/components/VisualPageIndicator/VisualPageIndicator.tsx, src/components/VisualPageIndicator/__snapshots__/VisualPageIndicator.test.tsx.snap, src/components/VisualPageIndicator/index.ts, src/design-tokens/themes.json, src/index.ts, src/tokens-dist/css/variables.css, src/tokens-dist/json/variables-nested.json, src/tokens-dist/ts/colors.ts
=> feat(VisualPageIndicator): introduce 1.0 component

src/components/ToastNotification/ToastNotification.stories.tsx, src/components/ToastNotification/ToastNotification.test.tsx, src/components/ToastNotification/ToastNotification.tsx
- add in dismissType
- add in tests and console messages so make sure the new field falls back
=> fix(ToastNotification): fix typo in prop name

docs/PUBLISHING.md
Add a `yarn install` in the back-merge step, to account for edge case where `next` has new package versions committed (yarn will blow up if the installed packages do not match the ones mentioned in yarn.lock/package.json)
=> docs(PUBLISHING): update publish back-merge instruction

.gitignore, src/components/Button/Button.module.css
Previously, the button styles when `icon-only` would unset the minimum width to take on a perfectly circular shape. This is fine in default cases, but would cause the button to lose width when used in a flex context, like in `DataTable`. Instead of `unset`ting the width for icon-only, add a `min-width` to each button size when layout is icon-only.
=> fix(button): update button sizes in icon only to have a minimum width

.gitignore, bin/_util.js, bin/_util.test.js, bin/eds-import-from-figma-api.js, bin/eds-import-from-figma.js, package.json, yarn.lock
- handle both downloaded file version and API version
- handle input and edge cases (e.g., missing config)
- separate and handle parsing of token contents into theme file
- guard against committing local edsrc config
we also flag instances of mismatches between figma and code, for later fixing (in Figma). Example:
=> feat(scripts): allow import script to pull using Figma API

bin/eds-import-from-figma-api.js
The script should only attempt to write reference values when used with `--local`. Instead, when used in a consuming app that needed a non-default theme, it would try to write reference values to the custom theme, which would be missing from EDS.
This updates the check to only throw a validation error when run in local mode, AND when the reference value to write is missing (the intention).
=> fix(scripts): add locality check to value pre-validation

.storybook/data/tokens.json, src/components/Accordion/Accordion.module.css, src/components/Breadcrumbs/Breadcrumbs.module.css, src/components/Card/Card.module.css, src/components/Fieldset/Fieldset.module.css, src/components/Fieldset/Fieldset.tsx, src/components/Fieldset/__snapshots__/Fieldset.test.tsx.snap, src/components/Modal/Modal.module.css, src/components/Modal/Modal.stories.tsx, src/components/Modal/Modal.tsx, src/components/Modal/__snapshots__/Modal.test.tsx.snap, src/components/Tag/Tag.module.css, src/components/TextareaField/TextareaField.module.css, src/components/TextareaField/TextareaField.tsx, src/components/TextareaField/__snapshots__/TextareaField.test.tsx.snap, src/design-tokens/core-tokens.json, src/design-tokens/css/base/body.css, src/tokens-dist/css/variables.css, src/tokens-dist/json/variables-nested.json, src/tokens-dist/ts/colors.ts
Remove token usages for foreground/background colors in storybook CSS. Remove token which is no longer being used. Updates to a few components where the base color to use should have been specified but wasn't (we got it for free in some cases, but the component should have specified it deliberately instead of relying on storybook to do so).
=> fix(storybook): set default foreground/background colors for story pages

.storybook/data/tokens.json, src/components/Button/Button.module.css, src/tokens-dist/css/variables.css, src/tokens-dist/json/variables-nested.json
Saw that the treatment for the following button styles were missing
* variant=default
* rank=primary
* state=hover
Add in the color styles for this case, and update snapshots as needed
=> fix(Button): add token usage for primary default button on hover

src/components/TabGroup/TabGroup.module.css
The component was incorrectly using the tier-1 tokens directly. Change the tokens used to match the ones in design. Also fix the errant usage of the recently removed tier 1 `anim` tokens and replace with `ease-in-out`
https://github.com/user-attachments/assets/38427963-4ec9-4463-824f-ac273a6802fd
=> fix(TabGroup): use proper tier 2+ tokens with component

src/components/InputChip/InputChip.module.css
Add left padding equivalent to 12px to the inside of `InputChip` components to match design
=> fix(InputChip): add padding to inside left edge to match design

.storybook/components/Docs/Guidelines/Theming.mdx, src/design-tokens/css/base/reset.css, tailwind.config.ts
Before, anyone using the theming tools would have to occasionally combine keys and values very similar to what comes with EDS, in order to get the same config results using their theme file. Inconvenient!
Instead, move this creation logic into an exported method AND use the method to generate the default config. This way we re-use the logic internally, and provide a simpler interface for using the old method (duplicate logic seen in EDS in your project directly).
Update the documentation to reflect this improvement
=> refactor(config): export and document tailwind config utility method

.storybook/components/Docs/Guidelines/Theming.mdx, README.md, bin/_util.js, bin/eds-import-from-figma-api.js
- support better checks for unknown figma variable types
- update and fix handling for verbose output
- add documentation details for how to handle import files
=> fix(scripts): add in checks for unknown types

src/tokens-dist/css/variables.css, tailwind.config.ts
Previously we created a utility method to DRY up the code. However this required typing which, after thinking a bit, wasn't worth the effort to make accurate (this is not exported). Further, it's possible to use built-in things to achieve the same result. Use `Object.assign` instead of a custom piece of code that does the same.
A further improvement could involve breaking this down such that we can use `.apply` and reduce the lines of code for conversion. BUT, since there are only two of these, can come back to that. Example:
```js
Object.assign.apply(null, [{}, ...entries]); // where `entries` is the list of converted key-value pairs after the .map
```
=> fix(tailwind): adjust config creation to avoid TypeScript issues

.storybook/preview.tsx, src/components/DataTable/__snapshots__/DataTable.test.ts.snap, src/components/FieldLabel/FieldLabel.tsx, src/components/InputField/InputField.module.css, src/components/InputField/InputField.stories.tsx, src/components/InputField/InputField.tsx, src/components/InputField/__snapshots__/InputField.test.tsx.snap, src/components/Select/Select.module.css, src/components/Select/Select.stories.tsx, src/components/Select/Select.tsx, src/components/Select/__snapshots__/Select.test.tsx.snap, src/components/TextareaField/TextareaField.module.css, src/components/TextareaField/TextareaField.stories.tsx, src/components/TextareaField/TextareaField.tsx, src/components/TextareaField/__snapshots__/TextareaField.test.tsx.snap
* Add `sublabel` for each of the listed components
* Update snapshots and test descriptions
=> Add sublabel prop for input fields (Select, InputField, TextareaField)

bin/_util.js, bin/eds-import-from-figma-api.js
- previously, it was sending the collection ID to FigmaVariable
- now, add an enquirer entry to select that mode from the tier 1 collection
- also update the class to return all the collection information
- use the additional collection information to filter out the unpublished collection data
- doulbe check that tests still pass
- add in additional tests for script logic
- add TODOs to flag refactor opportunities
=> fix(scripts): update script wrapper to use proper tier 1 mode

src/components/Checkbox/Checkbox.tsx, src/components/DataTable/DataTable.tsx, src/components/Fieldset/Fieldset.tsx, src/components/InputField/InputField.tsx, src/components/PopoverListItem/PopoverListItem.tsx, src/components/Radio/Radio.tsx, src/components/Select/Select.tsx, src/components/TextareaField/TextareaField.tsx, src/components/Toggle/Toggle.tsx
- use ReactNode to seamlessly allow use of null/undefined values
- verify all existing tests work
=> fix: sync type declarations for sublabel and fieldNote

.storybook/components/Docs/Guidelines/CodeGuidelines.mdx, src/components/Accordion/Accordion.module.css, src/components/Modal/Modal.module.css, src/design-tokens/mixins.css
The token was removed, and this cleans up the few lingering usages of that token that were missed.
=> fix: remove lingering usages of depecated animation token

src/components/Card/Card.tsx, src/components/Card/__snapshots__/Card.test.ts.snap
- `<article>`, `<header>`, and `<footer>` have specific semantic meaning
- use role-less containers (`<div>`) instead
- also sonsider using `<h3>` or higher for the main card header
=> fix(Card): use a11y-compliant HTML tags for component

src/index.ts
several components have recently been updated to use the new token system, but weren't grouped properly in the src/index.ts file. Clean up this cosmetic discrepancy.
=> chore: re-organize exports to reflect component theme major version

.github/workflows/test.yml
See [docs](https://www.chromatic.com/docs/cli/#continuous-integration)
It looks like the previous config was using an unsupported (?) `=` syntax for the value, which may be tripping things up with the latest version of the `chromatic` dependency. Switch to using the environment variable approach.
Result: https://github.com/chanzuckerberg/edu-design-system/actions/runs/17445020400/job/49537232470?pr=2264#step:6:3
=> chore: use CHROMATIC_PROJECT_TOKEN as environment variable

.storybook/components/DesignTokens/Tier2/Colors.stories.tsx, .storybook/components/DesignTokens/Tier3/Colors.stories.tsx
Make sure the handful of token names that are `camelCase` when used in tailwind appear as such in the documentation.
=> docs(tokens): add proper formatting to the figma/tailwind token refs 
