packages/tokens/properties/color/base.json
Rename tokens to better match the existing tokens. I think this will make a cleaner mapping.
`npm start`, check the storybook colors docs
=> feat(tokens): replace eds token numbers

.eslintrc, packages/components/docs/token-table.tsx, packages/components/src/playground/button.tsx, packages/components/src/typography/typography.tsx
https://github.com/chanzuckerberg/edu-design-system/pull/284#discussion_r571216907
build passes
=> chore(lint): turn off explicit-function-return-type

package.json, packages/components/.storybook/preview.tsx, packages/components/README.md, packages/components/package-lock.json, packages/components/package.json, packages/components/src/tokens.stories.mdx, packages/components/tailwind.config.js, packages/tokens/README.md, packages/tokens/package-lock.json, packages/tokens/package.json
Rename the packages:
- czedi-kit-components -> eds-components
- czedi-kit-tokens -> eds-tokens
- n/a
=> Prep package names

README.md
Update README for nodenv. Thank you @dierat for pointing this out!
n/a
=> Update README for nodenv

.eslintrc, package-lock.json, package.json, packages/components/jest.config.js, packages/components/jest.setup.ts, packages/components/package-lock.json, packages/components/package.json, packages/components/src/Text/Text.spec.tsx
This PR adds the eslint plugin for testing library.
- CI
- Added an error intentionally and ran linters locally
=> Add eslint-plugin-testing-library

README.md, packages/components/README.md, packages/tokens/README.md
Refactor and update the project and package READMEs.
n/a
=> Refactor project readmes

packages/components/package.json
Tell Webpack that eds-components has no side effects, to help it remove unused files more effectively when someone imports from index.js.
https://webpack.js.org/guides/tree-shaking/\#mark-the-file-as-side-effect-free
- CI
=> No side effects

README.md, SECURITY.md
Since this project is already public, we should bring it up to the [CZI open-source guidelines](https://czi.atlassian.net/wiki/spaces/TECH/pages/1900972990/Creating+an+Open+Source+Project+at+CZI#CreatinganOpenSourceProjectatCZI-Licensing). Mainly
- adding a SECURITY.md file
- adding a project status
n/a
=> update docs needed per open-source guidelines

packages/components/src/Tag/Tag.tsx
Add the ability to pass a unique className to the new Tag component
No regressions
=> Add option ClassName attribute to Tag

packages/components/src/Button/__snapshots__/button.spec.tsx.snap, packages/components/src/Button/button.stories.tsx
missed these last few sections we wanna show in [zeroheight](https://zeroheight.com/0843bc428/p/777700-button/b/32e1a2)
build passes
=> docs: add small button stories for zeroheight

package.json, packages/tokens/package.json
This PR
- Fixes the eds-tokens build script, which I broke in #533 
- Improves the output of the build and start commands
- CI
=> Misc cleanups 2

packages/components/src/Banner/Banner.stories.tsx, packages/components/src/Button/button.stories.tsx, packages/components/src/Heading/Heading.stories.tsx, packages/components/src/Link/Link.stories.tsx, packages/components/src/SvgIcon/SvgIcon.stories.tsx, packages/components/src/Tag/Tag.stories.tsx, packages/components/src/Text/Text.stories.tsx, packages/components/src/Toast/Toast.stories.tsx, packages/components/src/common/CloseButton/CloseButton.stories.tsx, packages/components/src/common/Notifications/NotificationIcon/NotificationIcon.stories.tsx, plop-templates/Component/Component.stories.tsx.hbs
Convert stories to [component story format (CSF) v3](https://storybook.js.org/blog/component-story-format-3-0/).
- CI
=> Component story format v3

.eslintrc, package.json, packages/components/src/Button/button.stories.tsx, packages/components/src/Link/Link.stories.tsx, yarn.lock
Add chanzuckerberg/eslint-plugin-stories.
- CI
- Intentional lint violations
=> Add chanzuckerberg/eslint-plugin-stories

packages/components/package.json, packages/components/src/Tooltip/Tooltip.stories.tsx, yarn.lock
This PR updates `story-utils` to v3.0.4, which has some bug fixes needed to use story play functions as intendned.
- Manual testing
=> Upgrade @chanzuckerberg/story-utils from 3.0.1 to 3.0.4

packages/components/src/FormGroup/FormGroup.module.css, packages/components/src/FormGroup/FormGroup.spec.tsx, packages/components/src/FormGroup/FormGroup.stories.tsx, packages/components/src/FormGroup/FormGroup.tsx, packages/components/src/FormGroup/__snapshots__/FormGroup.spec.tsx.snap, packages/components/src/FormGroup/index.ts, packages/components/src/index.ts
Clubhouse ticket: https://app.shortcut.com/czi-edu/story/169595/button-group-form-group-move-to-eds
Location in `traject`: https://github.com/FB-PLP/traject/tree/master/app/assets/javascripts/v2/core/EDSCandidates/FormGroup
=> feat: add FormGroup component

CHANGELOG.md, lerna.json, packages/components/CHANGELOG.md, packages/components/package.json, packages/tokens/CHANGELOG.md, packages/tokens/package.json, yarn.lock
- patch eds for deps upgrades, esp style-dictionary
=> chore(release): v0.8.1

packages/components/src/Icons/PlayArrowRounded.tsx, packages/components/src/Icons/index.ts
Addresses: https://app.shortcut.com/czi-edu/story/187869/feedback-status-icons-add-playarrowroundedicon-to-eds
Followed playbook: https://eds.czi.design/0843bc428/p/13f502-icons/t/895d68
Storybook:
=> Add PlayArrowRoundedIcon

.storybook/main.js, package.json, yarn.lock
- Add storybook badges addon to next branch
- Same as #895 but for next branch
- See it working manually
=> chore: add storybook badges add-on

docs/CODE_GUIDELINES.md, src/components/AccordionPanel/AccordionPanel.module.css, src/components/AccordionPanel/AccordionPanel.tsx, src/components/Breadcrumbs/Breadcrumbs.module.css, src/components/BreadcrumbsItem/BreadcrumbsItem.tsx, src/components/Button/Button.module.css, src/components/FieldNote/FieldNote.module.css, src/components/FileUploadField/FileUploadField.module.css, src/components/FileUploadField/FileUploadField.stories.tsx, src/components/FileUploadField/FileUploadField.tsx, src/components/Icon/Icon.tsx, src/components/LinkList/LinkList.module.css, src/components/LinkListItem/LinkListItem.tsx, src/components/ListDetail/ListDetail.module.css, src/components/ListDetail/ListDetail.tsx, src/components/LoadingIndicator/LoadingIndicator.module.css, src/components/LoadingIndicator/LoadingIndicator.tsx, src/components/PrimaryNav/PrimaryNav.module.css, src/components/PrimaryNavItem/PrimaryNavItem.tsx, src/components/SelectField/SelectField.module.css, src/components/SelectField/SelectField.tsx, src/components/Tags/Tags.module.css, src/components/TagsItem/TagsItem.tsx
[ch191478]
just some cleanup work 🙂 
- verify w/ Chromatic tests
=> Update existing icons to use `size`, `color` props

src/components/Button/Button.stories.tsx, src/components/ButtonGroup/ButtonGroup.module.css, src/components/ButtonGroup/ButtonGroup.stories.tsx, src/components/ButtonGroup/ButtonGroup.test.ts, src/components/ButtonGroup/ButtonGroup.tsx, src/components/ButtonGroup/__snapshots__/ButtonGroup.test.ts.snap, src/components/Modal/ModalExample.tsx
[sc-187505]
- Move buttongroup to next
- Unit/snap tests
- Chromatic
=> chore: move buttongroup to next

.eslintrc, packages/components/src/Button/button.tsx, packages/components/src/Heading/Heading.tsx, packages/components/src/Link/Link.tsx, packages/components/src/SvgIcon/SvgIcon.stories.tsx, packages/components/src/Text/Text.spec.tsx, packages/components/src/common/typography.tsx, packages/components/src/storyUtils/clickableStyleUtils.tsx
Summary:
Adds the react/jsx-sort-props rule to our linter
Test Plan:
This one is pretty easy, just check to see if the lint workflow works 🤗
=> feat: add lint rule

package.json, tsconfig.build.json
=> build: publish icons

.storybook/recipes/GlobalHeader/GlobalHeader.module.css, .storybook/recipes/GlobalHeader/GlobalHeader.tsx, src/components/Header/Header.module.css, src/components/PrimaryNavItem/PrimaryNavItem.module.css
Summary:
To make the merge easier with new next branch from #987 
Added hover/focus states to the menu button for alignment with nav items below on small screen global header
Test Plan:
yarn test runs with success (deprecation warning as usual)
yarn types runs without issues
yarn lint runs without issues
yarn start works
=> feature: port changes menu-button-hover branch

src/components/Heading/Heading.module.css, src/components/Text/Text.module.css
- reduces specificity for app overrides in text and heading
- manual testing
- build and use in app, see if class override for margins work
- chromatic
=> chore(heading, text): lower specificity for margin for app overrides

src/components/Checkbox/Checkbox.tsx
- noticed this while matching checkbox api in main to next
- n/a
=> chore(checkbox): update comment to correct import

src/components/Tag/Tag.tsx
Porting over an update that was made on `main`. The recommended comment change comes from this PR suggestion: https://github.com/chanzuckerberg/edu-design-system/pull/1011/files/832749b710d89286536460dcf973877d17bd2258#r859158783
Verify the prop comment is updated in storybook.
=> docs(tag): update variant prop comment

.stylelintrc, package.json, yarn.lock
context: https://github.com/chanzuckerberg/edu-design-system/pull/1010#discussion_r859154358
matches our stylelint config to the one on `next` to make merging easier
`yarn styles` shows no errors
=> chore: use stylelint-config-recommended

src/components/Banner/Banner.tsx
In https://github.com/chanzuckerberg/edu-design-system/pull/1033 I updated the comment for the `Banner` `isFlat` prop. This PR brings the same change to `next`.
Verify the updated comment appears in storybook on `next`.
=> docs(banner): update isFlat prop comment

src/components/DataBar/DataBar.stories.tsx, src/components/DataBar/DataBar.tsx, src/components/DataBar/__snapshots__/DataBar.test.tsx.snap
- adds roles to the databar and its elements for accessibility
- this mirrors the horizontal bar in LP
- accessibility tests pass
- no visual diff
=> test(databar): assign roles for accessibility

CHANGELOG.md, codecov.yml, package.json
bring in the release commit so `next` and `main` point to the same spot. there's probably a way to do this without creating a separate branch 🤔 
build passes
=> chore: merge in v0.21.0 release branch

src/components/Banner/Banner.module.css, src/components/Banner/Banner.tsx, src/components/Hr/Hr.tsx
Fixing a couple of small issues I noticed when reviewing https://github.com/chanzuckerberg/edu-design-system/pull/1061
`yarn types` produces no errors.
=> chore(banner, hr): fix types and remove comment

package.json
=> chore: release beta test

package.json, src/upcoming-components/Hero/Hero.tsx
=> Tmp release test

CHANGELOG.md, package.json
merge `release-v0.21.1` branch back into next
=> chore(release): 0.21.1

CHANGELOG.md, package.json, src/components/Banner/Banner.module.css, src/components/InlineNotification/InlineNotification.module.css, src/components/Toast/Toast.module.css, src/design-tokens/mixins.css
=> Release v0.22.0

.storybook/pages/Cad/Cad.tsx, src/components/DragDrop/DragDrop.tsx, src/components/DragDropContainer/DragDropContainer.tsx
=> chore(dragdrop): move state

src/components/Popover/Popover.test.tsx, src/components/Popover/Popover.tsx, src/components/Popover/PopoverExample.tsx, src/components/Popover/__snapshots__/Popover.test.tsx.snap
- now closes popover on escape
- tested in unit test
- also includes popover unit test snaps
- tests pass
[sc-201722]
=> fix(popover): close popover on escape

src/components/Banner/Banner.module.css, src/components/Banner/Banner.tsx, src/components/Banner/__snapshots__/Banner.test.tsx.snap, src/components/PageLevelBanner/PageLeveBanner.test.tsx, src/components/PageLevelBanner/PageLevelBanner.module.css, src/components/PageLevelBanner/PageLevelBanner.stories.tsx, src/components/PageLevelBanner/PageLevelBanner.test.tsx, src/components/PageLevelBanner/PageLevelBanner.tsx, src/components/PageLevelBanner/__snapshots__/PageLevelBanner.test.tsx.snap, src/components/PageLevelBanner/index.ts
Follow-up to https://github.com/chanzuckerberg/edu-design-system/pull/1118 which had some feedback that I didn't address before merging.
No changes in storybook; this is all refactoring.
=> chore(page-level-banner): clean up

.storybook/components/DesignTokens/Tier2/TypographyUsage.js, .storybook/recipes/CalendarCard/CalendarCard.module.css, .storybook/recipes/CalendarCard/CalendarCard.stories.tsx, .storybook/recipes/CalendarCard/CalendarCard.tsx, .storybook/recipes/CalendarCard/index.ts, src/components/Heading/Heading.module.css, src/components/Heading/Heading.stories.tsx, src/components/Heading/Heading.tsx, src/components/Heading/__snapshots__/Heading.test.tsx.snap, src/components/Utilities/TypographyUsage.css, src/design-tokens/tier-2-usage/typography-usage.css
https://www.figma.com/file/Ff7hJoSvXX9hkAmIklnsT2/EDS-Paper-v1.0-%7C-UI-Components?node-id=968%3A5311
Recipe for a calendar card to represent an event within calendar UI
Storybook: Recipes/CalendarCard
=> feat(calendarcard): add recipe

src/components/TimelineNav/TimelineNav.tsx, src/upcoming-components/TableObject/TableObject.stories.tsx
I'm seeing some type errors in the `TableObject` component because a prop type was updated in `Table` but the `TableObject` stories are using the old type values.
Run `yarn types` and verify there are no errors.
=> fix(table-object): fix behavior type updated in Table

.storybook/recipes/BaselineCard/BaselineCard.module.css, .storybook/recipes/BaselineCard/BaselineCard.stories.tsx, .storybook/recipes/BaselineCard/BaselineCard.tsx, .storybook/recipes/BaselineCard/index.ts, .storybook/recipes/CalendarCard/CalendarCard.module.css, src/components/CardBody/CardBody.tsx, src/components/CardHeader/CardHeader.tsx, src/components/Tag/Tag.stories.tsx
- adds baseline card according to [mock](https://www.figma.com/file/Ff7hJoSvXX9hkAmIklnsT2/EDS-Paper-v1.0-%7C-UI-Components?node-id=1986%3A10883)
[sc-200369]
- no chromatic diffs
=> feat(baselinecard): create baseline card recipe

src/components/Tabs/Tabs.module.css, src/components/Tabs/Tabs.stories.tsx, src/components/Tabs/Tabs.test.tsx, src/components/Tabs/Tabs.tsx, src/components/Tabs/__snapshots__/Tabs.test.tsx.snap, src/design-tokens/tier-2-usage/typography-usage.css
- matches tabs [mocks](https://www.figma.com/file/DEm9VhynEYAlx66ogEuskp/Tab-Navigation---Component-Exploration-%2B-Creation?node-id=3870%3A10986)
- adjusts tabs font
- adjusts active indicator box size
- adds scroll indicators
https://user-images.githubusercontent.com/86632227/175191559-76d83b5c-e32c-412f-9d15-c9b3f2d15883.mov
- no visual regression except those using tabs
[sc-202249]
=> chore(tabs): match mocks

src/components/Layout/Layout.module.css, src/components/Layout/Layout.stories.tsx, src/components/Layout/Layout.tsx, src/components/Layout/__snapshots__/Layout.test.tsx.snap
- adds 33-67 layout
[sc-203640]
https://user-images.githubusercontent.com/86632227/176318753-c3a5b0bb-0b89-4ff6-8531-bcc38636cc05.mov
=> chore(layout): add 33-67 layout

.storybook/pages/FeedbackOverview/FeedbackOverview.tsx
=> chore(timeline): add dot

CHANGELOG.md, package.json
keeping `next` in sync with `main` (#1227)
=> chore(release): v3.1.1

CHANGELOG.md, package.json
Keeping next in sync with main, with main bumping to 3.1.2: https://github.com/chanzuckerberg/edu-design-system/pull/1230
=> chore(release): v3.1.2

src/components/Score/Score.stories.tsx
- moves core stories from `PleaseUpdateThisToADifferentFolder` to `Molecules/Messaging` like `<Tag>`
- thus organized properly and no longer needs to be updated to a different folder
=> chore(score): update score storybook folder

CHANGELOG.md, package.json
Keeping `next` in sync with `main`.
All automated tests pass.
=> chore(release): v5.0.0

CHANGELOG.md, package.json
Keeping `next` in sync with `main`.
=> chore(release): 5.0.1

CHANGELOG.md, package.json
Keeping `next` in sync with `main`.
=> chore(release): 5.1.1

src/components/Tabs/Tabs.module.css, src/components/Tabs/Tabs.tsx
Yet more Tabs cleanup:
- Fix tab ids (more info inline)
- Change where aria-labelledby is applied
- ~~Remove scroll styling~~ (nvm, I didn't realize this was intentional. Thought it was part of BM's template)
- Minor type cleanup
- Tests
- Storybook
=> More tabs cleanup

CHANGELOG.md, package.json
Keeping `next` in sync with `main`
=> chore(release): v5.2.1

package.json, src/components/Tabs/Tabs.tsx, src/components/TimelineNav/TimelineNav.tsx, yarn.lock
Upgrade shared React eslint plugin, which enables the 2 new rules from https://github.com/chanzuckerberg/frontend-libs/pull/36
CI
=> Upgrade shared React eslint plugin

CHANGELOG.md, package.json
Keeping `next` in sync with `main`.
=> chore(release): 5.3.1

docs/ICONS.md
Add a note describing what to check for when adding a new icon.
- n/a (changes only a markdown file)
=> docs(icons): update validation instructions

docs/ICONS.md, src/components/DragDrop/DragDrop.stories.tsx, src/components/DragDrop/__snapshots__/DragDrop.test.ts.snap, src/components/Grid/Grid.stories.tsx, src/components/Grid/__snapshots__/Grid.test.ts.snap, src/components/Toolbar/Toolbar.stories.tsx, src/components/Toolbar/__snapshots__/Toolbar.test.ts.snap
This PR is for the stories:
https://app.shortcut.com/czi-edu/story/216433/use-tailwind-utility-classes-in-story-files:
All story files should use [Tailwind classes](https://tailwindcss.com/docs/installation). This task is to audit stories.tsx files within src/components. For each file:
replace any usage of utility classes (these start with "u-") with Tailwind utilities.
Run Storybook command: yarn storybook
Build Chromatic.
=> chore: use tailwind utility classes in story files

CHANGELOG.md, package.json
=> chore(release): 6.0.1

README.md, docs/PUBLISHING.md
Update some docs about publishing
nada
=> Update some docs about publishing

.storybook/pages/CoursePlannerEdit/CoursePlannerEdit.module.css, .storybook/pages/CoursePlannerEdit/CoursePlannerEdit.tsx, .storybook/pages/CoursePlannerStep1/CoursePlannerStep1.module.css, .storybook/pages/CoursePlannerStep1/CoursePlannerStep1.tsx, .storybook/pages/ProjectOverview/ProjectOverview.module.css, .storybook/pages/ProjectOverview/ProjectOverview.tsx, postcss.config.js, src/components/Section/Section.stories.module.css, src/components/Section/Section.stories.tsx, src/components/Section/__snapshots__/Section.test.ts.snap
This PR is to clean up utilities classes
1) u-margin-top-xl-mobile
2) u-theme-typography-body-text-xs-bold
Updated with tailwind classes and css modules styles.
1) run storybook.
2) run test.
3) run chromatic to verify UI changes.
=> chore: clean up last couple of utility class usages

.storybook/components/Docs/Documentation.tsx, .storybook/components/GettingStarted/GettingStartedDocumentation.tsx, .storybook/components/IconGrid/IconGrid.tsx, .storybook/recipes/NumberIconList/NumberIconList.tsx, .storybook/recipes/PageShell/PageShell.tsx, .storybook/recipes/TableCard/TableCard.tsx, plop-templates/Recipe/Recipe.tsx.hbs, src/components/Banner/Banner.tsx, src/components/CardHeader/CardHeader.tsx, src/components/Heading/Heading.tsx, src/components/TextField/TextField.tsx
We already went through and updated most of the components to have meaningful comments, but there are still a couple of lingering ones that have the old default undescriptive comment or have no description of the component/recipe.
I'm also removing comments on documentation pages because those are worthless.
Go through the components that have been updated and verify their updated component comments appear in the docs tab in storybook.
=> docs: all components and recipes have meaningful comments

src/components/DragDrop/DragDrop.module.css
Updating another tier 1 token used in a component to enable theming by downstream products in the future. This one is in the `DragDrop` component.
Verify there are no visual changes in the `DragDrop` component.
=> chore(drag-drop): use tier 2 token for background color

.storybook/recipes/Filters/Filters.stories.tsx, .storybook/recipes/Filters/Filters.tsx
[EDS-334]
Adds a table to the filters recipe, where toggling the filters will actively filter the table.
Table shows on storybook.
Table is filtered by the filters.
Filters is still Drawer when small breakpoints, Popover for large breakpoints
https://user-images.githubusercontent.com/86632227/201823130-71899541-0cf3-4cba-9232-345fdd31fdf2.mov
https://user-images.githubusercontent.com/86632227/201823140-548a1502-e249-4372-aa4f-86d75e4adcd1.mov
[EDS-334]: https://czi-tech.atlassian.net/browse/EDS-334?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add table to filters recipe

CHANGELOG.md, package.json
Keepign in sync with `main` : https://github.com/chanzuckerberg/edu-design-system/pull/1392
=> chore(release): 7.0.0

.storybook/preview.tsx, src/components/Skeleton/Skeleton.module.css, src/components/Skeleton/Skeleton.stories.tsx, src/components/Skeleton/Skeleton.test.ts, src/components/Skeleton/Skeleton.tsx, src/components/Skeleton/__snapshots__/Skeleton.test.ts.snap, src/components/Skeleton/index.ts, src/index.ts
* add known three states for use
* default to round-rect and document others
* add tests for each and layout
=> feat(Skeleton): add skeleton components

CHANGELOG.md, package.json
=> chore(release): 7.2.0

CHANGELOG.md, package.json
=> Release v7.2.1

.storybook/pages/AlongDemo/AlongDemo.tsx
- fill-rule => fillRule
- cilp-rule => clipRule
- n/a
=> chore: use recognized React SVG props in demo

.storybook/pages/FeedbackOverview/FeedbackOverview.tsx, src/components/TimelineNav/TimelineNav.module.css, src/components/TimelineNav/TimelineNav.stories.tsx, src/components/TimelineNav/TimelineNav.tsx, src/components/TimelineNav/__snapshots__/TimelineNav.test.ts.snap
=> fix(TimelineNav): remove unused props and styles

.eslintrc, .github/workflows/test.yml, .storybook/pages/WireframeDemo/WireframeDemo.tsx, .storybook/recipes/BaselineCard/BaselineCard.tsx, docs/COMPONENTS.md, docs/ICONS.md, package.json, src/components/Breadcrumbs/Breadcrumbs.tsx, src/components/ButtonDropdown/ButtonDropdown.tsx, src/components/DragDropItem/DragDropItem.tsx, src/components/DropdownMenuItem/DropdownMenuItem.tsx, src/components/FieldsetItems/FieldsetItems.tsx, src/components/InlineNotification/InlineNotification.tsx, src/components/Layout/Layout.module.css, src/components/LayoutContainer/LayoutContainer.stories.tsx, src/components/Menu/Menu.module.css, src/components/TimelineNav/TimelineNav.module.css, src/components/TimelineNav/TimelineNav.stories.tsx, src/components/TimelineNav/TimelineNav.tsx, src/components/Toolbar/Toolbar.stories.tsx
- remove any comments that have no clear call to action
- create follow up tickets for units of work that can be addressed
- convert some comments to Notes for information purposes
=> chore: remove and audit TODO comments

src/components/TimelineNav/TimelineNav.stories.tsx
- use the `viewport` and `chromatic` parameters to generate a snapshot with the collapsed view of the timeline nav component
=> test(TimelineNav): add mobile layout test

.storybook/preview.tsx, .storybook/util/viewports.ts, src/components/Skeleton/Skeleton.stories.tsx, src/components/TimelineNav/TimelineNav.stories.tsx
- update storybook parameters to use known device viewports
- update names of background colors to match token names
=> docs: update viewport and background params

docs/GETTING_STARTED.md
update details describing what's in storybook, and provide more clarity on how to navigate the content provided by storybook.
- n/a
=> docs: update getting started documentation

.github/pull_request_template.md, docs/CONTRIBUTING.md
- updates this pull request template with a test plan
- Create an [alpha publish](https://github.com/chanzuckerberg/edu-design-system/blob/main/docs/PUBLISHING.md#alpha-release) and try out in `edu-stack` or `traject` as a sanity check if changes affect build or deploy, or are breaking.
=> docs: update pull request template and specify squash merge

CHANGELOG.md, package.json
Keeping in sync with `main`: https://github.com/chanzuckerberg/edu-design-system/pull/1498
=> chore(release): 9.1.0

plop-templates/Component/Component.stories.ts.hbs
- add in changes that fix lint complaints
- n/a (template changes on non-user files
=> chore: update plop file format

src/components/Label/Label.module.css, src/components/Select/Select.module.css, src/components/Select/Select.tsx, src/components/Select/__snapshots__/Select.test.tsx.snap, src/design-tokens/mixins.css
- remove little used helper mixin, and apply typography to labels
- add overline container to match label structure for textarea and input fields
- EDS-841
=> fix(Select): sync label design with form fields

src/components/Input/Input.tsx, src/components/InputField/InputField.tsx
- specifies change event handler type in Input for QOL
- build EDS
- copy / paste `Input` and `InputField` folders into node_modules of gst
-  following doesn't have type error:
```
<InputField
className="py-5"
label={label}
onChange={(e) => onChange(id, e.target.value)}
value={selection}
/>
```
=> test(input): specify change event handler type

CHANGELOG.md, package.json
* remove data-bootstrap-override EDS-850
* **Avatar:** add avatar component ([#1510](https://github.com/chanzuckerberg/edu-design-system/issues/1510)) ([bc21f85](https://github.com/chanzuckerberg/edu-design-system/commit/bc21f85baf6d906d40d24da7e7108d60aaadc2b5))
* **slider:** create slider ([#1503](https://github.com/chanzuckerberg/edu-design-system/issues/1503)) ([e7ced34](https://github.com/chanzuckerberg/edu-design-system/commit/e7ced34ff5c80c0776682ba912b5a69fac4507d8))
* **TextareaField:** add TextArea base component and TextareaField ([#1493](https://github.com/chanzuckerberg/edu-design-system/issues/1493)) ([f2ba31d](https://github.com/chanzuckerberg/edu-design-system/commit/f2ba31df82322e589c98b337da2cdde7184639a8))
* remove data-bootstrap-override EDS-850 …
=> chore(release): 10.0.0

docs/PUBLISHING.md
- clarify usage of tags upon release
- mention deprecated packages
- add documentation on github automations
- add additional logic checks on release notes
=> docs(Publishing): add automation details and format tweaks

.storybook/components/Docs/MarkdownWrapper.module.css
- clarifies the purpose of the markdown wrapper styling
=> docs(markdownwrapper): clarifying styling

README.md, docs/TOKENS.md, tailwind.config.js
- with updated tailwind config, needed docs update on usage
- updated readme on how to use tailwind config file
- adds table of contents to tokens markdown file
- adds tailwind class tokens sections in tokens markdown file, with examples showing usage
=> docs(token): update tailwind config usage and show utility class e.g.s

src/components/Avatar/Avatar.stories.ts, src/components/Avatar/Avatar.tsx, src/components/InputField/InputField.stories.tsx, src/components/LoadingIndicator/LoadingIndicator.stories.ts, src/components/LoadingIndicator/LoadingIndicator.tsx, src/components/Menu/Menu.stories.tsx, src/components/Menu/Menu.tsx, src/components/PopoverListItem/PopoverListItem.stories.tsx, src/components/PopoverListItem/PopoverListItem.tsx, src/components/ProgressBar/ProgressBar.stories.tsx, src/components/ProgressBar/ProgressBar.tsx, src/components/Radio/Radio.stories.tsx, src/components/Radio/Radio.tsx, src/components/Select/Select.stories.tsx, src/components/Select/Select.tsx, src/components/Skeleton/Skeleton.stories.tsx, src/components/Skeleton/Skeleton.tsx, src/components/Table/Table.stories.tsx, src/components/Table/Table.tsx, src/components/TableBody/TableBody.tsx, src/components/TableCaption/TableCaption.tsx, src/components/TableCell/TableCell.tsx, src/components/TableFooter/TableFooter.tsx, src/components/TableHeader/TableHeader.tsx, src/components/TableHeaderCell/TableHeaderCell.tsx, src/components/TableRow/TableRow.tsx, src/components/TextareaField/TextareaField.stories.tsx, src/components/TextareaField/TextareaField.tsx
- per team discussion, do this once a component has been used in a product
- this only affects documentation. fixes are applied as raised
- n/a (documentation changes)
=> chore: remove beta tags from mature components

.storybook/pages/AlongDemo/AlongDemo.tsx, .storybook/pages/ProjectOverview/ProjectOverview.tsx, .storybook/pages/StudentRefinement/StudentRefinement.tsx, .storybook/pages/WireframeDemo/WireframeDemo.tsx, package.json, src/components/Skeleton/Skeleton.stories.tsx, src/components/Skeleton/__snapshots__/Skeleton.test.ts.snap, tailwind.config.ts, yarn.lock
This PR updates Tailwind to 3.3: https://tailwindcss.com/blog/tailwindcss-v3-3
Lots of cool stuff in this release, but the main reason I want to update it because we can now write our Tailwind config files in TS.
- Will make future config updates (if needed) easier
- Makes it easier to use TS config files in Pilot apps (since they will be importing EDS's config)
- CI + Chromatic
=> chore: Tailwind 3.3 and TS config file

.storybook/recipes/Sliders.stories.tsx, .storybook/recipes/TabularInputs.stories.tsx
- create a recipe showing how to one can use `Table`, `Input`, and `Label` to create a tabular form input structure
=> docs(Table): add recipe showing input with split label

.storybook/recipes/LoadingProfileCard.stories.tsx, src/components/Skeleton/Skeleton.stories.tsx, src/components/Skeleton/__snapshots__/Skeleton.test.ts.snap
- move card example from skeleton state docs
- create separate recipe with example controls
- add separate recipe snapshots
=> docs: add profile card recipe using skeleton state

.storybook/recipes/Sliders.stories.tsx, src/components/InputField/InputField.module.css, src/components/InputField/InputField.stories.tsx, src/components/InputField/InputField.tsx, src/components/InputField/__snapshots__/InputField.test.ts.snap
- add a class which selectively applies a bottom margin
- verify snapshots don't change for existing stories
=> fix(InputField): apply bottom margin only with fieldNote

.storybook/recipes/Filters/Filters.tsx, src/components/Heading/Heading.tsx, src/components/Icon/Icon.stories.tsx, src/components/TimelineNavPanel/TimelineNavPanel.tsx, tsconfig.json
- fix up places that were relying on that rule
- do this now, as a future version of TS will ignore this override and start breaking everything
- make sure all tests pass
=> fix: restore check for undefined any types

src/components/DataBar/DataBar.stories.tsx, src/components/Dropdown/Dropdown.stories.tsx, src/components/Heading/Heading.stories.tsx, src/components/Modal/Modal.stories.tsx, src/components/Modal/__snapshots__/Modal.test.tsx.snap, src/components/ProgressBar/ProgressBar.stories.tsx, src/components/Tabs/Tabs.stories.tsx, src/components/Text/Text.stories.tsx
- re-enable any snapshots that do not seem flaky
- add a reason to any tests that explain why its skipped
- review flakiness of any snapshots
=> test: audit disabled test snapshots

.github/CODEOWNERS, package.json
- update the codeowners file with the proper team name
- update the author in package.json with the same handle
- use visual codeowners check file in GH
- check email alias in google groups
=> chore: update CODEOWNERS with new team designation

docs/PUBLISHING.md
This link is for future reference, for teams that may linger on older builds of EDS
- n/a (docs)
=> docs: add note to add storybook link to release notes

src/components/Accordion/Accordion.stories.tsx, src/components/Badge/Badge.stories.tsx, src/components/Popover/Popover.tsx, src/components/Slider/Slider.stories.tsx, src/design-tokens/mixins.css
- sync statuses with figma and zeroheight documentation
- define unused or missing token values in existing components
- verify search bar component color is defined
- verify storybook component statuses match what was discussed
=> fix: clean component statuses and tokens

README.md, codecov.yml
This should remove the stories and other test files from the code coverage, since it's currently reporting on those. Test how ignore changes the reporting.
- also add badge for coverage
- test how the coverage changes by ignoring the test and story files from reporting
=> chore: ignore test files in test coverage report

codecov.yml
- jest making sure the regex was doing the right thing
- n/a
=> chore: expand codecov ignore values

src/components/Avatar/Avatar.module.css
- verify change to snapshot as needed
=> fix(Avatar): adjust the tier 2 token used in size 'sm'

.storybook/components/DesignTokens/Tier1/TypographyPresets.jsx, .storybook/components/DesignTokens/Tier1/TypographyPresets.module.css, .storybook/components/DesignTokens/Tier2/TypographyUsage.jsx, src/design-tokens/tier-1-definitions/typography-presets.css, src/design-tokens/tier-2-usage/typography-usage.css
- add 001-008 light
- add 008 regular
- verify updates to storybook snapshots
=> feat(Typography): add light weight type ramp entries

src/components/FiltersDrawer/FiltersDrawer.test.tsx
Test is flaky probably due to some async things going on, and I am skipping.
Ticket to investigate and re-enable: [EDS-1008]
[EDS-1008]: https://czi-tech.atlassian.net/browse/EDS-1008?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> test(filtersdrawer): skip flaky test

.gitignore, package.json, yarn.lock
- add in CLI dependency for later use
- update dependencies in lock files
- n/a (updating dependencies for later use)
=> chore(deps): add Omlet tooling

src/components/InputField/InputField.module.css, src/components/InputField/InputField.tsx, src/components/InputField/__snapshots__/InputField.test.ts.snap
- change component to use a span tag
- use text/neutral-subtle
- update test snapshots
=> fix(InputField): fix alignment and color for required marker

src/components/ProgressBar/ProgressBar.module.css, src/components/ProgressBar/ProgressBar.tsx, src/components/ProgressBar/__snapshots__/ProgressBar.test.ts.snap
- use label-md instead of title-md
- use text/neutral-subtle (currently inherits)
=> fix(ProgressBar): align label and caption with design

.github/workflows/release.yml
- add the config now, in prep for doing a release later this week
- use the newly-added token to test against `init`'d analysis
- n/a
=> chore: add test command to update omlet on release

.storybook/data/tokens.json, .storybook/pages/AlongDemo/AlongDemo.module.css, .storybook/pages/AlongDemo/GlobalStyles.module.css, src/components/ClickableStyle/ClickableStyle.module.css, src/design-tokens/tier-3-component/buttons.json, src/tokens-dist/css/variables.css, src/tokens-dist/json/variables-nested.json
[EDS-954]
- adds and uses t3 token for button border radius
- synced with design on 6/23 to align on token naming
[EDS-954]: https://czi-tech.atlassian.net/browse/EDS-954?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(button): create t3 token for border radius

.github/workflows/release.yml
- add fetch-depth so git history is readable
- See config example in linked ticket
- n/a
=> chore: update analysis config to preserve history

.storybook/components/Docs/Guildelines/Tokens.stories.mdx, .storybook/components/Docs/Guildelines/Typography.stories.mdx
- remove lingering pointers to old typography token naming
- n/a
=> docs(Typography): update links for tokens

docs/PUBLISHING.md
Modify PUBLISHING.md to include hotfix steps
- n/a (docs)
=> docs: add hotfix release instructions

src/components/Breadcrumbs/Breadcrumbs.stories.tsx
- hopefully stops breadcrumb diff false positives
- brumbs no longer flaky on chromatic
=> test(breadcrumbs): add chromatic diffthreshold

.storybook/data/tokens.json, src/tokens-dist/css/variables.css, src/tokens-dist/json/variables-nested.json, src/tokens-dist/ts/colors.ts
update exported values for link tokens
- updated snapshots 
- verify no diff is generated when running `yarn start`
=> fix: update token exports

src/components/Accordion/Accordion.tsx, src/components/Badge/Badge.tsx, src/components/Slider/Slider.tsx
Update components after audit with design team. 
=> docs: remove errant beta flags from mature components

README.md, docs/CONTRIBUTING.md
Combine the developer documentation as we streamline the README to focus on the package consumer experience.
=> docs: consolidate contribution documentation

README.md
Add some details about how to apply the tailwind config from EDS.
=> docs: clarify EDS tailwind config doc.s

src/components/Tabs/Tabs.module.css, src/components/Tabs/Tabs.stories.tsx, src/components/Tabs/Tabs.tsx, src/components/Tabs/__snapshots__/Tabs.test.tsx.snap, src/util/variant-types.ts
- allow: left, right, center
- remove on scrollable
- add snapshots
=> feat(Tabs): add variant for controlling tab header alignment

package.json, yarn.lock
update to latest published version
- n/a (minor version update)
=> chore: update omlet cli dependency

package.json, tsconfig.json, yarn.lock
=> chore: update jest dom to v6

src/tokens-dist/css/variables.css
Update some of the generated comments around specific tokens
- n/a documentation-only change
=> docs(tokens): update deprecation markers

src/components/InlineNotification/InlineNotification.stories.tsx, src/components/InlineNotification/InlineNotification.tsx, src/components/InlineNotification/__snapshots__/InlineNotification.test.ts.snap
- remove yield variant from stories
- remove inactive from stories
- mark yield variant and inactive prop as deprecated
=> feat(InlineNotification): remove deprecated variants

src/components/Select/Select.stories.tsx, src/components/Select/Select.test.tsx, src/components/Select/Select.tsx, src/components/Select/__snapshots__/Select.test.tsx.snap
- add handling for onClick on Select.Button and Select.ButtonWrapper
- add patch wrapper so that onChange only fires when SelectedValue changes
- add stories to demonstrate behavior
- add tests to cover event behaviors
=> feat(Select): add ability to handle click and change event handlers

.storybook/components/Docs/Guidelines/Theming.stories.mdx
Fix up a few small nits discovered while testing the instructions
=> docs(Theming): update example code with canonical import details

bin/_util.js, bin/_util.test.js
- cover remaining utilities in EDS _utils
=> test(util): add coverage

src/components/InputField/InputField.tsx
- This property is unconnected from the input field, and not used.
=> feat(InputField)!: remove unused prop requiredLabel

src/components/Button/Button-v2.module.css, src/components/Button/Button-v2.stories.tsx, src/components/Button/Button-v2.tsx
**Recreating the PR to have proper integrations kick off**
=> feat(Button)!: introduce v2.0 component

src/components/Menu/Menu-v2.module.css, src/components/Menu/Menu-v2.stories.tsx, src/components/Menu/Menu-v2.tsx, src/components/Menu/index.ts, src/components/PopoverContainer/PopoverContainer-v2.module.css, src/components/PopoverContainer/PopoverContainer-v2.stories.tsx, src/components/PopoverContainer/PopoverContainer-v2.tsx, src/components/PopoverContainer/index.ts, src/components/PopoverListItem/PopoverListItem-v2.module.css, src/components/PopoverListItem/PopoverListItem-v2.stories.ts, src/components/PopoverListItem/PopoverListItem-v2.tsx, src/components/PopoverListItem/index.ts, src/components/Text/Text.tsx
- add stories
- also update constituent sub-components
- set up snapshots to update
=> feat(Menu)!: introduce 2.0 component

src/components/InputLabel/InputLabel-v2.module.css, src/components/InputLabel/InputLabel-v2.stories.ts, src/components/InputLabel/InputLabel-v2.tsx, src/components/Radio/Radio-v2.module.css, src/components/Radio/Radio-v2.stories.tsx, src/components/Radio/Radio-v2.tsx, src/components/Radio/index.ts
=> feat(Radio)!: introduce 2.0 component

src/components/Accordion/Accordion-v2.module.css, src/components/Accordion/Accordion-v2.stories.tsx, src/components/Accordion/Accordion-v2.tsx
- add stories
- remove deprecated functionality
- update examples as needed
=> feat(Accordion)!: introduce 2.0 component

src/components/BannerNotification/BannerNotification.module.css, src/components/BannerNotification/BannerNotification.stories.tsx, src/components/BannerNotification/BannerNotification.test.ts, src/components/BannerNotification/BannerNotification.tsx, src/components/BannerNotification/__snapshots__/BannerNotification.test.ts.snap, src/components/BannerNotification/index.ts, src/components/InlineNotification/InlineNotification-v2.tsx
- add in stories
- add in new component, nested under v2 folder
=> feat(BannerNotification)!: introduce 2.0 component

src/components/TextareaField/TextareaField-v2.module.css
=> chore(TextareaField): apply padding update

src/components/Button/index.ts, src/components/Link/Link-v2.stories.tsx, src/components/Link/Link-v2.tsx, src/components/Link/index.ts, src/index.ts
- check whether build completes
=> chore: export types

src/components/ButtonGroup/ButtonGroup-v2.module.css
=> chore(ButtonGroup): align padding with design

src/components/Card/index.ts
=> chore(Card): update v2.0 export

src/components/FieldNote/FieldNote-v2.stories.tsx, src/components/FieldNote/FieldNote-v2.tsx
- based on review feedback from design review
=> chore: update/reduce component props

src/components/Select/Select-v2.stories.tsx, src/components/Select/Select.stories.tsx, src/components/Tooltip/Tooltip-v2.stories.tsx
=> docs: update Select and Tooltip (v2) documentation

src/components/Button/Button-v2.module.css, src/components/Button/Button-v2.stories.tsx, src/components/Button/Button-v2.test.tsx, src/components/Button/Button-v2.tsx, src/components/Button/__snapshots__/Button-v2.test.tsx.snap
=> fix(Button): align disabled treatment to latest design

src/components/TextareaField/TextareaField-v2.module.css, src/components/TextareaField/TextareaField-v2.tsx, src/components/TextareaField/__snapshots__/TextareaField-v2.test.tsx.snap
- add bottom line for readonly field
- move character counter to the top line of the component
=> fix(TextareaField): address QA updates

src/components/InlineNotification/InlineNotification-v2.module.css, src/components/InlineNotification/InlineNotification-v2.test.ts, src/components/InlineNotification/InlineNotification-v2.tsx, src/components/InlineNotification/__snapshots__/InlineNotification-v2.test.ts.snap
=> fix(InlineNotification): address QA updates

src/components/Button/Button-v2.module.css, src/components/Button/Button-v2.tsx, src/components/Button/__snapshots__/Button-v2.test.tsx.snap
=> fix(Button): address QA degisn feedback

src/components/Toast/index.ts, src/components/ToastNotification/ToastNotification.module.css, src/components/ToastNotification/ToastNotification.stories.ts, src/components/ToastNotification/ToastNotification.test.ts, src/components/ToastNotification/ToastNotification.tsx, src/components/ToastNotification/__snapshots__/ToastNotification.test.ts.snap, src/components/ToastNotification/index.ts, src/index.ts
- rename component and introduce QA fixes for button/icon alignment
=> feat(ToastNotification)!: rename from Toast to ToastNotification

.storybook/preview.tsx, src/components/AppNotification/AppNotification.module.css, src/components/AppNotification/AppNotification.stories.tsx, src/components/AppNotification/AppNotification.test.ts, src/components/AppNotification/AppNotification.tsx, src/components/AppNotification/__snapshots__/AppNotification.test.ts.snap, src/components/AppNotification/index.ts, src/components/Button/Button-v2.module.css, src/components/ButtonGroup/ButtonGroup-v2.module.css, src/components/ButtonGroup/ButtonGroup-v2.stories.tsx, src/components/ButtonGroup/ButtonGroup-v2.tsx, src/index.ts
- add component with specified design and code API
- add in tests and stories
=> feat(AppNotification)!: introduce 2.0 component

src/components/Accordion/__snapshots__/Accordion-v2.test.tsx.snap, src/components/NumberIcon/NumberIcon-v2.module.css, src/components/NumberIcon/NumberIcon-v2.stories.tsx, src/components/NumberIcon/NumberIcon-v2.tsx
=> fix(NumberIcon): address QA design notes

src/components/Link/Link-v2.stories.tsx, src/components/Link/Link-v2.tsx, src/components/Link/__snapshots__/Link-v2.test.tsx.snap
- n/a (simple expanded type; verify existing tests pass)
=> feat(Link): allow nodes to be used in link body

package.json, yarn.lock
testing usage of new chromatic major version. include any changes needed from upgrading from 9.x to 11.x
=> chore: update chromatic dep to 11.x+

src/components/TabGroup/TabGroup.module.css, src/components/TabGroup/TabGroup.stories.tsx, src/components/TabGroup/TabGroup.tsx, src/components/TabGroup/__snapshots__/TabGroup.test.tsx.snap
- add `variant` prop
- use default `default` and provide `inverse`
- add story and update snapshots.
=> feat(TabGroup): add inverse variant treatment

src/components/Select/Select-v2.module.css, src/components/Select/Select-v2.stories.tsx, src/components/Select/Select-v2.tsx, src/components/Select/__snapshots__/Select-v2.test.tsx.snap
- update and add snapshots and stories for this
- also add story descriptions and updated code blocks
- update display of graphical stories
=> feat(Select): support horizontal labels

src/components/Checkbox/Checkbox-v2.module.css
=> refactor(Checkbox): use characters for check state

.storybook/components/Docs/Guidelines/Theming.stories.mdx
=> docs: add recommended utility class usage

src/components/Button/Button-v2.module.css, src/components/Button/Button-v2.stories.tsx, src/components/Button/__snapshots__/Button-v2.test.tsx.snap
=> feat(Button): update interactive styles for tertiary buttons

src/components/Link/Link-v2.module.css, src/components/Link/Link-v2.stories.tsx, src/components/Link/Link-v2.tsx, src/components/Link/__snapshots__/Link-v2.test.tsx.snap
=> feat(Link): add inverse variant (with variant prop)

src/components/Button/Button-v2.module.css, src/components/Button/Button-v2.stories.tsx, src/components/Button/Button-v2.tsx, src/components/Button/__snapshots__/Button-v2.test.tsx.snap
=> fix(Button): mark disable usage as invalid

src/components/Link/Link-v2.module.css
=> fix(Link): align icons in flexed standalone container

src/bin/migrate/transforms/edit-jsx-prop.test.ts
removing errant `console.log` line
- n/a (only affects testing)
=> chore: remove console.log line

.storybook/preview.tsx, src/components/Modal/Modal.module.css, src/components/Modal/Modal.stories.tsx, src/components/Modal/Modal.test.tsx, src/components/Modal/Modal.tsx, src/components/Modal/__snapshots__/Modal.test.tsx.snap
Bumping `Modal` to 2.1 with the following functionality:
- allow fixed (default), auto, and max
- add stories with doc.s
=> feat(Modal): add height property to modal API

LICENSE, README.md
- also update the copyright year
=> docs: add clarity to what EDS repository provides

.storybook/components/Docs/GettingStarted.mdx, .storybook/components/Docs/Guidelines/CodeGuidelines.mdx, .storybook/components/Docs/Guidelines/Components.mdx, .storybook/components/Docs/Guidelines/Icons.mdx
=> docs: update contribution documentation

src/components/Button/Button.stories.tsx, src/components/InputField/InputField.stories.tsx, src/components/Link/Link.stories.tsx, src/components/Link/__snapshots__/Link.test.tsx.snap, src/components/ProgressBar/ProgressBar.stories.tsx, src/components/SearchBar/SearchBar.stories.tsx, src/components/Skeleton/Skeleton.stories.tsx, src/components/ToastNotification/ToastNotification.stories.ts, src/components/ToastNotification/ToastNotification.test.tsx, src/components/ToastNotification/ToastNotification.tsx, src/components/Tooltip/Tooltip.stories.tsx
- various component updates to fix component usage warnings
- fixes to usage examples
=> docs: update storybook doc.s

src/components/Card/Card.module.css
Update the spacing between `eyebrow` and `title` to match design
=> fix(Card): add spacing between eyebrow and title

docs/PUBLISHING.md
=> docs: update publishing documentation

.github/workflows/test.yml, CHANGELOG.md, package.json, tailwind.config.ts, yarn.lock
[Storybook](https://61313967cde49b003ae2a860-jyqlmpntqz.chromatic.com/)
* **tailwind:** update animation token export types ([#2047](https://github.com/chanzuckerberg/edu-design-system/issues/2047)) ([0f95301](https://github.com/chanzuckerberg/edu-design-system/commit/0f9530114f7f323b065688c4b5472ce2f041d64d))
=> Release v15.3.1

src/index.ts
- n/a (all existing tests should pass; no functionality changes)
=> chore: group all 2.x exports

src/components/Input/Input.module.css, src/components/TextareaField/TextareaField.module.css, src/design-tokens/mixins.css
- delete mixins that aren't used anymore
- rename any 'V2' mixins
- add some block comments to describe contents
Mostly, the build should pass and existing checks should pass as well. Also, no snapshot changes.
=> chore: remove unused mixins

src/components/Menu/Menu.stories.tsx, src/components/Menu/__snapshots__/Menu.test.tsx.snap
=> docs(Menu): demonstrate code examples and custom triggers

.storybook/components/Docs/Guidelines/CodeGuidelines.mdx, docs/CONTRIBUTING.md
=> docs: add additional contribution documentation

src/components/SelectionChip/SelectionChip.module.css, src/components/SelectionChip/SelectionChip.stories.ts, src/components/SelectionChip/SelectionChip.test.ts, src/components/SelectionChip/SelectionChip.tsx, src/components/SelectionChip/__snapshots__/SelectionChip.test.ts.snap, src/components/SelectionChip/index.ts, src/index.ts
=> feat(SelectionChip): introduce 1.0 component

.github/CODEOWNERS
remove old infra team from CODEOWNERS
=> chore(CODEOWNERS): remove old team code owners

CHANGELOG.md, package.json, src/components/Button/Button.module.css
[Storybook](https://61313967cde49b003ae2a860-rzashkyqcn.chromatic.com/)
* **button:** update button sizes in icon only to have a minimum width ([#2130](https://github.com/chanzuckerberg/edu-design-system/issues/2130)) ([8a312e8](https://github.com/chanzuckerberg/edu-design-system/commit/8a312e8c0e6acbe9e9b0aeeb5325bf97761b0298))
=> Release v15.10.2

src/components/DataTable/DataTable.tsx, src/components/DataTable/index.ts, src/index.ts
- export utility object with sort directions
- export type derived from the sort directions
- use the type and object in the component
=> feat(DataTable): export sort direction enum with types

src/components/Fieldset/Fieldset.module.css, src/components/Fieldset/Fieldset.tsx, src/components/Fieldset/__snapshots__/Fieldset.test.tsx.snap, src/components/InputField/InputField.module.css
- add temporary shim to the label style to match InputField
- document as HACK to address later (remove FieldLabel?)
=> fix(Fieldset): fix label typography

src/bin/migrate/migrations/15-to-16.ts
This file will house the transforms to run when migrating from EDS v15 to v16. Includes the basic documentation examples, and empty arrays to add migrations to. Migrations will be added as code changes are made to components.
Merging into `v16` as part of the prep work for the next major release
=> chore: set up shell script for running migrations

.storybook/components/Docs/Guidelines/CodeGuidelines.mdx, src/components/Badge/Badge.stories.tsx, src/components/Badge/Badge.tsx, src/components/Breadcrumbs/Breadcrumbs.tsx, src/components/Fieldset/Fieldset.tsx, src/components/HorizontalStepper/HorizontalStepper.stories.tsx, src/components/HorizontalStepper/HorizontalStepper.tsx, src/components/Label/Label.module.css, src/components/Label/Label.tsx, src/components/ProgressBar/ProgressBar.stories.tsx, src/components/ProgressBar/ProgressBar.tsx, src/components/SearchBar/SearchBar.stories.tsx, src/components/SearchBar/SearchBar.tsx, src/components/Slider/Slider.stories.tsx, src/components/Slider/Slider.tsx, src/components/Tag/Tag.tsx, src/components/Text/Text.module.css, src/components/ToastNotification/ToastNotification.tsx, src/design-tokens/mixins.css, src/util/variant-types.ts
This is some safe preparatory work to signal deprecated components, tokens, and other content to be removed in v16. Proactively marking/documenting some components as deprecated for the next minor/patch release of EDS.
=> chore: add marker comments to places where code should be removed

CHANGELOG.md, bin/eds-import-from-figma-api.js, package.json
[Storybook](https://61313967cde49b003ae2a860-ljbkbonyxu.chromatic.com/)
* **scripts:** add locality check to value pre-validation ([#2154](https://github.com/chanzuckerberg/edu-design-system/issues/2154)) ([5f2ad71](https://github.com/chanzuckerberg/edu-design-system/commit/5f2ad710d1ba407db94e7a0ccf47a340d36ee449))
=> Release v15.11.2

package.json, yarn.lock
Use latest: https://github.com/dsherret/ts-morph/releases/tag/25.0.1
=> fix(deps)!: update dependency ts-morph to v25

src/components/AppNotification/AppNotification.module.css, src/components/AppNotification/AppNotification.stories.tsx, src/components/AppNotification/AppNotification.tsx, src/components/AppNotification/__snapshots__/AppNotification.test.ts.snap
- add in the new prop to use, instead of color
- add in assertion to check if color is used
- mark color as deprecated
- update tests and snapshots
=> feat(AppNotification): add variant prop with assert

bin/_util.js, bin/_util.test.js, bin/eds-import-from-figma-api.js
- use enquirer to prompt for tier information
- add in checks for the correct tier values being used
- remove brittle constants in script
- clean up some comments and documentation
- add better UI for script initializing
- update tests
=> feat(script): add interactive options for selecting token tier information

src/components/AppNotification/AppNotification.stories.tsx, src/components/AppNotification/__snapshots__/AppNotification.test.ts.snap, src/components/Modal/__snapshots__/Modal.test.tsx.snap
- use render in stories to select button variant
=> fix(AppNotification): add in dynamic updates to children based on variant

tailwind.config.ts
Also, minor refactoring since all reducers are exactly the same now.
In their wisdom, the Tailwind folk named their utility classes `rounded-*` so these won't map to the property name like most of the other util.s, unfortunately.
=> fix(tailwind): add in settings to use EDS border radii tokens with tailwind

.storybook/data/tokens.json, bin/eds-import-from-figma-api.js, src/components/Heading/Heading.module.css, src/components/Text/Text.module.css, src/design-tokens/core-tokens.json, src/tokens-dist/css/variables.css, src/tokens-dist/json/variables-nested.json
- add in eds-theme-typography-font-style-headline-decorative-inline
- make proper use in Heading component
- make proper use in Text component
- run `yarn build:tokens` to build generated files
=> fix: fix typography token and usages

src/components/Modal/Modal.module.css, src/components/Modal/Modal.stories.tsx, src/components/Modal/Modal.tsx, src/components/Modal/__snapshots__/Modal.test.tsx.snap
Add in support for `size` value `"full"`. Update stories to account for this new functionality
=> feat(Modal): add in full size modal
